### ISSUE TITLE
Crash when displaying Sync Overview

### ISSUE THREAD

**Issue by Rewt0r** [canton7/SyncTrayzor#113]
This error appeared when clicking the tray icon to display the Sync Overview on a new machine in the cluster.

```
Version: 1.0.22.33; Variant: Portable; Arch: Amd64
Path: C:\Sync\SyncTrayzor\SyncTrayzor.exe
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at SyncTrayzor.Pages.FileTransfersTrayViewModel.TransferCompleted(Object sender, FileTransferChangedEventArgs e) in c:\projects\synctrayzor\src\SyncTrayzor\Pages\FileTransfersTrayViewModel.cs:line 187
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Dup #108  - this will be fixed in the next release, or grab a build off https://ci.appveyor.com/project/canton7/synctrayzor
