### ISSUE TITLE
Heads up: Windows Group policy when executing from to AppData

### ISSUE THREAD

**Issue by jaredthirsk** [canton7/SyncTrayzor#12]
I got this exception when I first tried your application, and it asked me to post it here:

System.ComponentModel.Win32Exception (0x80004005): This program is blocked by group policy. For more information, contact your system administrator
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SyncTrayzor.SyncThing.SyncThingProcessRunner.Start() in h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingProcessRunner.cs:line 93
   at SyncTrayzor.SyncThing.SyncThingManager.Start() in h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 141
   at SyncTrayzor.Bootstrapper.OnLaunch() in h:\Users\Antony\Documents\projects\SyncTrayzor\src\SyncTrayzor\Bootstrapper.cs:line 91
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jaredthirsk** [comment]
Fix for me:  

I had installed CryptoPrevent (http://www.foolishit.com/vb6-projects/cryptoprevent/).

I simply needed to add a whitelist entry for syncthing.exe in the c:\users\myname\AppData\Roaming\Synctrayzor\ folder.

**Comment by canton7** [comment]
Aha, neat little utility. It's quite right to flag up Syncthing - but sadly I don't have a choice if I want to allow auto updates.

I think the right thing to do here is handle that exception by showing a dialog which says something along the lines of "Hey, couldn't start Syncthing because of group policy stuff. Please make sure you configure any hyper-alert malware detection programs and try again" (and not exit). I'll also add a note to the README (and I can do that now).

Does that sound sensible?

**Comment by jaredthirsk** [comment]
Yeah, that makes sense!
