### ISSUE TITLE
Startup Crashes

### ISSUE THREAD

**Issue by atoav** [canton7/SyncTrayzor#131]
Windows 8.1 x64. Had no problems for months. Now it crashes. Did a reinstall and everything, didn't help:

---
Version: 1.0.22.33; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.Configuration.ConfigurationErrorsException: Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section. ---> System.Net.Sockets.SocketException: The requested service provider could not be loaded or initialized
   at System.Net.NetworkAddressChangePolled..ctor()
   at System.Net.AutoWebProxyScriptEngine.AutoDetector.Initialize()
   at System.Net.AutoWebProxyScriptEngine..ctor(WebProxy proxy, Boolean useRegistry)
   at System.Net.WebProxy.UnsafeUpdateFromRegistry()
   at System.Net.Configuration.DefaultProxySectionInternal..ctor(DefaultProxySection section)
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   --- End of inner exception stack trace ---
   at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__24.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__18.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__10.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Interesting.

Can you down this file https://gist.githubusercontent.com/canton7/5c657ac11bce6da6c1f3/raw/035af840ccd1515e0b0175c5c315b01cfcd8b266/SyncTrayzor.exe.config and save it as `C:\Program Files\SyncTrayzor\SyncTrayzor.exe.config` overwriting the file that is there currently please?

**Comment by atoav** [comment]
Now it starts and gives me the errormessage 
```
Failed to start Syncthing. 
Please read the log to determine the cause. If "FATAL: Cannot open database" appears, please close any other instances of Syncthing. 
If SyncTrayzor crashed previously, there may still be zombine Syncthing processes alive. 
Please use the menu option "Syncthing -> Kill all Syncthing processes" to stop them, then use "Syncthing -> Start" to start Syncthing again.
```

I tried exactly that, but it shows that same alert over and over.

The log:
```
2015-08-11 17:05:28.5854 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: Kill all Syncthing processes 
2015-08-11 17:05:30.2999 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: SyncThingProcessRunner.Start called 
2015-08-11 17:05:30.2999 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Starting 
2015-08-11 17:05:30.2999 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Stopped -> Starting 
2015-08-11 17:05:30.2999 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Starting syncthing: C:\Users\d0\AppData\Roaming\SyncTrayzor\syncthing.exe 
2015-08-11 17:05:30.2999 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Starting API clients 
2015-08-11 17:05:30.2999 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Attempting to request API using version 0.11.x API client 
2015-08-11 17:05:30.3152 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Failed to connect on attempt 0 
2015-08-11 17:05:30.7375 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [OJOZ7] 17:05:30 INFO: syncthing v0.11.7 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-05-31 07:37:02 UTC 
2015-08-11 17:05:30.7375 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [OJOZ7] 17:05:30 INFO: My ID: OJOZ7U4 
2015-08-11 17:05:30.7375 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [OJOZ7] 17:05:30 INFO: Database block cache capacity 64608 KiB 
2015-08-11 17:05:30.8918 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [OJOZ7] 17:05:30 FATAL: Cannot start GUI on "localhost:8384": GetAddrInfoW: A non-recoverable error occurred during a database lookup. 
2015-08-11 17:05:30.9137 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status Error 
2015-08-11 17:05:30.9137 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Starting -> Stopped 
2015-08-11 17:05:30.9137 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Starting -> Stopped 
2015-08-11 17:05:30.9137 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Aborting API clients 
2015-08-11 17:05:30.9381 [Info] SyncTrayzor.SyncThing.SyncThingManager: StartClientAsync aborted 

```

**Comment by canton7** [comment]
Syncthing has a corrupt database by the looks of its error message. You may have to delete its database and allow it to re-index.

**Comment by atoav** [comment]
Tried searching for that db, where is it located usually?

**Comment by canton7** [comment]
It'll be in something like `C:\Users\<You>\AppData\Local\Syncthing\index-v0.11.0.db`. Stop Syncthing, rename that folder, start Syncthing again.

**Comment by SwederSchellens** [comment]
I'm also experiencing crashes at start-up on two different machines. Problems started after upgarding to Windows10. Could that be related?

**Comment by atoav** [comment]
Deleted the db, now I get this. Before I got the message that syncthing.exe in `C:\Program Files\SyncTrayzor\Syncthing.exe`was missing, so I replaced it.
```
Version: 1.0.22.33; Variant: Portable; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.Configuration.ConfigurationErrorsException: Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section. ---> System.Net.Sockets.SocketException: The requested service provider could not be loaded or initialized
   at System.Net.NetworkAddressChangePolled..ctor()
   at System.Net.AutoWebProxyScriptEngine.AutoDetector.Initialize()
   at System.Net.AutoWebProxyScriptEngine..ctor(WebProxy proxy, Boolean useRegistry)
   at System.Net.WebProxy.UnsafeUpdateFromRegistry()
   at System.Net.Configuration.DefaultProxySectionInternal..ctor(DefaultProxySection section)
   at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
   --- End of inner exception stack trace ---
   at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__24.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__18.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__10.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
@SwederSchellens please open another issue, and include all details (such as whether it's Syncthing or SyncTrayzor that's crashing, any error messages, etc).

@atoav You're seeing that error even with the modified `SyncTrayzor.exe.config` I gave you above?

**Comment by atoav** [comment]
Okay amazing, had the config, but now it was gone again, so saved it again, started SyncTrayzor up, it gave me again that warning about the db, which I deleted twice already. So killed again all Syncthing processes, started etc.

SyncTrayzor Log:
```
2015-08-12 10:38:34.1414 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ExePath: C:\Program Files\SyncTrayzor 
2015-08-12 10:38:34.1745 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\d0\AppData\Roaming\SyncTrayzor\logs 
2015-08-12 10:38:34.1925 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncThingBackupPath: C:\Program Files\SyncTrayzor\syncthing.exe 
2015-08-12 10:38:34.1925 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\d0\AppData\Roaming\SyncTrayzor\config.xml 
2015-08-12 10:38:34.1925 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\d0\AppData\Roaming\SyncTrayzor\config-backups 
2015-08-12 10:38:34.1925 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Users\d0\AppData\Local\SyncTrayzor\cef\cache 
2015-08-12 10:38:34.2605 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowSynchronizedBalloon=True ShowDeviceConnectivityBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingApiKey= SyncthingEnvironmentalVariables=[] SyncthingUseCustomHome=True SyncthingDenyUpgrade=False SyncthingRunLowPriority=False Folders=[] NotifyOfNewVersions=True LastNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingPath=%EXEPATH%\syncthing.exe SyncthingCustomHomePath=%EXEPATH%\data\syncthing ShowSynchronizedBalloonEvenIfNothingDownloaded=False> 
2015-08-12 10:38:34.2735 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Found existing configuration at C:\Users\d0\AppData\Roaming\SyncTrayzor\config.xml 
2015-08-12 10:38:34.3006 [Info] SyncTrayzor.Services.AutostartProvider: Have read/write access to the registry 
2015-08-12 10:38:35.1772 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: SyncThingProcessRunner.Start called 
2015-08-12 10:38:35.1952 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Starting 
2015-08-12 10:38:35.1952 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Stopped -> Starting 
2015-08-12 10:38:35.2062 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Starting syncthing: C:\Program Files\SyncTrayzor\syncthing.exe 
2015-08-12 10:38:35.2312 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Starting API clients 
2015-08-12 10:38:35.2612 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Attempting to request API using version 0.11.x API client 
2015-08-12 10:38:35.3333 [Warn] SyncTrayzor.Services.UpdateManagement.UpdateChecker: Fetching updates failed with an error System.Net.Http.HttpRequestException An error occurred while sending the request. Void ThrowForNonSuccess(System.Threading.Tasks.Task)    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__18.MoveNext() in c:\Documents\projects\RestEase\src\RestEase\Implementation\Requester.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestAsync>d__22`1.MoveNext() in c:\Documents\projects\RestEase\src\RestEase\Implementation\Requester.cs:line 305
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__0.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__0.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 82 System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Unable to connect to the remote server. ---> System.Net.Sockets.SocketException: The requested service provider could not be loaded or initialized
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.ServicePoint.GetConnection(PooledStream PooledStream, Object owner, Boolean async, IPAddress& address, Socket& abortSocket, Socket& abortSocket6)
   at System.Net.PooledStream.Activate(Object owningObject, Boolean async, GeneralAsyncDelegate asyncCallback)
   at System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__18.MoveNext() in c:\Documents\projects\RestEase\src\RestEase\Implementation\Requester.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestAsync>d__22`1.MoveNext() in c:\Documents\projects\RestEase\src\RestEase\Implementation\Requester.cs:line 305
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__0.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__0.MoveNext() in c:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 82
WebException The underlying connection was closed: Unable to connect to the remote server. System.Net.WebResponse EndGetResponse(System.IAsyncResult)
SocketException The requested service provider could not be loaded or initialized Void .ctor(System.Net.Sockets.AddressFamily, System.Net.Sockets.SocketType, System.Net.Sockets.ProtocolType)
2015-08-12 10:38:35.3543 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Failed to connect on attempt 0 
2015-08-12 10:38:35.6775 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:35 INFO: syncthing v0.11.9 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-14 11:52:00 UTC 
2015-08-12 10:38:35.6775 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status Error 
2015-08-12 10:38:35.6775 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:35 INFO: My ID: HCR4RWI 
2015-08-12 10:38:35.6895 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Starting -> Stopped 
2015-08-12 10:38:35.6895 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:35 INFO: No config file; starting with empty defaults 
2015-08-12 10:38:35.7096 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Starting -> Stopped 
2015-08-12 10:38:35.7096 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Aborting API clients 
2015-08-12 10:38:35.7096 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:35 FATAL: get free port (GUI): listen tcp 127.0.0.1:0: The requested service provider could not be loaded or initialized. 
2015-08-12 10:38:35.7226 [Info] SyncTrayzor.SyncThing.SyncThingManager: StartClientAsync aborted 
2015-08-12 10:38:42.7197 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: Kill all Syncthing processes 
2015-08-12 10:38:44.9371 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: SyncThingProcessRunner.Start called 
2015-08-12 10:38:44.9411 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Starting 
2015-08-12 10:38:44.9411 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Stopped -> Starting 
2015-08-12 10:38:44.9411 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Starting syncthing: C:\Program Files\SyncTrayzor\syncthing.exe 
2015-08-12 10:38:44.9561 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Starting API clients 
2015-08-12 10:38:44.9561 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Attempting to request API using version 0.11.x API client 
2015-08-12 10:38:44.9561 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Failed to connect on attempt 0 
2015-08-12 10:38:45.3333 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:45 INFO: syncthing v0.11.9 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-14 11:52:00 UTC 
2015-08-12 10:38:45.3333 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status Error 
2015-08-12 10:38:45.3333 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Starting -> Stopped 
2015-08-12 10:38:45.3333 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Starting -> Stopped 
2015-08-12 10:38:45.3333 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Aborting API clients 
2015-08-12 10:38:45.3333 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:45 INFO: My ID: HCR4RWI 
2015-08-12 10:38:45.3463 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:45 INFO: No config file; starting with empty defaults 
2015-08-12 10:38:45.3463 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:45 FATAL: get free port (GUI): listen tcp 127.0.0.1:0: The requested service provider could not be loaded or initialized. 
2015-08-12 10:38:45.3614 [Info] SyncTrayzor.SyncThing.SyncThingManager: StartClientAsync aborted 
2015-08-12 10:38:55.2908 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: Kill all Syncthing processes 
2015-08-12 10:38:56.2608 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: SyncThingProcessRunner.Start called 
2015-08-12 10:38:56.2688 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Starting 
2015-08-12 10:38:56.2688 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Stopped -> Starting 
2015-08-12 10:38:56.2688 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Starting syncthing: C:\Program Files\SyncTrayzor\syncthing.exe 
2015-08-12 10:38:56.2688 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Starting API clients 
2015-08-12 10:38:56.2688 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Attempting to request API using version 0.11.x API client 
2015-08-12 10:38:56.2838 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Failed to connect on attempt 0 
2015-08-12 10:38:56.6561 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:56 INFO: syncthing v0.11.9 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-14 11:52:00 UTC 
2015-08-12 10:38:56.6581 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status Error 
2015-08-12 10:38:56.6581 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Starting -> Stopped 
2015-08-12 10:38:56.6581 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:56 INFO: My ID: HCR4RWI 
2015-08-12 10:38:56.6581 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Starting -> Stopped 
2015-08-12 10:38:56.6581 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Aborting API clients 
2015-08-12 10:38:56.6581 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:56 INFO: No config file; starting with empty defaults 
2015-08-12 10:38:56.6741 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [HCR4R] 10:38:56 FATAL: get free port (GUI): listen tcp 127.0.0.1:0: The requested service provider could not be loaded or initialized. 
2015-08-12 10:38:56.6741 [Info] SyncTrayzor.SyncThing.SyncThingManager: StartClientAsync aborted 
2015-08-12 10:39:12.2544 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 115MB. Private Memory Size: 93MB. GC Total Memory: 8MB 
```

Syncthing.log:
```
SyncThingProcessRunner.Start called
Starting syncthing: C:\Program Files\SyncTrayzor\syncthing.exe
[HCR4R] 10:38:35 INFO: syncthing v0.11.9 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-14 11:52:00 UTC
Syncthing process stopped with exit status Error
[HCR4R] 10:38:35 INFO: My ID: HCR4RWI
[HCR4R] 10:38:35 INFO: No config file; starting with empty defaults
[HCR4R] 10:38:35 FATAL: get free port (GUI): listen tcp 127.0.0.1:0: The requested service provider could not be loaded or initialized.
Kill all Syncthing processes
SyncThingProcessRunner.Start called
Starting syncthing: C:\Program Files\SyncTrayzor\syncthing.exe
[HCR4R] 10:38:45 INFO: syncthing v0.11.9 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-14 11:52:00 UTC
Syncthing process stopped with exit status Error
[HCR4R] 10:38:45 INFO: My ID: HCR4RWI
[HCR4R] 10:38:45 INFO: No config file; starting with empty defaults
[HCR4R] 10:38:45 FATAL: get free port (GUI): listen tcp 127.0.0.1:0: The requested service provider could not be loaded or initialized.
Kill all Syncthing processes
SyncThingProcessRunner.Start called
Starting syncthing: C:\Program Files\SyncTrayzor\syncthing.exe
[HCR4R] 10:38:56 INFO: syncthing v0.11.9 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-06-14 11:52:00 UTC
Syncthing process stopped with exit status Error
[HCR4R] 10:38:56 INFO: My ID: HCR4RWI
[HCR4R] 10:38:56 INFO: No config file; starting with empty defaults
[HCR4R] 10:38:56 FATAL: get free port (GUI): listen tcp 127.0.0.1:0: The requested service provider could not be loaded or initialized.
```

Sorry to bother you, maybe I should just reformat my harddrive and make a fresh install of my OS..

**Comment by AudriusButkevicius** [comment]
Can you check your firewall and add exception for syncthing? It seems we can't connect to the network at all.

**Comment by canton7** [comment]
I note you're using version 1.0.22 of SyncTrayzor, which is a few months out of date (and there's been at least one mandatory update since then). Please upgrade!

I'm also very worried by the fact that random files from `C:\Program Files\SyncTrayzor` are going missing (you've said that `SyncTrayzor.exe.config` and `Syncthing.exe` have both gone missing), and it seems that Syncthing's configuration has disappeared as well (which is stored in `C:\Users\<You>\AppData\Local\Syncthing\config.xml`). This folder requires admin permissions to write to, and SyncTrayzor runs without admin permissions, so these files aren't being deleted by SyncTrayzor (and it would never delete them anyway). Either you've got an antivirus program that's out of control, or your hard drive's about to die, methinks :smile: 

It looks like Syncthing is failing because SyncTrayzor is telling it to start its gui on port 0, which it will only do if SyncTrayzor's configuration is corrupt in some way. Can you paste the contents of `C:\Users\<You>\AppData\Roaming\SyncTrayzor\config.xml`, censoring device IDs, etc, as appropriate?

Thanks.

**Comment by atoav** [comment]
Okay, the over-paranoid antivirus makes sense, because I had a malware problem recently (which is, why I considered just start fresh — I will probably do that).

But in case it helps:
```
<?xml version="1.0"?>
<Configuration xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="3">
  <ShowTrayIconOnlyOnClose>false</ShowTrayIconOnlyOnClose>
  <MinimizeToTray>false</MinimizeToTray>
  <CloseToTray>true</CloseToTray>
  <ShowSynchronizedBalloon>true</ShowSynchronizedBalloon>
  <ShowDeviceConnectivityBalloons>true</ShowDeviceConnectivityBalloons>
  <ShowSynchronizedBalloonEvenIfNothingDownloaded>false</ShowSynchronizedBalloonEvenIfNothingDownloaded>
  <SyncthingAddress>localhost:8384</SyncthingAddress>
  <StartSyncthingAutomatically>true</StartSyncthingAutomatically>
  <SyncthingApiKey>F8pkEZwtHM0uCBPi1aoZ6LeGAsAPpiPDKibknAxK</SyncthingApiKey>
  <SyncthingEnvironmentalVariables />
  <SyncthingUseCustomHome>true</SyncthingUseCustomHome>
  <SyncthingDenyUpgrade>false</SyncthingDenyUpgrade>
  <SyncthingRunLowPriority>false</SyncthingRunLowPriority>
  <Folders />
  <NotifyOfNewVersions>true</NotifyOfNewVersions>
  <ObfuscateDeviceIDs>true</ObfuscateDeviceIDs>
  <UseComputerCulture>true</UseComputerCulture>
  <SyncthingConsoleHeight>100</SyncthingConsoleHeight>
  <WindowPlacement>
    <IsMaximised>false</IsMaximised>
    <MinPosition>-1, -1</MinPosition>
    <MaxPosition>-1, -1</MaxPosition>
    <NormalPosition>410, 250, 1100, 700</NormalPosition>
  </WindowPlacement>
  <SyncthingWebBrowserZoomLevel>0</SyncthingWebBrowserZoomLevel>
  <LastSeenInstallCount>0</LastSeenInstallCount>
  <SyncthingPath>%EXEPATH%\syncthing.exe</SyncthingPath>
  <SyncthingCustomHomePath>%EXEPATH%\data\syncthing</SyncthingCustomHomePath>
</Configuration>
```

**Comment by canton7** [comment]
That's odd. That configuration was originally generated by a portable version of SyncTrayzor, and isn't really suitable for the installed version (which you appear to be running).

Did that configuration file really come from `C:\Users\<You>\AppData\Roaming\SyncTrayzor\config.xml`? How did it get there? Did you copy it there yourself? Did you install SyncTrayzor using the installer, or by downloading the portable .zip?

Anyway, that's fine on the GUI port front (assuming that SyncTrayzor really is reading that config file). Listen to @AudriusButkevicius's debugging skills on that front.

**Comment by SwederSchellens** [comment]
@canton7 I opened issue https://github.com/canton7/SyncTrayzor/issues/132

**Comment by atoav** [comment]
Don't bother to much, other stuff starts to break apart too. There must be stuff broken on many places. The system is cluttered and a fresh start won't hurt. Thanks for your incredibly fast help!

**Comment by canton7** [comment]
Are things working better after a re-install?

**Comment by atoav** [comment]
Everything is fine now. I really don't know what happened.

**Comment by canton7** [comment]
Righto. There are 2 issues here: the modification needed to `SyncTrayzor.exe.config`, and the subsequent moving / changing files. I'll keep this issue open until I've released a fix for the first, and quietly ignore the second and hope it never happens again...
