### ISSUE TITLE
Crash on Startup: A procedure imported by 'CefSharp.Core.dll' could not be loaded

### ISSUE THREAD

**Issue by peejaygee** [canton7/SyncTrayzor#137]
Error message on boot up, was fine yesterday after re-install of app (the error started two days ago, so uninstalled and re-installed) but it's returned today.

```
Version: 1.0.27.115; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileLoadException: A procedure imported by 'CefSharp.Core.dll' could not be loaded.
File name: 'CefSharp.Core.dll'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at StyletIoC.Creation.BuilderUpper.<>c__DisplayClass4.<GetExpression>b__0(FieldInfo x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at StyletIoC.Creation.BuilderUpper.GetExpression(Expression inputParameterExpression, ParameterExpression registrationContext, Type type)
   at StyletIoC.Internal.Creators.CreatorBase.CompleteExpressionFromCreator(Expression creator, ParameterExpression registrationContext)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at Stylet.Bootstrapper`1.get_RootViewModel()
   at SyncTrayzor.Bootstrapper.Configure() in c:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 125
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Hrm, this is a reappearance of #130. Would you mind following the same debugging steps as Aeyoun followed in that issue, re Dependency Walker?

**Comment by amaitland** [comment]
Operating system?

**Comment by peejaygee** [comment]
Windows 8.1

I'll do that dependency program shortly and dump my results. Just sitting at traffic lights heading to work. =)

**Comment by peejaygee** [comment]
Rather than Clog this thread, I dumped it to pastebin.

http://pastebin.com/RAkHHvpT

**Comment by canton7** [comment]
Thanks - I'll diff this against mine when I get some time - probably over the weekend.

**Comment by peejaygee** [comment]
Did you manage to look-see what might be causing it, I left my machine on over the weekend, as i find it stayed working, I was noticing that when I restated my laptop it breaks, so I had to uninstall and reinstall it.

**Comment by canton7** [comment]
I didn't see anything of interest.

Your comment is interesting though. So you can start/stop it multiple times and it works, but a reboot breaks it? Did you do the dependency walker test while it was in a broken, or a working state? Do you have any anti-virus or anti-malware programs installed?

**Comment by peejaygee** [comment]
What I'll do tonight, I'll run the dependency walker again, while it's working, and then reboot the machine, and (IF) when it crashes, run it again and get the 2nd log. For Comparison.

I currently have McAfee installed on my machine. I have another machine with SyncTrayzor installed with Comodo, with no issues, but I really don't want to uninstall McAfee just to test that.. :( (but I will, if I have too)

**Comment by canton7** [comment]
Sounds like a plan!

My thinking is: a reinstall of SyncTrayzor fixes it, so it's something constrained to SyncTrayzor's Program Files folder: that's the only place that the installer touches. That folder is protected: only something with admin permissions can modify it - that means that SyncTrayzor itself can't be causing this, as it doesn't have permission. Not sure why a reboot is the trigger - maybe whatever's doing the fiddling is registering a file removal to happen on reboot, as the file's in use at the time that the fiddler does its fiddling.

Antivirus is my gut feeling, but I'm not convinced by any means. It will be interesting to see whether any files go missing, or whether something' doing something really evil like intercepting assemblies...

**Comment by peejaygee** [comment]
So, turns out it wasn't the AV, after uninstalling my McAfee and installing, and restarting, same error... so I thought it is NOT beating me.. I remember buying 'StartUp Organizer' a while back, so I installed that, and while it was a little pain, it allowed me to turn off everything that was starting up, and slowly turn things back on, one by one, then restarting, etc, etc... while it was a laborious process, it turns out there was one file/program causing the issue.

HydraVisionDesktopManager

So, test this, I had everything in my startup running, except that.... SyncTrayzor run, no errors... run the HVDM, error.... end task.... SyncTrayzor run again with no issues..

So I looked into it, it appears it was part of the graphics card on my laptop, so I went to AMD's website, got the latest version of the graphics card drivers (never really needed to up, as I don't use my laptop for games, that much) and it would appear that after installing it, they chose to uninstall it, so it must have been giving issues. 

But I would not have thought that it was the graphics card software that was causing the error. It was very weird..

I'm just re-installing my AV software now, I can't see it causing any problems, but I'll report back if it does.

**Comment by canton7** [comment]
Whoa, thanks for digging into this in so much detail!

It's weird that this only became an issue after reboot - I wouldn't have expected a graphics driver issue to behave like that. Maybe HydraVision was trying to do some really evil stuff around controlling whether windows are visible or not by intercepting their attempts to draw? I can begin to imagine how that might work, and fail.

I wonder whether running SyncTrayzor with hardware rendering disabled might have fixed the issue (there's an option in the settings). Too late now, heh.

**Comment by canton7** [comment]
Closing, as it doesn't seem to have re-appeared.
