### ISSUE TITLE
Update to 1.0.28: "Not enough storage is available to process this command"

### ISSUE THREAD

**Issue by dsvf** [canton7/SyncTrayzor#149]
When the update prompt to 1.0.28 came, I accepted. I was connected via RDP at the time. I disconnected from the session. Later, when I reconnected, the following error message asked to be posted here as an issue (see below).
This may or may not be a SyncTrayzor issue, since other programs died in weird ways once I reconnected to the RDP session (-> "Not enough Storage").

Restarting SyncTrayzor produced another crash, but reported from Windows (not SyncTrayzor). Screenshot failed, so no copy of this error message.
After a second restart of SyncTrayzor, it works fine.

System: Windows 7 Professional 64-bit, with "enough" free RAM and HDD

```
Version: 1.0.28.141; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.Windows.Media.Animation.AnimationException: Cannot animate the 'IconSource' property on a 'Hardcodet.Wpf.TaskbarNotification.TaskbarIcon' using a 'System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames'. For details see the inner exception. ---> System.ComponentModel.Win32Exception: Not enough storage is available to process this command
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   at SyncTrayzor.NotifyIcon.NotifyIconResolutionUtilities.SetIconFromImageSource(TaskbarIcon taskbarIcon, ImageSource imageSource) in C:\projects\synctrayzor\src\SyncTrayzor\NotifyIcon\NotifyIconResolutionUtilities.cs:line 53
   at SyncTrayzor.NotifyIcon.NotifyIconResolutionUtilities.<>c.<.cctor>b__5_0(DependencyObject d, DependencyPropertyChangedEventArgs e) in C:\projects\synctrayzor\src\SyncTrayzor\NotifyIcon\NotifyIconResolutionUtilities.cs:line 33
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   at System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   at System.Windows.Media.Animation.TimeManager.Tick()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
The actual error bubbles up from Windows, as is `Not enough storage is available to process this command`. A bit of googling brings up some fairly sparse explanations ([one](http://blog.rongabriel.com/not-enough-storage-is-available-to-process-this-command/) [two](http://stackoverflow.com/questions/507853/system-error-code-8-not-enough-storage-is-available-to-process-this-command) [three](http://www.techfleece.com/2011/03/03/how-to-fix-not-enough-server-storage-is-available-to-process-this-command-error/) [four](http://stackoverflow.com/questions/507853/system-error-code-8-not-enough-storage-is-available-to-process-this-command/10560659#10560659) [five](https://support.microsoft.com/en-us/kb/285089)).

My working hypothesis is that SyncTrayzor got unlucky: it happened to be the application which tried to do something which ended up exceeding the IRC stack size, and got denied. Virtual every google result suggests changing the registry key `IRPStackSize`: if this happens again, maybe that's a possibility...

**Comment by dsvf** [comment]
I'll keep this in mind, should this error occur again (never did so far). That aside, I suppose you can close the issue, since it is not related to SyncTrayzor.

**Comment by canton7** [comment]
I think if this is related to SyncTrayzor, #151 will cover it, so I'll close this off.
