### ISSUE TITLE
Error "Cannot animate the 'IconSource' property"

### ISSUE THREAD

**Issue by dsvf** [canton7/SyncTrayzor#151]
The following error message occurred (see below).

As a side note, Firefox crashed a few seconds later, similar to https://github.com/canton7/SyncTrayzor/issues/149 (which was also from me). If these issues make no sense, they might point to underlying errors with my system (Hardware errors, maybe? None that I know of.)

```
Version: 1.0.28.141; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.Windows.Media.Animation.AnimationException: Cannot animate the 'IconSource' property on a 'Hardcodet.Wpf.TaskbarNotification.TaskbarIcon' using a 'System.Windows.Media.Animation.ObjectAnimationUsingKeyFrames'. For details see the inner exception. ---> System.ComponentModel.Win32Exception: The operation completed successfully
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   at SyncTrayzor.NotifyIcon.NotifyIconResolutionUtilities.SetIconFromImageSource(TaskbarIcon taskbarIcon, ImageSource imageSource) in C:\projects\synctrayzor\src\SyncTrayzor\NotifyIcon\NotifyIconResolutionUtilities.cs:line 53
   at SyncTrayzor.NotifyIcon.NotifyIconResolutionUtilities.<>c.<.cctor>b__5_0(DependencyObject d, DependencyPropertyChangedEventArgs e) in C:\projects\synctrayzor\src\SyncTrayzor\NotifyIcon\NotifyIconResolutionUtilities.cs:line 33
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Animation.AnimationStorage.OnCurrentTimeInvalidated(Object sender, EventArgs args)
   at System.Windows.Media.Animation.Clock.FireEvent(EventPrivateKey key)
   at System.Windows.Media.Animation.Clock.RaiseAccumulatedEvents()
   at System.Windows.Media.Animation.TimeManager.RaiseEnqueuedEvents()
   at System.Windows.Media.Animation.TimeManager.Tick()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
This seems to occur when no more handles are available, either because your process exceeded all 10,000 that are allowed for it, or because some process or other went haywire and stole them all.

The two things I would check are:
 1. Open Task Manager, Processes, go to View -> Select Columns and check `Handles`, `USER Objects` and `GDI Objects`. See if anything (SyncTrayzor included) is swallowing a large amount (more than, say, 5,000).
 2. Try the build which will appear here shortly: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.28.147/artifacts

**Comment by dsvf** [comment]
I was just about to post a follow-up with an identical error message when my PC crashed completely (BSOD), which occur practically never. So again, take my reports with a grain of salt.

GDI object count is tame, all below 300. I will try the new build.

Background Info: I just before the crashes, I added my music collection as a sync folder, which is noticeably larger than my other folders.

**Comment by canton7** [comment]
What was the BSOD? Which message?

**Comment by dsvf** [comment]
Well, the error did not occur again in the meantime, so something seems to be pacified.

BSOD error message:
    The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000003b (0x00000000c0000005, 0xfffff9600034ea13, 0xfffff88002525fe0, 0x0000000000000000). A dump was saved in: C:\Windows\MEMORY.DMP. Report Id: 100815-20108-01.

which seems to be a [System Service Exception](https://msdn.microsoft.com/en-us/library/windows/hardware/ff558949%28v=vs.85%29.aspx).

**Comment by canton7** [comment]
Some very odd indeed was going on.... 

I'm going to chalk this up to some random system problems which SyncTrayzor happened to get caught in the middle of. If it happens again, please re-open the issue!
