### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by drdozer** [canton7/SyncTrayzor#159]
```
Version: 1.0.28.141; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.IOException: The process cannot access the file 'C:\Users\caroline\AppData\Roaming\SyncTrayzor\config.xml.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at SyncTrayzor.Utils.AtomicFileStream..ctor(String path, String tempPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in C:\projects\synctrayzor\src\SyncTrayzor\Utils\AtomicFileStream.cs:line 87
   at SyncTrayzor.Utils.AtomicFileStream.Open(String path, String tempPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in C:\projects\synctrayzor\src\SyncTrayzor\Utils\AtomicFileStream.cs:line 76
   at SyncTrayzor.Services.FilesystemProvider.OpenAtomic(String path, FileMode mode) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 32
   at SyncTrayzor.Services.Config.ConfigurationProvider.SaveToFile(Configuration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 295
   at SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 166
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 84
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 94
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by canton7** [comment]
When we start up, we create the file `C:\Users\caroline\AppData\Roaming\SyncTrayzor\config.xml.tmp`, then try and open it for writing. Between us creating it and trying to open it, something else on your computer has grabbed it and opened.

This might be a virus scanner, or something similar.

Is this problem repeatable: if you try and start SyncTrayzor many times, does it fail in the same way each time? Do you have anti-virus, anti-malware, or some sort of synchronization software running which might have grabbed the file?

**Comment by chucic** [comment]
This just happened to me, on portable version 1.0.29. Second time I started SyncTrayzor it was fine. Just to confirm that this is still happening, although pretty rarely.

**Comment by canton7** [comment]
No one has yet answered all of the questions I asked, so I've got very little to go on.

**Comment by chucic** [comment]
Right.
Repeatable: No. Only happened once, before and after that STZ worked fine. Even when this error was shown, STZ and ST seems to be working fine (I mean I didn't kill it or stop it and it connected to others and was syncing etc, only I had that error window shown).
Antivirus: Yes, I have Eset Nod32, which might have grab the file.

So this is basically expected behaviour, I posted about it just because I remembered there was issue about it some time ago and to let you know that this will probably affect every user once or twice in given period of time.

Let me know what I can do to help with this (if possible), e.g. what to do next time I encounter this again.

**Comment by canton7** [comment]
Aha, so you're running a slightly obscure AV: so the AV theory is the most likely explanation.

It's odd that SyncTrayzor continued to function: I'll look into this. It should have died.

Now that I know what the probable cause is, I've got an approach in mind which should sort it. Stay tuned!

**Comment by simplypeachy** [comment]
For what it's worth, I run Eset and Synctrazyor on about a dozen systems (and Eset on several hundred) and haven't seen this fault once. I also have Eset in a non-standard configuration, set to be more zealous than default. Just a heads up in case it's a red herring :-)

**Comment by canton7** [comment]
Cool, thanks for letting me know.

I've got what should be a fix in place, anyway. If people still report this is a problem once I've release that, then I'll get very confused and start racking my brains...
