### ISSUE TITLE
v0.12 apparently spams the log with event parse failure messages

### ISSUE THREAD

**Issue by canton7** [canton7/SyncTrayzor#163]
```
"2015-10-22 12:48:36.3350 [Error] SyncTrayzor.SyncThing.SyncThingPoller: Unexpected exception while polling System.ArgumentException Could not convert 'RelayStateChanged' to EventType."
```

**Comment by alex2108** [comment]
Whole log message:
```
2015-10-22 14:27:11.7033 [Error] SyncTrayzor.SyncThing.SyncThingPoller: Unexpected exception while polling System.ArgumentException Could not convert 'RelayStateChanged' to EventType. System.Object ToObject(System.Type)    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at SyncTrayzor.SyncThing.ApiClient.EventConverter.Create(Type objectType, JObject jObject) in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\ApiClient\EventConverter.cs:line 27
   at SyncTrayzor.SyncThing.ApiClient.JsonCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\ApiClient\JsonCreationConverter.cs:line 43
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at RestEase.Implementation.Requester.<RequestAsync>d__22`1.MoveNext() in c:\Documents\projects\RestEase\src\RestEase\Implementation\Requester.cs:line 307
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher.<PollAsync>d__35.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\EventWatcher\SyncThingEventWatcher.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingPoller.<>c__DisplayClass10_0.<<StartInternal>b__0>d.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingPoller.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingPoller.<DoWithErrorHandlingAsync>d__11.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingPoller.cs:line 108 System.ArgumentException: Could not convert 'RelayStateChanged' to EventType. ---> System.ArgumentException: Requested value 'RelayStateChanged' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at SyncTrayzor.SyncThing.ApiClient.EventConverter.Create(Type objectType, JObject jObject) in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\ApiClient\EventConverter.cs:line 27
   at SyncTrayzor.SyncThing.ApiClient.JsonCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\ApiClient\JsonCreationConverter.cs:line 43
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at RestEase.Implementation.Requester.<RequestAsync>d__22`1.MoveNext() in c:\Documents\projects\RestEase\src\RestEase\Implementation\Requester.cs:line 307
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SyncTrayzor.SyncThing.EventWatcher.SyncThingEventWatcher.<PollAsync>d__35.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\EventWatcher\SyncThingEventWatcher.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingPoller.<>c__DisplayClass10_0.<<StartInternal>b__0>d.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingPoller.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingPoller.<DoWithErrorHandlingAsync>d__11.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingPoller.cs:line 108
ArgumentException Requested value 'RelayStateChanged' was not found. Boolean TryParseEnum(System.Type, System.String, Boolean, EnumResult ByRef)
```

**Comment by canton7** [comment]
You can download a build which doesn't spam these messages from: https://ci.appveyor.com/project/canton7/synctrayzor/build/1.0.28.150/artifacts
