### ISSUE TITLE
SyncTrayzor unable to access temporary config file (AV issue?)

### ISSUE THREAD

**Issue by chrisveness** [canton7/SyncTrayzor#166]
Version: 1.0.28.141; Variant: Installed; Arch: Amd64
```
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.IOException: The process cannot access the file 'C:\Users\[user]\AppData\Roaming\SyncTrayzor\config.xml.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at SyncTrayzor.Utils.AtomicFileStream..ctor(String path, String tempPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in C:\projects\synctrayzor\src\SyncTrayzor\Utils\AtomicFileStream.cs:line 87
   at SyncTrayzor.Utils.AtomicFileStream.Open(String path, String tempPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in C:\projects\synctrayzor\src\SyncTrayzor\Utils\AtomicFileStream.cs:line 76
   at SyncTrayzor.Services.FilesystemProvider.OpenAtomic(String path, FileMode mode) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 32
   at SyncTrayzor.Services.Config.ConfigurationProvider.SaveToFile(Configuration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 295
   at SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 166
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 84
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 94
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Dup of #159. 



When we start up, we create the file C:\Users\caroline\AppData\Roaming\SyncTrayzor\config.xml.tmp, then try and open it for writing. Between us creating it and trying to open it, something else on your computer has grabbed it and opened.

This might be a virus scanner, or something similar.

Is this problem repeatable: if you try and start SyncTrayzor many times, does it fail in the same way each time? Do you have anti-virus, anti-malware, or some sort of synchronization software running which might have grabbed the file?
