### ISSUE TITLE
v1.0.30 crashing immediately

### ISSUE THREAD

**Issue by berrnd** [canton7/SyncTrayzor#178]
Just upgraded to 1.0.30 and got this:

![22-11-_2015_18-37-01](https://cloud.githubusercontent.com/assets/2161815/11325352/eea74218-914b-11e5-8e80-04247a152f29.png)

```
Version: 1.0.30.169; Variant: Portable; Arch: Amd64
Path: C:\LocalApps\SyncTrayzor\SyncTrayzor.exe
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\LocalApps\SyncTrayzor\logs\logs archive'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at SyncTrayzor.Services.Config.ConfigFolderCleaner.Clean() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigFolderCleaner.cs:line 58
   at SyncTrayzor.Bootstrapper.OnLaunch() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 177
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Manually creating `\logs\logs archive` worked...

**Comment by canton7** [comment]
Ah bollocks. Thanks. Fix incoming...

**Comment by canton7** [comment]
Oops, didn't mean to close this yet.

New release is building...

**Comment by canton7** [comment]
Righty, v1.0.31 is out
