### ISSUE TITLE
SyncTrayzor Crash error report

### ISSUE THREAD

**Issue by stephenjudge** [canton7/SyncTrayzor#181]
```
Version: 1.0.31.172; Variant: Portable; Arch: Amd64
Path: C:\PortableApps\PortableApps\SyncTrayzorPortable-x64\SyncTrayzor.exe
System.InvalidOperationException: There was an error generating the XML document. ---> System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at System.Xml.XmlTextWriter.WriteStartElement(String prefix, String localName, String ns)
   at System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(String localName, String ns, String value, XmlQualifiedName xsiType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterConfiguration.Write3_FolderConfiguration(String n, String ns, FolderConfiguration o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterConfiguration.Write4_Configuration(String n, String ns, Configuration o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterConfiguration.Write5_Configuration(Object o)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
   at System.Xml.Serialization.XmlSerializer.Serialize(Stream stream, Object o, XmlSerializerNamespaces namespaces)
   at SyncTrayzor.Services.Config.ConfigurationProvider.SaveToFile(Configuration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 312
   at SyncTrayzor.Services.Config.ConfigurationProvider.Save(Configuration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 289
   at SyncTrayzor.Services.ConfigurationApplicator.LoadFolders() in C:\projects\synctrayzor\src\SyncTrayzor\Services\ConfigurationApplicator.cs:line 98
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Is this something that is repeatable, or has it just happened the once?

**Comment by canton7** [comment]
Ah never mind, I know what this is....

**Comment by canton7** [comment]
Until this is released, you can pick up a fixed build here: https://ci.appveyor.com/project/canton7/synctrayzor/build/artifacts
