### ISSUE TITLE
System.IO.FileLoadException: A procedure imported by 'CefSharp.Core.dll' could not be loaded.

### ISSUE THREAD

**Issue by tkafka** [canton7/SyncTrayzor#183]
Yesterday SyncTrayzor (v1.0.32) worked OK, so I set it to start at startup. Today after restart of computer, every start of SyncTrayzor ends with this. I redownloaded portable version and unpacked it, but with same result (this rules out data corruption). Also, I suspected that this could happen if a program is started from other folder by windows, but same thing happens when I run it from it's directory.

Any idea how to solve this?

Here is SyncTrayzor.log: https://gist.github.com/anonymous/35cf0c8e075fbda47c98

```
Version: 1.0.32.183; Variant: Portable; Arch: Amd64
Path: D:\Programs\SyncTrayzorPortable-x64\SyncTrayzor.exe
System.IO.FileLoadException: A procedure imported by 'CefSharp.Core.dll' could not be loaded.
File name: 'CefSharp.Core.dll'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at StyletIoC.Creation.BuilderUpper.<>c__DisplayClass4.<GetExpression>b__0(FieldInfo x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at StyletIoC.Creation.BuilderUpper.GetExpression(Expression inputParameterExpression, ParameterExpression registrationContext, Type type)
   at StyletIoC.Internal.Creators.CreatorBase.CompleteExpressionFromCreator(Expression creator, ParameterExpression registrationContext)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext)
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable)
   at Stylet.Bootstrapper`1.get_RootViewModel()
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 120
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Looks similar to #130 and #137. Have you installed any new software recently? Anything else that happened to your computer, even if you think it might be completely irrelevant?

**Comment by canton7** [comment]
Hi, any response?

**Comment by canton7** [comment]
Closing due to no response. Please re-open if you re-appear.
