### ISSUE TITLE
Oops in SyncTrazor

### ISSUE THREAD

**Issue by shlomiag** [canton7/SyncTrayzor#185]
[SyncTrayzor.zip](https://github.com/canton7/SyncTrayzor/files/71796/SyncTrayzor.zip)

Hi,

I'd like to report the following:

```
Version: 1.0.32.183; Variant: Installed; Arch: Amd64
Path: E:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.IOException: The process cannot access the file 'E:\Users\Sandra\AppData\Roaming\SyncTrayzor\config.xml.tmp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at SyncTrayzor.Utils.AtomicFileStream..ctor(String path, String tempPath) in C:\projects\synctrayzor\src\SyncTrayzor\Utils\AtomicFileStream.cs:line 22
   at SyncTrayzor.Services.FilesystemProvider.CreateAtomic(String path) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 37
   at SyncTrayzor.Services.Config.ConfigurationProvider.SaveToFile(Configuration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 310
   at SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 167
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 85
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 94
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Is this repeatable? As in, does it happen every time you start SyncTrayzor? Or did you just see it the once?

**Comment by shlomiag** [comment]
Hi Antony,

I haven't seen SyncTrayzor crash before, or at least not in a manner similar to this. I turned on SyncTrayzor, got back to my computer after a while, and got this error reporting window. Might it have something to do with the recent update I installed to the SyncTrayzor client?

Shlomi

**Comment by canton7** [comment]
As in, can you start it now, without it crashing again?

**Comment by shlomiag** [comment]
Well, apart from that one-time crash it seems to be working fine.

Shlomi

**Comment by canton7** [comment]
Are you running any anti-virus / anti-malware? Is `E:\` a networked drive of some sort?

**Comment by shlomiag** [comment]
Microsoft Security Essentials, and Spy Bot's background service.

No, E: is (unconventionally) the label of the OS partition on my multi-partition system. No network drives.

**Comment by canton7** [comment]
Oh! I've just spotted something else in the log.

It looks like, somehow, two SyncTrayzor instances were started at exactly the same instant. Normally we handle two running processor by having the second process ask the first one to show its main window, and then exiting, but this doesn't work if they're both started exactly together. They then tried to write to the config file at exactly the same time, and one of them lost.

I'm somewhat confused as to how this could have happened. How was SyncTrayzor started? Just automatically, when Windows starts? If so, can you have a look at in the registry under `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`, and see what entries for SyncTrayzor there are (since everything works now it's quite possible that any problems here have been fixed automatically). Anything else you can think of that might have caused two instances to be started exactly together?

**Comment by canton7** [comment]
... even if we never expect two instances of Syncthing to be running at once with the same config directory, we should still be robust to it (instead of crashing). I'm not sure of the best way to do this: I don't think it makes sense to let those two instances run side-by-side: they won't be able to both run Syncthing anyway since *that* doesn't let two instances run at the same time with the same config. It might be best to just show a dialog explaining the situation, then exit.

**Comment by shlomiag** [comment]
The registry key you specified does not contain any information related to
SyncTrazor or syncthing.

I think that I have a simple explanation to what puzzles you. There are two
users on my Windows 7 machine. When I first installed SyncTrazor on this
machine, it placed itself to start automatically on login of either of
these two users. One of these users actually uses syncthing, while with the
other I couldn't be bothered, so I neither bothered to configure it nor
tried to remove it from starting automatically on login. When one of the
two users is logged in, SyncTrazor indeed displays an error message right
after the other logs in, saying that only one instance of syncthing is
allowed. But since I couldn't be bothered, I wasn't troubled by this error
message recurring.

My guess is that this oops occurred since I took the computer out of
hibernation/sleep while both users were logged on. Or maybe something
similar to this.

What do you think Anton?

**Comment by canton7** [comment]
That half-explains it. Both instances of SyncTrayzor were started as the user `Sandra` - that is, both were trying to access `E:\Users\Sandra\AppData\Roaming\SyncTrayzor\config.xml`. Does that make sense to you?

**Comment by shlomiag** [comment]
That's incorrect. I just tried logging on both users, one after the other.
SyncTrazor starts one (separate) instance under each of the two users (as
per Windows Task Manager).

**Comment by canton7** [comment]
That's expected, and it's fine as both instances will use different configuration directories, allowing Syncthing to (potentially) start twice.

In this specific case, SyncTrayzor was started twice as the *same* user. That's what I'm trying to understand.

**Comment by canton7** [comment]
Hi, any idea how SyncTrayzor was started twice as the same user?

**Comment by shlomiag** [comment]
No, not really. It happened right after log on, so maybe it was a Windows task scheduler event triggered by the log on.
