### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by Xalaxis** [canton7/SyncTrayzor#210]
```
Version: 1.1.3.283; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.ArgumentException: Value does not fall within the expected range.
   at NETWORKLIST.NetworkListManagerClass.GetCost(UInt32& pCost, NLM_SOCKADDR& pDestIPAddr)
   at SyncTrayzor.Services.Metering.NetworkCostManager.IsConnectionMetered(IPAddress address) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\NetworkCostManager.cs:line 70
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<UpdateDeviceAsync>d__34.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 255
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<Update>d__33.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 235
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

[SyncTrayzor.txt](https://github.com/canton7/SyncTrayzor/files/104845/SyncTrayzor.txt)

**Comment by canton7** [comment]
Ah, I wonder what's going on here.

Short-term fix: edit `C:\Users\<You>\AppData\Roaming\SyncTrayzor\config.xml`, and change `<PauseDevicesOnMeteredNetworks>true</PauseDevicesOnMeteredNetworks>` to <PauseDevicesOnMeteredNetworks>false</PauseDevicesOnMeteredNetworks>` (you'd normally be able to do this in the GUI, but presumably you can't start that...).

I'll add some more logging, see what exactly is going on.

**Comment by Jelmerro** [comment]
Downgrading back to 1.1.2 will keep everything working as before, nothing got corrupted

**Comment by canton7** [comment]
Got it. There will be a build here in about 10 minutes which should fix it. Mind trying it?

https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.3.284/artifacts

**Comment by Xalaxis** [comment]
Will have a go shortly

**Comment by canton7** [comment]
Right! That's finally built.

**Comment by canton7** [comment]
Right, I'm suppressing this in v1.1.4, but I don't know what the root cause is (other than that I'm asking the Windows API in charge of metered connections slightly the wrong question).

Once you've upgraded and SyncTrayzor has started, would you mind looking through your log for the line containing "GetCost failed" and pasting it there? Thanks!

You'll find your log in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs\SyncTrayzor.log`

**Comment by Xalaxis** [comment]
2016-01-26 15:33:36.1818 #10136 [Error] SyncTrayzor.Services.Metering.NetworkCostManager: GetCost failed. IP: 192.168.2.5, Bytes: 02-00-00-00-00-00-00-00-C0-A8-02-05-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 System.ArgumentException Value does not fall within the expected range. Void GetCost(UInt32 ByRef, NETWORKLIST.NLM_SOCKADDR ByRef)    at NETWORKLIST.NetworkListManagerClass.GetCost(UInt32& pCost, NLM_SOCKADDR& pDestIPAddr)
   at SyncTrayzor.Services.Metering.NetworkCostManager.IsConnectionMetered(IPAddress address) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\NetworkCostManager.cs:line 71 System.ArgumentException: Value does not fall within the expected range.
   at NETWORKLIST.NetworkListManagerClass.GetCost(UInt32& pCost, NLM_SOCKADDR& pDestIPAddr)
   at SyncTrayzor.Services.Metering.NetworkCostManager.IsConnectionMetered(IPAddress address) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\NetworkCostManager.cs:line 71

Hopefully that's of help?  As expected you've fixed the crash - Good job :grin:

**Comment by canton7** [comment]
Perfect thanks! That's enough for me to work with.
