### ISSUE TITLE
Issue after latest update to SyncTrazor

### ISSUE THREAD

**Issue by mrbrahma** [canton7/SyncTrayzor#213]
May be a duplicate...

This is seen after an update a few mins back.

```
Version: 1.1.3.283; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
File name: 'CefSharp.Core.dll'
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__1f(ScreenState oldState, ScreenState newState) in c:\projects\stylet\Stylet\Screen.cs:line 155
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 141
   at Stylet.ScreenExtensions.<>c__DisplayClass1.<ActivateWith>b__0(Object o, ActivationEventArgs e) in c:\projects\stylet\Stylet\ScreenExtensions.cs:line 68
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 141
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel) in c:\projects\stylet\Stylet\WindowManager.cs:line 220
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog) in c:\projects\stylet\Stylet\WindowManager.cs:line 194
   at Stylet.WindowManager.ShowWindow(Object viewModel) in c:\projects\stylet\Stylet\WindowManager.cs:line 90
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 87
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Yep, dup of #211. Looking into it.

**Comment by canton7** [comment]
A damnit, I know what this is. The embedded browser changed the dependencies it needs....

**Comment by canton7** [comment]
Got it. There will be a build here in about 10 minutes which should fix it. Mind trying it?

https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.3.284/artifacts

**Comment by canton7** [comment]
Right, that's finally built.

If you can try the build and confirm whether or not that fixes the issue, I'd appreciate it. If you confirm that it does fix the issue, I'll make a release straight away.

**Comment by mrbrahma** [comment]
Yup, issue is now gone! Thanks.

**Comment by canton7** [comment]
Fantastic, I'll push out a release.

Thanks for checking.
