### ISSUE TITLE
Crashes upon syncing after upgrade

### ISSUE THREAD

**Issue by LiamMarcus** [canton7/SyncTrayzor#216]
Manually upgraded to 1.1.4 after problems with automatic upgrade this morning.  Issue still happening.  Program starts fine.  When sync starts, it crases with the following (Win 10, 64 bit)

```
Version: 1.1.4.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at NETWORKLIST.NetworkListManagerClass.GetCost(UInt32& pCost, NLM_SOCKADDR& pDestIPAddr)
   at SyncTrayzor.Services.Metering.NetworkCostManager.IsConnectionMetered(IPAddress address) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\NetworkCostManager.cs:line 71
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<UpdateDeviceAsync>d__34.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 255
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<DeviceConnected>d__24.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Righty, you're seeing the same as #215.

**Comment by canton7** [comment]
For now, you can disable "Pause devices which connect over a metered network" in the settings.

**Comment by LiamMarcus** [comment]
That stopped resolved the crashing and it is back to syncing.
