### ISSUE TITLE
"Something went badly wrong" updating to 1.1.5

### ISSUE THREAD

**Issue by TimeLordmbw** [canton7/SyncTrayzor#220]
After attempting to update to 1.1.5, SyncTrayzor will no longer open (Windows 8.1; reboot did not help). I think I have the latest version of Syncthing, but I can't get in to verify.

The error message I get says to include the following:

Version: 1.1.3.283; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.BadImageFormatException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
File name: 'CefSharp.Core.dll'
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__1f(ScreenState oldState, ScreenState newState) in c:\projects\stylet\Stylet\Screen.cs:line 155
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 141
   at Stylet.ScreenExtensions.<>c__DisplayClass1.<ActivateWith>b__0(Object o, ActivationEventArgs e) in c:\projects\stylet\Stylet\ScreenExtensions.cs:line 68
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 141
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel) in c:\projects\stylet\Stylet\WindowManager.cs:line 220
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog) in c:\projects\stylet\Stylet\WindowManager.cs:line 194
   at Stylet.WindowManager.ShowWindow(Object viewModel) in c:\projects\stylet\Stylet\WindowManager.cs:line 90
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 87
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by simplypeachy** [comment]
0x800700C1 is "ERROR_BAD_EXE_FORMAT" so I assume CefSharp.Core.dll is broken in some way. Try re-installing SyncTrayzor to see if it helps.

**Comment by TimeLordmbw** [comment]
Yup. Reinstall took care of it.  Thanks!

**Comment by canton7** [comment]
Weird. I check the integrity of all updates before auto-installing, so either the installer corrupted the file while writing it (but it's a popular and trusted installer framework, which makes this seem unlikely) or something managed to corrupt that file between it being written and SyncTrayzor starting for the first time (antivirus?).

**Comment by canton7** [comment]
Thanks for looking into this @TimeLordmbw!

I'm going to close this off: I don't think it's anything I could have prevented. If anyone can find a way to repeat this, please reopen.
