### ISSUE TITLE
Crash after changing to staggered versioning

### ISSUE THREAD

**Issue by davidlmontgomery** [canton7/SyncTrayzor#234]
Just getting set up with Syncthing, SyncTrayzor. Was in the middle of a long initial sync. Happened across the option to change versioning to staggered (from none). Changed on the two "clients" (the two boxes receiving all the files initially, although of course now they are sharing with each other) without problem. Changed it on the box sharing the files. All prompted for restarts after change. On the box with error, after pressing restart, SyncTrayzor crashed. I started SyncTrayzor manually. It came up saying syncthing had stopped. I started it. Log (and ongoing synching with other two boxes) indicated previous syncthing instance was still running. I followed suggestion, using menu option to kill all syncthing processes. (In retrospect, I wonder if the suggestion shouldn't be to bring up the default syncthing web interface in a browser, and try to shut it down properly, especially given the warning about possible database corruption.) Then I clicked to start syncthing, and got the error:

Version: 1.1.7.0; Variant: Installed; Arch: X86
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadStartupDataAsync>d__130.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 467
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartClientAsync>d__124.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartAsync>d__114.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 189
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ViewerViewModel.<Start>d__39.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\ViewerViewModel.cs:line 262
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
It's the same as #231.

Syncthing's returning a bad response, but i'm not yet sure what could be causing it. Pretty sure it's not related to the file versioning stuff. I think it's something racy in Syncthing, which means it should work if you try again.

**Comment by davidlmontgomery** [comment]
Indeed, after I posted the crash, I restarted, and everything appears to be working fine.

**Comment by canton7** [comment]
Closing in favour of #231.
