### ISSUE TITLE
Error creating the Web Proxy specified

### ISSUE THREAD

**Issue by ml7Dom** [canton7/SyncTrayzor#239]
```
ERROR DETAILS
	Following errors were detected during this operation.
	* [3/4/2016 12:38:55 PM] System.Configuration.ConfigurationErrorsException
		- Error creating the Web Proxy specified in the 'system.net/defaultProxy' configuration section.
		- Source: System
		- Stack trace:
			at System.Net.Configuration.DefaultProxySectionInternal.GetSection()
			at System.Net.WebRequest.get_InternalDefaultWebProxy()
			at System.Net.HttpWebRequest..ctor(Uri uri, ServicePoint servicePoint)
			at System.Net.HttpRequestCreator.Create(Uri Uri)
			at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.Sockets.SocketException
		- A system call has failed
		- Source: System
		- Stack trace:
			at System.Net.SafeCloseSocketAndEvent.CreateWSASocketWithEvent(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType, Boolean autoReset, Boolean signaled)
			at System.Net.NetworkAddressChangePolled..ctor()
			at System.Net.AutoWebProxyScriptEngine.AutoDetector.Initialize()
			at System.Net.AutoWebProxyScriptEngine.AutoDetector.get_CurrentAutoDetector()
			at System.Net.AutoWebProxyScriptEngine..ctor(WebProxy proxy, Boolean useRegistry)
			at System.Net.WebProxy.UnsafeUpdateFromRegistry()
			at System.Net.Configuration.DefaultProxySectionInternal..ctor(DefaultProxySection section)
			at System.Net.Configuration.DefaultProxySectionInternal.GetSection()

```

**Comment by canton7** [comment]
Looks like a fun interaction between .NET and something else, which according to Google could be down to a myriad if things... I've seen this before with SyncTrayzor and there's a bit of config in place to work around it, but apparently that doesn't work for you... 

1. Are you running SyncTrayzor from a network drive? Try running it from a local drive, see if that makes any difference. 
2. Ant anti-malware / antivirus / overactive firewalls getting in the way? 
3. Try running `netsh winsock reset` from an administrator command prompt and restart.

**Comment by ml7Dom** [comment]
@canton7 thanks, I made the third option and it worked #

**Comment by canton7** [comment]
Cool! Thanks for confirming. I'll remember that one...
