### ISSUE TITLE
Occasional Crash during startup

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#243]
I've been adding new Windows 10 machine to the cluster, and occasionally SyncTrayzor would crash during startup with the following message:
```
Version: 1.1.7.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadStartupDataAsync>d__130.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 467
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartClientAsync>d__124.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 361
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartAsync>d__114.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 189
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__39.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Duplicate of #231.

Good to see that it's still around though - I'll get that new release (with the required logging) out soon....

**Comment by scienmind** [comment]
Oh, ok then, I'll close this one
