### ISSUE TITLE
Crash: An unhandled AppDomain exception

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#258]
The crash was kinda random, and seem not exactly fitting in other issues. But maybe it'll still be helpful for other Bootstrapper related things...
I'm not sure what caused it, the only "unusual thing that was going on during the crash is that it occurred on the non-portable installation (v.1.1.9) during the startup of the portable installation on the same machine. 

```
2016-05-04 10:32:53.5957 #50392 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
2016-05-04 10:33:00.3678 #50392 [Debug] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 149MiB. Private Memory Size: 133MiB. GC Total Memory: 9MiB 
2016-05-04 10:33:10.2228 #50392 [Error] SyncTrayzor.Bootstrapper: An unhandled AppDomain exception occurred. Terminating: True System.Threading.Tasks.TaskCanceledException A task was canceled. Void ThrowForNonSuccess(System.Threading.Tasks.Task)    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__18.MoveNext() in c:\projects\restease\src\RestEase\Implementation\Requester.cs:line 283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestVoidAsync>d__1f.MoveNext() in c:\projects\restease\src\RestEase\Implementation\Requester.cs:line 312
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<PauseDeviceAsync>d__28.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Devices\SyncthingDeviceManager.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<UpdateDeviceAsync>d__33.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<Update>d__32.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__18.MoveNext() in c:\projects\restease\src\RestEase\Implementation\Requester.cs:line 283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestVoidAsync>d__1f.MoveNext() in c:\projects\restease\src\RestEase\Implementation\Requester.cs:line 312
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<PauseDeviceAsync>d__28.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Devices\SyncthingDeviceManager.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<UpdateDeviceAsync>d__33.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 311
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<Update>d__32.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2016-05-04 10:33:10.6941 #50392 [Debug] SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient: Fetched updates response: <UpdateNotificationResponse data= error=> 
2016-05-04 10:33:10.6941 #50392 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
2016-05-04 10:33:10.6941 #50392 [Error] SyncTrayzor.Bootstrapper: An unhandled AppDomain exception occurred. Terminating: True System.Threading.Tasks.TaskCanceledException A task was canceled. Void ThrowForNonSuccess(System.Threading.Tasks.Task)    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__18.MoveNext() in c:\projects\restease\src\RestEase\Implementation\Requester.cs:line 283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestVoidAsync>d__1f.MoveNext() in c:\projects\restease\src\RestEase\Implementation\Requester.cs:line 312
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<ResumeDeviceAsync>d__29.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Devices\SyncthingDeviceManager.cs:line 155
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<UpdateDeviceAsync>d__33.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 322
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<Update>d__32.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__18.MoveNext() in c:\projects\restease\src\RestEase\Implementation\Requester.cs:line 283
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestVoidAsync>d__1f.MoveNext() in c:\projects\restease\src\RestEase\Implementation\Requester.cs:line 312
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<ResumeDeviceAsync>d__29.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Devices\SyncthingDeviceManager.cs:line 155
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<UpdateDeviceAsync>d__33.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 322
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<Update>d__32.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 274
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2016-05-04 10:34:21.9473 #50392 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [IDIDID] 10:33:24 INFO: Restarting 
2016-05-04 10:34:21.9623 #50392 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [IDIDID] 10:33:24 OK: Exiting 
2016-05-04 10:34:21.9623 #50392 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing process stopped with exit status Restarting 
2016-05-04 10:34:21.9623 #50392 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing process requested restart, so restarting 
2016-05-04 10:34:21.9623 #50392 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Request to set state: Running -> Restarting 
2016-05-04 10:34:21.9623 #50392 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Setting state: Running -> Restarting 
2016-05-04 10:34:21.9623 #50392 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Aborting API clients 
2016-05-04 10:34:21.9623 #50392 [Info] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options 
2016-05-04 10:34:21.9623 #50392 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: SyncthingProcessRunner.Start called 
2016-05-04 10:34:21.9763 #50392 [Debug] SyncTrayzor.Syncthing.FreePortFinder: Found free port: PORT 
2016-05-04 10:34:21.9763 #50392 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Request to set state: Restarting -> Starting 
2016-05-04 10:34:21.9763 #50392 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Setting state: Restarting -> Starting 
2016-05-04 10:34:21.9763 #50392 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Starting API clients 
```

**Comment by canton7** [comment]
This is the same as #252

**Comment by scienmind** [comment]
Oh... 
I should've taken profiler's info..
