### ISSUE TITLE
Old version of SyncTrayzor does not work with Syncthing 0.13

### ISSUE THREAD

**Issue by bshafer** [canton7/SyncTrayzor#261]
I think my problem was that I had an old version of SyncTrayzor, and then I clicked on the "Upgrade to 0.13.1" button.

```
Version: 1.1.1.231; Variant: Installed; Arch: X86
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyncTrayzor.SyncThing.FolderIgnores..ctor(List`1 ignores, List`1 patterns) in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\Folder.cs:line 25
   at SyncTrayzor.SyncThing.SyncThingFolderManager.<>c__DisplayClass29_0.<<FetchFoldersAsync>b__2>d.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingFolderManager.cs:line 175
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingFolderManager.<FetchFoldersAsync>d__29.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingFolderManager.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingFolderManager.<LoadFoldersAsync>d__27.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingFolderManager.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<LoadConfigDataAsync>d__138.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 518
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<LoadStartupDataAsync>d__137.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 483
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__131.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 379
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__119.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 203
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__39.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

[SyncTrayzor.zip](https://github.com/canton7/SyncTrayzor/files/270948/SyncTrayzor.zip)

**Comment by canton7** [comment]
You're running a very old version, from January. 

Support for Syncthing 0.13 was added in version 1.1.9, over 2 weeks ago.

**Comment by canton7** [comment]
(This has nothing to do with database corruption).
