### ISSUE TITLE
crash upon restore after minimizing to tray

### ISSUE THREAD

**Issue by xamindar** [canton7/SyncTrayzor#266]
Version: 1.1.9.356; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.Exception: IBrowser instance is null. Browser has likely not finished initializing or is in the process of disposing.
   at CefSharp.WebBrowserExtensions.Reload(IWebBrowser browser, Boolean ignoreCache)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__1f(ScreenState oldState, ScreenState newState) in c:\projects\stylet\Stylet\Screen.cs:line 155
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 141
   at Stylet.ScreenExtensions.<>c__DisplayClass1.<ActivateWith>b__0(Object o, ActivationEventArgs e) in c:\projects\stylet\Stylet\ScreenExtensions.cs:line 68
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 141
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel) in c:\projects\stylet\Stylet\WindowManager.cs:line 220
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog) in c:\projects\stylet\Stylet\WindowManager.cs:line 194
   at Stylet.WindowManager.ShowWindow(Object viewModel) in c:\projects\stylet\Stylet\WindowManager.cs:line 90
   at SyncTrayzor.Pages.ShellViewModel.EnsureInForeground() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 183
--- End of stack trace from previous location where exception was thrown ---
   at Stylet.Xaml.ActionBase.InvokeTargetMethod(Object[] parameters) in c:\projects\stylet\Stylet\Xaml\ActionBase.cs:line 201
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Thanks for reporting this.

I'm pretty sure I just botched an intermediate release - this doesn't affect any official releases. I've undone my mistake :smile:
