### ISSUE TITLE
Synctrayzor crashing just when started

### ISSUE THREAD

**Issue by gsola96** [canton7/SyncTrayzor#280]
I have a Windows 7 machine running synctrayzor for some time now without any problem. Today when I rebooted it after installing updates, it starts at bootup as always but it crashes and tells me to open an issue here copying this text.

Hope someone can help me.
Thanks in advance

`Version: 1.1.8.329; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyncTrayzor.Syncthing.Folders.FolderIgnores..ctor(List`1 ignores, List`1 patterns) in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\FolderIgnores.cs:line 23
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<>c__DisplayClass29_0.<<FetchFoldersAsync>b__2>d.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<FetchFoldersAsync>d__29.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 187
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<LoadFoldersAsync>d__27.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadConfigDataAsync>d__137.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 497
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadStartupDataAsync>d__136.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 475
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartClientAsync>d__130.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 367
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartAsync>d__120.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__39.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by canton7** [comment]
You're running version 1.1.8, which does not support Syncthing 0.13. Support for Syncthing 0.13 was added in 1.1.9, which was released on 3 May. It should have been prompting you to upgrade for over a month :smile: 

Please download and install the latest version (1.1.10) [from here](https://github.com/canton7/SyncTrayzor/releases/tag/v1.1.10).

**Comment by gsola96** [comment]
Well, I have several machines running headless SyncThing and SyncTrayzor on some Windows machines and I'm aware of updates about SyncThing and not about SyncTrayzor I think...
Nevertheless, it's strange that this error pops now since I updated to 0.13 on the server on May (when it was released)

Anyway, thanks for the info!

**Comment by canton7** [comment]
The version you were running, 1.1.8, will have exhibited this crash the second it tried to run Syncthing 0.13. 

How are you running SyncTrayor headless? There must be a desktop attached. It tells you about updates using a tray notification.

**Comment by canton7** [comment]
Closing as no response
