### ISSUE TITLE
"Oops! Something went wrong!" Message

### ISSUE THREAD

**Issue by insanegerman** [canton7/SyncTrayzor#303]
Hello, I revived an error message when reopening SyncTrayzor. The full stack trace is:

```
Version: 1.1.11.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyncTrayzor.Pages.ViewerViewModel.OnClose() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\ViewerViewModel.cs:line 274
   at Stylet.Screen.<Stylet.IScreenState.Close>b__27(ScreenState oldState, ScreenState newState) in c:\projects\stylet\Stylet\Screen.cs:line 192
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 139
   at Stylet.ScreenExtensions.TryClose(Object screen) in c:\projects\stylet\Stylet\ScreenExtensions.cs:line 40
   at Stylet.ScreenExtensions.<>c__DisplayClass7.<CloseWith>b__6(Object o, CloseEventArgs e) in c:\projects\stylet\Stylet\ScreenExtensions.cs:line 110
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Close>b__27(ScreenState oldState, ScreenState newState) in c:\projects\stylet\Stylet\Screen.cs:line 196
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 139
   at Stylet.ScreenExtensions.TryClose(Object screen) in c:\projects\stylet\Stylet\ScreenExtensions.cs:line 40
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

If the log file is needed, I am able to provide that.

**Comment by canton7** [comment]
Thanks for this. The stack trace on its own should be enough to fix
