### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by apisarenco** [canton7/SyncTrayzor#311]
Version: 1.1.2.247; Variant: Installed; Arch: Amd64
    Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
    System.NullReferenceException: Object reference not set to an instance of an object.
       at SyncTrayzor.SyncThing.FolderIgnores..ctor(List`1 ignores, List`1 patterns) in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\Folder.cs:line 32
       at SyncTrayzor.SyncThing.SyncThingFolderManager.<>c__DisplayClass29_0.<<FetchFoldersAsync>b__2>d.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingFolderManager.cs:line 180
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SyncTrayzor.SyncThing.SyncThingFolderManager.<FetchFoldersAsync>d__29.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingFolderManager.cs:line 187
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SyncTrayzor.SyncThing.SyncThingFolderManager.<LoadFoldersAsync>d__27.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingFolderManager.cs:line 108
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SyncTrayzor.SyncThing.SyncThingManager.<LoadConfigDataAsync>d__138.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 518
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SyncTrayzor.SyncThing.SyncThingManager.<LoadStartupDataAsync>d__137.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 483
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__131.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 379
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__119.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 203
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 17
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at SyncTrayzor.Pages.ShellViewModel.<Start>d__39.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 86
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[SyncTrayzor_log.txt](https://github.com/canton7/SyncTrayzor/files/460821/SyncTrayzor_log.txt)

**Comment by apisarenco** [comment]
Hah, it found an update. Now it starts up.

**Comment by canton7** [comment]
Yep, 1.1.2 is ancient. 

Out of curiosity, how did you end up with such an old version? Did you just not run it for ages? Is there another website hosting downloads?

**Comment by apisarenco** [comment]
Dual boot :) haven't used this OS much lately.

**Comment by canton7** [comment]
Ah, fair enough!
