### ISSUE TITLE
NullReferenceException SyncTrayzor 1.1.13.0 amd64 portable

### ISSUE THREAD

**Issue by nof8** [canton7/SyncTrayzor#321]
Crashed while I've been away from computer.

syncthing v0.14.10 "Dysprosium Dragonfly" (go1.7.1 windows-amd64) jenkins@build.syncthing.net 2016-11-01 10:26:25 UTC

Windows 10 Home x64 1607

```
Version: 1.1.13.0; Variant: Portable; Arch: Amd64
Path: T:\PortableApps\synctrayzorportable-x64\synctrayzor.exe
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<PauseDeviceAsync>d__28.MoveNext() в C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Devices\SyncthingDeviceManager.cs:строка 141
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в SyncTrayzor.Services.Metering.MeteredNetworkManager.<UpdateDeviceAsync>d__33.MoveNext() в C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:строка 313
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в SyncTrayzor.Services.Metering.MeteredNetworkManager.<DeviceConnected>d__24.MoveNext() в C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:строка 179
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Weird, that line of code shouldn't be able to throw that exception. Mind posting the relevant section of your log? You'll find it in the `logs` subdirectory.

**Comment by nof8** [comment]
[SyncTrayzor — copy.log.zip](https://github.com/canton7/SyncTrayzor/files/589161/SyncTrayzor.copy.log.zip)

**Comment by Zillode** [comment]
Ditto with non-portable version:
```
Version: 1.1.13.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<PauseDeviceAsync>d__28.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Devices\SyncthingDeviceManager.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<UpdateDeviceAsync>d__33.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 313
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.Metering.MeteredNetworkManager.<DeviceConnected>d__24.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\MeteredNetworkManager.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
