### ISSUE TITLE
Error starting Synctrayzor

### ISSUE THREAD

**Issue by fbreve** [canton7/SyncTrayzor#341]
```
Version: 1.1.14.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 105
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 114
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Can you give me some context? Have you used SyncTrayzor in the past? Did you upgrade? Anything else that might be vaguely relevant?

Can you paste the contents of `C:\Program Files\SyncTrayzor\InstallCount.txt`?

Delete or rename  `C:\Program Files\SyncTrayzor\InstallCount.txt` to fix the issue, although I'd love to understand what caused it.

**Comment by fbreve** [comment]
Yes, I've been using it for more than a year, at least.

I didn't upgrade recently. I only restarted the computer after a crash (screen frozen, don't know what caused it)

InstallCount.txt is attached. There are only two "NUL" characters on it.

Renaming it did work. Thank you.

[InstallCount.txt](https://github.com/canton7/SyncTrayzor/files/813898/InstallCount.txt)

**Comment by canton7** [comment]
Weird, something has corrupted it. That file is only ever edited by the installer, and SyncTrayzor itself doesn't have permission to edit it.

I'd check the health of your disk - sounds like it's killing files.

**Comment by fbreve** [comment]
According to CrystalDiskInfo it is fine. 

![image](https://cloud.githubusercontent.com/assets/7475908/23509163/9d1e239c-ff33-11e6-9885-1105f5bc0490.png)

**Comment by canton7** [comment]
Weird, I've no idea how that file ended up with NULLs in then. Pretty confident it's not SyncTrayzor though, so I'll blame goblins.

**Comment by canton7** [comment]
Closing as suspect disk corruption
