### ISSUE TITLE
Exception reported

### ISSUE THREAD

**Issue by endolith** [canton7/SyncTrayzor#361]
```
Version: 1.1.15.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.Exception: Unable to find Syncthing at path C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\syncthing.exe
   at SyncTrayzor.Syncthing.SyncthingProcessRunner.Start() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingProcessRunner.cs:line 104
   at SyncTrayzor.Syncthing.SyncthingManager.<StartAsync>d__120.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 193
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ViewerViewModel.<Start>d__39.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\ViewerViewModel.cs:line 305
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I think the actual problem is that Avast antivirus keeps deleting syncthing.exe?

**Comment by canton7** [comment]
Yep!

On startup, SyncTrayzor will replace `C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\syncthing.exe` if it doesn't exist (downgrading it in the process). However if it's deleted after SyncTrayzor starts, that counts as deleting an application's files from under it while it's running, which it's not going to like.

Tell Avast to behave.

**Comment by canton7** [comment]
Hi, any update?

**Comment by endolith** [comment]
Well it's been working since I put it in Avast's exception list.  Can the error message be made more obvious?

**Comment by canton7** [comment]
Potentially. There are plenty of other files which you could delete while SyncTrayzor is running, though, and most of them I wouldn't be able to detect in time to show a nice error message.
