### ISSUE TITLE
UnauthorizedAccessException when opening the App

### ISSUE THREAD

**Issue by Suresh301190** [canton7/SyncTrayzor#378]
Getting exception on the first run PFB the attached exception and the log file.

App Version 1.1.16

```
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at SyncTrayzor.Services.AutostartProvider.SetAutoStart(AutostartConfiguration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\AutostartProvider.cs:line 202
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 164
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Attached log file - [SyncTrayzor-log.zip](https://github.com/canton7/SyncTrayzor/files/1083177/SyncTrayzor.zip)

**Comment by canton7** [comment]
I'm afraid I'm on mobile and can't open zips. What version of SyncTrayzor?

**Comment by canton7** [comment]
Mind trying this build? https://ci.appveyor.com/project/canton7/synctrayzor/build/1.1.16.470/artifacts

**Comment by canton7** [comment]
Does that fix your issue?

**Comment by Suresh301190** [comment]
Not sure but the issue was resolved after I opened the app usi5ing admin rights the first time.
