### ISSUE TITLE
Crash on startup: NULL reference in SyncthingConnectionsWatcher.cs

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#380]
```
Version: 1.1.16.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyncTrayzor.Syncthing.SyncthingConnectionsWatcher.OnStop() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingConnectionsWatcher.cs:line 48
   at SyncTrayzor.Syncthing.SyncthingPoller.<StartInternal>d__10.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingPoller.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Full Log: 
https://gist.github.com/anonymous/4b701858d8e79c6921632c98bc90f9af

SyncTrayzor v.1.1.16
Syncthing v.0.14.30
OS: Win10x64

**Comment by canton7** [comment]
That's a new one! Thanks
