### ISSUE TITLE
SyncTrayzor stopped launching Syncthing & "unhandled AppDomain exception occurred"

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#418]
For some reason SyncTrayzor decided to die on me on one of the PCs:

It's also refuses to launch Syncthing (only SyncTrayzor.exe in task manager).
The only thing in the log is:
```
2017-11-04 17:54:13.5595 #14212 [Info] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.18.0 (Amd64) started at C:\Program Files\SyncTrayzor\SyncTrayzor.exe (.NET version: 4.7 on Windows 10 Creators Update systems (460798)) 
2017-11-04 17:54:13.6456 #14212 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\USER_NAME\AppData\Roaming\SyncTrayzor\logs 
2017-11-04 17:54:13.6481 #14212 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingBackupPath: C:\Program Files\SyncTrayzor\syncthing.exe 
2017-11-04 17:54:13.6481 #14212 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\USER_NAME\AppData\Roaming\SyncTrayzor\config.xml 
2017-11-04 17:54:13.6481 #14212 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\USER_NAME\AppData\Roaming\SyncTrayzor\config-backups 
2017-11-04 17:54:13.6481 #14212 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Users\USER_NAME\AppData\Local\SyncTrayzor\cef\cache 
2017-11-04 17:54:13.6481 #14212 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingPath: C:\Users\USER_NAME\AppData\Roaming\SyncTrayzor\syncthing.exe 
2017-11-04 17:54:13.6481 #14212 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingHomePath:  
2017-11-04 17:54:13.6481 #14212 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Checking for other SyncTrayzor processes 
2017-11-04 17:54:13.6671 #14212 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Did not find any other processes, or they all responded with an error 
2017-11-04 17:54:13.7021 #14212 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowDeviceConnectivityBalloons=True ShowDeviceOrFolderRejectedBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingCommandLineFlags=[] SyncthingEnvironmentalVariables=[] SyncthingDenyUpgrade=False SyncthingPriorityLevel=Normal Folders=[] NotifyOfNewVersions=True LatestNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingCustomPath= SyncthingCustomHomePath= ShowSynchronizedBalloonEvenIfNothingDownloaded=False DisableHardwareRendering=False EnableFailedTransferAlerts=True EnableConflictFileMonitoring=True SyncthingDebugFacilities=[] ConflictResolverDeletesToRecycleBin=True PauseDevicesOnMeteredNetworks=True HaveDonated=False IconAnimationMode=DataTransferring OpenFolderCommand=explorer.exe "{0}" ShowFileInFolderCommand=explorer.exe /select, "{0}"LogLevel=Info> 
2017-11-04 17:54:13.7206 #14212 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Found existing configuration at C:\Users\USER_NAME\AppData\Roaming\SyncTrayzor\config.xml 
2017-11-04 17:54:13.8027 #14212 [Debug] SyncTrayzor.Services.AutostartProvider: Have read/write access to the registry 
2017-11-04 17:54:14.5076 #14212 [Debug] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options 
2017-11-04 17:59:14.5586 #14212 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 87MiB. Private Memory Size: 63MiB. GC Total Memory: 5MiB 
2017-11-04 18:04:14.5481 #14212 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 87MiB. Private Memory Size: 63MiB. GC Total Memory: 5MiB 
```

Or, at times it'll crash on startup with this error (logged, not "nicely shown" by SyncTrayzor):
```
2017-11-04 17:53:14.2981 #13744 [Error] SyncTrayzor.Bootstrapper: An unhandled AppDomain exception occurred. Terminating: True Stylet.Xaml.ActionNotSetException View.ActionTarget not set on control Hardcodet.Wpf.TaskbarNotification.TaskbarIcon (method DoubleClick). This probably means the control hasn't inherited it from a parent, e.g. because a ContextMenu or Popup sits in the visual tree. You will need so set 's:View.ActionTarget' explicitly. See the wiki section "Actions" for more details. Void AssertTargetSet()    at Stylet.Xaml.ActionBase.AssertTargetSet() in c:\projects\stylet\Stylet\Xaml\ActionBase.cs:line 172
   at Stylet.Xaml.CommandAction.Execute(Object parameter) in c:\projects\stylet\Stylet\Xaml\CommandAction.cs:line 155
   at Hardcodet.Wpf.TaskbarNotification.Util.ExecuteIfEnabled(ICommand command, Object commandParameter, IInputElement target) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Util.cs:line 273
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.RaiseTrayMouseDoubleClickEvent() in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\TaskbarIcon.Declarations.cs:line 1137
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.OnMouseEvent(MouseEvent me) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\TaskbarIcon.cs:line 389
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.ProcessWindowMessage(UInt32 msg, IntPtr wParam, IntPtr lParam) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Interop\WindowMessageSink.cs:line 252
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.OnWindowMessageReceived(IntPtr hwnd, UInt32 messageId, IntPtr wparam, IntPtr lparam) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Interop\WindowMessageSink.cs:line 216 Stylet.Xaml.ActionNotSetException: View.ActionTarget not set on control Hardcodet.Wpf.TaskbarNotification.TaskbarIcon (method DoubleClick). This probably means the control hasn't inherited it from a parent, e.g. because a ContextMenu or Popup sits in the visual tree. You will need so set 's:View.ActionTarget' explicitly. See the wiki section "Actions" for more details.
   at Stylet.Xaml.ActionBase.AssertTargetSet() in c:\projects\stylet\Stylet\Xaml\ActionBase.cs:line 172
   at Stylet.Xaml.CommandAction.Execute(Object parameter) in c:\projects\stylet\Stylet\Xaml\CommandAction.cs:line 155
   at Hardcodet.Wpf.TaskbarNotification.Util.ExecuteIfEnabled(ICommand command, Object commandParameter, IInputElement target) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Util.cs:line 273
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.RaiseTrayMouseDoubleClickEvent() in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\TaskbarIcon.Declarations.cs:line 1137
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.OnMouseEvent(MouseEvent me) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\TaskbarIcon.cs:line 389
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.ProcessWindowMessage(UInt32 msg, IntPtr wParam, IntPtr lParam) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Interop\WindowMessageSink.cs:line 252
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.OnWindowMessageReceived(IntPtr hwnd, UInt32 messageId, IntPtr wparam, IntPtr lparam) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Interop\WindowMessageSink.cs:line 216
```

SyncTrayzor v.1.1.18
Syncthing v.0.14.39
Windows 10 x64

**Comment by canton7** [comment]
The second dups #257. For the first, can you increase your logging level to Debug (Settings -> Logging and STTRACE -> Log Level) and try again?

**Comment by canton7** [comment]
Closing as no response.

**Comment by scienmind** [comment]
Yeah, that's probably the right thing to do.
I've set the STTRACE, but haven't run into this issue again since (although earlier it was quite persistent...)
