### ISSUE TITLE
Synctrayzor errors in startup after Windows 10 recovery

### ISSUE THREAD

**Issue by locksmithone** [canton7/SyncTrayzor#422]
Had some issues with my Win 10 box, which is now in the process of recovery. During this process, Synctrayzor is giving out the error below when starting at boot.

I suspect there might be a corrupt file somewhere, but could not figure it out from the error message. Already attempted reinstalling Synctrayzor, but no success. Hints?

Version: 1.1.18.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at OxyPlot.PlotModel..ctor()
   at SyncTrayzor.Pages.Tray.NetworkGraphViewModel..ctor(ISyncthingManager syncthingManager) in C:\projects\synctrayzor\src\SyncTrayzor\Pages\Tray\NetworkGraphViewModel.cs:line 30
   at lambda_method(Closure , IRegistrationContext )
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\SingletonRegistration.cs:line 37
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 101
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 112
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 101
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 112
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\SingletonRegistration.cs:line 37
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 101
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 112
   at StyletIoC.Internal.Registrations.FuncNoKeyRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\FuncNoKeyRegistration.cs:line 38
   at StyletIoC.Internal.Registrations.FuncNoKeyRegistration..ctor(IRegistration delegateRegistration) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\FuncNoKeyRegistration.cs:line 27
   at StyletIoC.Internal.Container.TryCreateFuncFactory(Type type, String key, IRegistrationCollection& registrations) in c:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:line 287
   at StyletIoC.Internal.Container.StyletIoC.Creation.IRegistrationContext.CanResolve(Type type, String key) in c:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:line 180
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__3(ParameterInfo p) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 68
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 67
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal() in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\RegistrationBase.cs:line 38
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator() in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\RegistrationBase.cs:line 30
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable) in c:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:line 108
   at StyletIoC.Internal.Container.Get[T](String key) in c:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:line 102
   at Stylet.Bootstrapper`1.get_RootViewModel() in c:\projects\stylet\Stylet\Bootstrapper.cs:line 26
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 164
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by canton7** [comment]
Something is seriously messed up with your .NET installation, looks like critical files have been deleted. Try repairing / reinstalling the .NET framework.

**Comment by locksmithone** [comment]
I had a bad reboot on my computer and that might have corrupted some files.

I am on Windows 10. In Windows 10, there is practically no workable way of
repairing/reinstalling .NET framework

_ SFC and DISM are close to useless in repairing what needs to be repaired.
_ I have attempted "features on/off" to remove and re-add .NET. Although
the feature was removed and then added, synctrayzor still does not work.
_ I have attempted a "focused" DISM to add the specific .NET features from
the Windows ISO, sxs, cab files. One of those cab files refuses to install.
I have found no solution to mitigate the error.
_ Windows 10 update? No luck.
_ Manually installing/reinstalling .NET is forbidden. Windows says the
feature is already installed.
_ I have found tools from Microsoft support to evaluate .NET
corruption/errors. The tool indicates there are not errors. There is also a
tool to repair .NET installation, but it repairs nothing.

My next attempt is an in-place "upgrade" of Windows 10 (from Windows 10),
an attempt to repair what needs to be repaired and not lose my apps,
programs, configurations. If it fails, the only next option is to reinstall
windows, lose apps and programs and configurations, keep personal files,
and reinstall all apps, programs, geez.

The sad fact is that I have already invested much more time trying to
recover my installation than if I simply had reinstalled windows from
scratch right from the beginning, and then reinstalled my apps.

**Comment by locksmithone** [comment]
Update.

I did an in-place upgrade of Windows 10, from Windows 10. Not really an upgrade, but the only way to re-install Windows without losing configuration and programs. That fixed the .net corruption, but the syncthing databases were also corrupted. Deleted them, they were rebuilt, and now synctrayzor is back in business.

**Comment by canton7** [comment]
Glad you managed to find a fix! I was going to suggest grabbing the right .net installers, but your approach was probably easier.
