### ISSUE TITLE
"Oops! Something went badly wrong." (Crash Message from SyncTrayzor)

### ISSUE THREAD

**Issue by piz333** [canton7/SyncTrayzor#426]
Version: 1.1.18.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.UnauthorizedAccessException: Access is denied.

   at Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   at SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 51
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 127
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 139
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
It looks like the user you're running SyncTrayzor doesn't have permissions to write to `C:\Users\<You>\AppData\Local\SyncTrayzor`?

**Comment by piz333** [comment]
It appears that, all of a sudden, Windows 10 has removed my access to a whole host of directories: my own AppData, c:\ProgramData, and others. They're there but they don't show up in Explorer or cmd. If I manually type them into the Explorer path or in "cd AppData," they're there and I can view them. But I get prompted for admin authorization if I try to do anything like copying files into them.

My account is literally the only one on the PC and I set it up two months ago as an administrator. There have been no issues until now. I'm *so* happy...

**Comment by canton7** [comment]
Joy, thanks for letting me know!

**Comment by jtbr** [comment]
I'm having the same problem opening SyncTrayzor after a new install, and I _can_ write to (and create) that directory. This is on my work computer so there may be some security controls that are causing the issue, however I can't think of what that might be. Like I said, it can indeed write to the local appdata directory, although the same cannot be said of the installation directory. I'm running windows 7.

Here is the trace:
```Version: 1.1.18.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.UnauthorizedAccessException: Access is denied.

   at Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   at SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 51
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 127
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 139
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
This is a separate issue. Please open a new issue, and supply the entries from your log file which appear before the crash (File -> Settings -> Logging + STTRACE -> Show SyncTrayzor log file)
