### ISSUE TITLE
JSON integer 1688900941950290027 is too large or small for an Int32

### ISSUE THREAD

**Issue by DmitryStrunevsky** [canton7/SyncTrayzor#441]
SyncTrayzor crashes at startup on Windows 10.
App started crash after add device via [syncthing-lite](https://github.com/Nutomic/syncthing-lite#syncthing-lite)
```
2018-03-06 08:16:43.2223 #15984 [Error] SyncTrayzor.Syncthing.SyncthingManager: Unexpected exception while starting Syncthing: JSON integer 1688900941950290027 is too large or small for an Int32. Path 'version', line 1, position 508. Newtonsoft.Json.JsonReaderException JSON integer 1688900941950290027 is too large or small for an Int32. Path 'version', line 1, position 508. Void ParseNumber(Newtonsoft.Json.ReadType)    at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at RestEase.JsonResponseDeserializer.Deserialize[T](String content, HttpResponseMessage response, ResponseDeserializerInfo info)
   at RestEase.Implementation.Requester.<RequestAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.ApiClient.SyncthingApiClient.<FetchFolderStatusAsync>d__12.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\ApiClient\SyncthingApiClient.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<FetchFolderStatusAsync>d__28.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<>c__DisplayClass27_0.<<FetchFoldersAsync>b__2>d.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<FetchFoldersAsync>d__27.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<LoadFoldersAsync>d__25.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadConfigDataAsync>d__135.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 502
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadStartupDataAsync>d__134.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 480
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartClientAsync>d__128.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 350 Newtonsoft.Json.JsonReaderException: JSON integer 1688900941950290027 is too large or small for an Int32. Path 'version', line 1, position 508.
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at RestEase.JsonResponseDeserializer.Deserialize[T](String content, HttpResponseMessage response, ResponseDeserializerInfo info)
   at RestEase.Implementation.Requester.<RequestAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.ApiClient.SyncthingApiClient.<FetchFolderStatusAsync>d__12.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\ApiClient\SyncthingApiClient.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<FetchFolderStatusAsync>d__28.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<>c__DisplayClass27_0.<<FetchFoldersAsync>b__2>d.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<FetchFoldersAsync>d__27.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.Folders.SyncthingFolderManager.<LoadFoldersAsync>d__25.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\Folders\SyncthingFolderManager.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadConfigDataAsync>d__135.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 502
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadStartupDataAsync>d__134.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 480
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartClientAsync>d__128.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 350
```

**Comment by canton7** [comment]
I think this means you must have had a device with 1688900941950290027 files! Which doesn't seem right....

Closing, as it's old and others haven't seen it. Please reopen if you can still reproduce this! Thanks.
