### ISSUE TITLE
Conflict resolver & Folder list disconnected from syncthing

### ISSUE THREAD

**Issue by scienmind** [canton7/SyncTrayzor#466]
Sometimes SyncTrayzor would stop alerting about conflicts.
Manually opening "Conflict resolver" results in a message:

![image](https://user-images.githubusercontent.com/11633330/42549755-65ffa47e-84bd-11e8-8b7b-3399535e91ce.png)

When this occurs, folder list in settings is also inaccessible:
![image](https://user-images.githubusercontent.com/11633330/42549785-7d2fdf06-84bd-11e8-8d25-4137f5ce98ce.png)

All that while syncthing is alive and well.
SyncTrayzor itself doesn't crash so I'm not sure if it related to other conflict resolver issues reported.
Restarting SyncTrayzor usually fixes the issue.

Log:
```
2018-07-11 00:17:57.1710 #12708 [Error] SyncTrayzor.Services.Conflicts.ConflictFileManager: Failed to enumerate files in folder <PATH>: OperationCanceledException The operation was canceled. System.OperationCanceledException The operation was canceled. Void ThrowOperationCanceledException()    at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at SyncTrayzor.Services.Conflicts.ConflictFileManager.<>c__DisplayClass13_1.<FindConflictsImpl>b__1() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Conflicts\ConflictFileManager.cs:line 204
   at SyncTrayzor.Services.Conflicts.ConflictFileManager.TryFilesystemEnumeration(Action action, String path, String itemType) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Conflicts\ConflictFileManager.cs:line 226 System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at SyncTrayzor.Services.Conflicts.ConflictFileManager.<>c__DisplayClass13_1.<FindConflictsImpl>b__1() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Conflicts\ConflictFileManager.cs:line 204
   at SyncTrayzor.Services.Conflicts.ConflictFileManager.TryFilesystemEnumeration(Action action, String path, String itemType) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Conflicts\ConflictFileManager.cs:line 226
2018-07-11 00:22:31.8248 #12708 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 93MiB. Private Memory Size: 87MiB. GC Total Memory: 10MiB 
2018-07-11 00:27:31.8369 #12708 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 93MiB. Private Memory Size: 87MiB. GC Total Memory: 10MiB 
2018-07-11 00:32:31.8423 #12708 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 93MiB. Private Memory Size: 87MiB. GC Total Memory: 13MiB 
2018-07-11 00:37:31.8551 #12708 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 93MiB. Private Memory Size: 87MiB. GC Total Memory: 11MiB 
```
The failed path in the log is different each time, but those mostly are deeply nested directories (part of Portable SW install)

SyncTrayzor v.1.1.21
Syncthing v.0.14.48
Windows 10 x64

**Comment by canton7** [comment]
Please enable debug logging (Settings -> Logging -> Log Level), and capture logs which show the issue happening. The bit that you posted is just the scanning for conflicts being cancelled - it doesn't show *why* that's happening.

**Comment by scienmind** [comment]
So I the instance with debug logs had this again, here are the logs, I hope it's helpful:
https://privatebin.net/?7e1b9e0a8b6836c5#6yp7w72ilNPmdyfFhhzMdgbN0gAQMWgYBKHXN4riCs8=

**Comment by canton7** [comment]
I'm afraid this slipped off my radar, and the privatebin has expired (for future, please post logs in the github issue, so that doesn't happen). Is this an issue you're still seeing?
