### ISSUE TITLE
Crash...

### ISSUE THREAD

**Issue by epsen** [canton7/SyncTrayzor#468]
Version: 1.1.21.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
```
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at SyncTrayzor.Services.Ipc.IpcCommsServer.<StartInternal>d__9.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Ipc\IpcCommsServer.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/2200413/SyncTrayzor.log)
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/2200414/syncthing.log)

**Comment by canton7** [comment]
Thanks!

**Comment by pyhedgehog** [comment]
Am I right that this fix about crash on syncthing configuration change?
When this fix will be scheduled?

**Comment by canton7** [comment]
No, nothing to do with configuration changes.
