### ISSUE TITLE
1.1.22.0 Fresh install crashes with "ServiceModelSink.Behavior could not be loaded"

### ISSUE THREAD

**Issue by jesse-git** [canton7/SyncTrayzor#484]
Windows 10 1709 Build 16299.42

I decided to try out syncthing because it sounded like a miracle solution. Not sure what's so unusual about my system, but synctrayzor crashes within a couple seconds on every startup. The window is briefly displayed before crashing.

```
2018-10-25 01:14:34.6394 #21488 [Info] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.22.0 (Amd64) started at C:\Program Files\SyncTrayzor\SyncTrayzor.exe (.NET version: Unknown (461308)) 
2018-10-25 01:14:34.6794 #21488 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\User\AppData\Roaming\SyncTrayzor\logs 
2018-10-25 01:14:34.6834 #21488 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingBackupPath: C:\Program Files\SyncTrayzor\syncthing.exe 
2018-10-25 01:14:34.6834 #21488 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\User\AppData\Roaming\SyncTrayzor\config.xml 
2018-10-25 01:14:34.6834 #21488 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\User\AppData\Roaming\SyncTrayzor\config-backups 
2018-10-25 01:14:34.6834 #21488 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Users\User\AppData\Local\SyncTrayzor\cef\cache 
2018-10-25 01:14:34.6834 #21488 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingPath: C:\Users\User\AppData\Roaming\SyncTrayzor\syncthing.exe 
2018-10-25 01:14:34.6834 #21488 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingHomePath:  
2018-10-25 01:14:34.7014 #21488 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Checking for other SyncTrayzor processes 
2018-10-25 01:14:34.7014 #21488 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Did not find any other processes, or they all responded with an error 
2018-10-25 01:14:34.7484 #21488 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowDeviceConnectivityBalloons=True ShowDeviceOrFolderRejectedBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingCommandLineFlags=[] SyncthingEnvironmentalVariables=[] SyncthingDenyUpgrade=False SyncthingPriorityLevel=Normal Folders=[] NotifyOfNewVersions=True LatestNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingCustomPath= SyncthingCustomHomePath= ShowSynchronizedBalloonEvenIfNothingDownloaded=False DisableHardwareRendering=False EnableFailedTransferAlerts=True EnableConflictFileMonitoring=True ConflictResolverDeletesToRecycleBin=True PauseDevicesOnMeteredNetworks=True HaveDonated=False IconAnimationMode=DataTransferring OpenFolderCommand=explorer.exe "{0}" ShowFileInFolderCommand=explorer.exe /select, "{0}"LogLevel=Info> 
2018-10-25 01:14:34.7634 #21488 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Configuration file C:\Users\User\AppData\Roaming\SyncTrayzor\config.xml doesn't exist, so creating 
2018-10-25 01:14:34.7874 #21488 [Warn] SyncTrayzor.Services.Config.ConfigurationProvider: Syncthing doesn't exist at C:\Users\User\AppData\Roaming\SyncTrayzor\syncthing.exe, so copying from C:\Program Files\SyncTrayzor\syncthing.exe 
2018-10-25 01:14:35.2634 #21488 [Debug] SyncTrayzor.Services.AutostartProvider: Have read/write access to the registry 
2018-10-25 01:14:35.2634 #21488 [Debug] SyncTrayzor.Services.AutostartProvider: Setting AutoStart to <AutostartConfiguration AutoStart=True StartMinimized=True> 
2018-10-25 01:14:35.2634 #21488 [Debug] SyncTrayzor.Services.AutostartProvider: Autostart path: "C:\Program Files\SyncTrayzor\SyncTrayzor.exe" -minimized 
2018-10-25 01:14:35.9515 #21488 [Debug] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options 
2018-10-25 01:14:37.3206 #21488 [Error] SyncTrayzor.Bootstrapper: An unhandled AppDomain exception occurred. Terminating: True System.Configuration.ConfigurationErrorsException The type 'Microsoft.VisualStudio.Diagnostics.ServiceModelSink.Behavior, Microsoft.VisualStudio.Diagnostics.ServiceModelSink, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' registered for extension 'Microsoft.VisualStudio.Diagnostics.ServiceModelSink.Behavior' could not be loaded. (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config line 238) System.Object EvaluateOne(System.String[], System.Configuration.SectionInput, Boolean, System.Configuration.FactoryRecord, System.Configuration.SectionRecord, System.Object)    at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.ServiceModel.Activation.AspNetEnvironment.UnsafeGetSectionFromConfigurationManager(String sectionPath)
   at System.ServiceModel.Configuration.ConfigurationHelpers.UnsafeGetAssociatedSection(ContextInformation evalContext, String sectionPath)
   at System.ServiceModel.Description.ConfigLoader.LookupCommonBehaviors(ContextInformation context)
   at System.ServiceModel.Description.ConfigLoader.LoadServiceDescription(ServiceHostBase host, ServiceDescription description, ServiceElement serviceElement, Action`1 addBaseAddress, Boolean skipHost)
   at System.ServiceModel.ServiceHostBase.LoadConfigurationSectionInternal(ConfigLoader configLoader, ServiceDescription description, ServiceElement serviceSection)
   at System.ServiceModel.ServiceHostBase.ApplyConfiguration()
   at System.ServiceModel.ServiceHostBase.InitializeDescription(UriSchemeKeyedCollection baseAddresses)
   at System.ServiceModel.ServiceHost..ctor(Type serviceType, Uri[] baseAddresses)
   at CefSharp.Internals.BrowserProcessServiceHost..ctor(JavascriptObjectRepository javascriptObjectRepository, Int32 parentProcessId, Int32 browserId, IJavascriptCallbackFactory callbackFactory)
   at CefSharp.ManagedCefBrowserAdapter.OnAfterBrowserCreated(IBrowser browser)
   at CefSharp.Internals.ClientAdapter.OnAfterCreated(ClientAdapter* , CefRefPtr<CefBrowser>* browser) System.Configuration.ConfigurationErrorsException: The type 'Microsoft.VisualStudio.Diagnostics.ServiceModelSink.Behavior, Microsoft.VisualStudio.Diagnostics.ServiceModelSink, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' registered for extension 'Microsoft.VisualStudio.Diagnostics.ServiceModelSink.Behavior' could not be loaded. (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config line 238)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.ServiceModel.Activation.AspNetEnvironment.UnsafeGetSectionFromConfigurationManager(String sectionPath)
   at System.ServiceModel.Configuration.ConfigurationHelpers.UnsafeGetAssociatedSection(ContextInformation evalContext, String sectionPath)
   at System.ServiceModel.Description.ConfigLoader.LookupCommonBehaviors(ContextInformation context)
   at System.ServiceModel.Description.ConfigLoader.LoadServiceDescription(ServiceHostBase host, ServiceDescription description, ServiceElement serviceElement, Action`1 addBaseAddress, Boolean skipHost)
   at System.ServiceModel.ServiceHostBase.LoadConfigurationSectionInternal(ConfigLoader configLoader, ServiceDescription description, ServiceElement serviceSection)
   at System.ServiceModel.ServiceHostBase.ApplyConfiguration()
   at System.ServiceModel.ServiceHostBase.InitializeDescription(UriSchemeKeyedCollection baseAddresses)
   at System.ServiceModel.ServiceHost..ctor(Type serviceType, Uri[] baseAddresses)
   at CefSharp.Internals.BrowserProcessServiceHost..ctor(JavascriptObjectRepository javascriptObjectRepository, Int32 parentProcessId, Int32 browserId, IJavascriptCallbackFactory callbackFactory)
   at CefSharp.ManagedCefBrowserAdapter.OnAfterBrowserCreated(IBrowser browser)
   at CefSharp.Internals.ClientAdapter.OnAfterCreated(ClientAdapter* , CefRefPtr<CefBrowser>* browser)
2018-10-25 01:14:37.3556 #21488 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\User\AppData\Roaming\SyncTrayzor\syncthing.exe 
```

**Comment by jesse-git** [comment]
This apparently had nothing to do with synctrayzor, but it's the first .NET app I've used to crash due to the error. To my memory, I have never installed visual studio as indicated in the log... Synctrayzor now launches after removing the offending bits about `Microsoft.VisualStudio.Diagnostics.ServiceModelSink.Behavior` in
`C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config`
