### ISSUE TITLE
SyncTrayzor won't start SyncThing anymore

### ISSUE THREAD

**Issue by r4taw2mg** [canton7/SyncTrayzor#532]
Hi, 

i am running SyncTrayzor 1.1.24  with SyncThing 1.1.4. on Windows 8.1. in a standard configuration which worked before. Now SyncThing seems unable to start. The only thing changing was the installation of grafik and USB drivers. Can anybody help? Thanks in advance.

I upgraded to ST 1.3.0 (by replacing the syncthing.exe), but the problem remained the same. If I select "About" in the Trayzor menu, it says ST version "unknown". Another instance of mine 1.1.23/1.3.0 under Win7 is working fine.

```
Here is the Trayzor-log
2019-10-08 11:54:15.9955 #5196 [Warn] SyncTrayzor.Services.UpdateManagement.UpdateChecker: Fetching updates failed with an error System.Net.Http.HttpRequestException An error occurred while sending the request. Void Throw()    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__3.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__7.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 79 System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'synctrayzor.antonymale.co.uk'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<SendRequestAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__3.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__7.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 79
WebException The remote name could not be resolved: 'synctrayzor.antonymale.co.uk' System.Net.WebResponse EndGetResponse(System.IAsyncResult)
2019-10-08 11:55:06.9190 #5196 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
2019-10-08 11:55:16.6933 #5196 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 11:55:16.9109 #5196 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2019-10-08 11:55:16.9109 #5196 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 11:55:17.0339 #5196 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2019-10-08 11:55:17.0339 #5196 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 11:55:17.1440 #5196 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2019-10-08 11:55:17.1440 #5196 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 11:55:17.2551 #5196 [Warn] SyncTrayzor.Syncthing.SyncthingProcessRunner: 4 restarts in less than 00:01:00: not restarting again 
2019-10-08 11:58:15.7347 #5196 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 118MiB. Private Memory Size: 94MiB. GC Total Memory: 8MiB 
2019-10-08 11:58:15.9121 #5196 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
2019-10-08 12:00:27.3313 #5196 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
2019-10-08 12:02:49.5517 #3204 [Info] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.24.0 (Amd64) started at C:\Program Files\SyncTrayzor\SyncTrayzor.exe (.NET version: Unknown (461814)) 
2019-10-08 12:02:49.6047 #3204 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\Frank\AppData\Roaming\SyncTrayzor\logs 
2019-10-08 12:02:49.6047 #3204 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingBackupPath: C:\Program Files\SyncTrayzor\syncthing.exe 
2019-10-08 12:02:49.6047 #3204 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\Frank\AppData\Roaming\SyncTrayzor\config.xml 
2019-10-08 12:02:49.6047 #3204 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\Frank\AppData\Roaming\SyncTrayzor\config-backups 
2019-10-08 12:02:49.6047 #3204 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Users\Frank\AppData\Local\SyncTrayzor\cef\cache 
2019-10-08 12:02:49.6127 #3204 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingPath: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 12:02:49.6127 #3204 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingHomePath:  
2019-10-08 12:02:49.6127 #3204 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Checking for other SyncTrayzor processes 
2019-10-08 12:02:49.6127 #3204 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Did not find any other processes, or they all responded with an error 
2019-10-08 12:02:49.6768 #3204 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowDeviceConnectivityBalloons=True ShowDeviceOrFolderRejectedBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingCommandLineFlags=[] SyncthingEnvironmentalVariables=[] SyncthingDenyUpgrade=False SyncthingPriorityLevel=Normal Folders=[] NotifyOfNewVersions=True LatestNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingCustomPath= SyncthingCustomHomePath= ShowSynchronizedBalloonEvenIfNothingDownloaded=False DisableHardwareRendering=False EnableFailedTransferAlerts=True EnableConflictFileMonitoring=True ConflictResolverDeletesToRecycleBin=True PauseDevicesOnMeteredNetworks=True HaveDonated=False IconAnimationMode=DataTransferring OpenFolderCommand=explorer.exe "{0}" ShowFileInFolderCommand=explorer.exe /select, "{0}"LogLevel=Info> 
2019-10-08 12:02:49.6978 #3204 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Found existing configuration at C:\Users\Frank\AppData\Roaming\SyncTrayzor\config.xml 
2019-10-08 12:02:49.7418 #3204 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: InstallCount changed from 1 to 2 
2019-10-08 12:02:49.8051 #3204 [Debug] SyncTrayzor.Services.AutostartProvider: Have read/write access to the registry 
2019-10-08 12:02:50.4064 #3204 [Debug] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options 
2019-10-08 12:02:53.9421 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 12:02:54.2523 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2019-10-08 12:02:54.2523 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 12:02:54.3814 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2019-10-08 12:02:54.3814 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 12:02:54.5495 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2019-10-08 12:02:54.5495 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 12:02:54.6926 #3204 [Warn] SyncTrayzor.Syncthing.SyncthingProcessRunner: 4 restarts in less than 00:01:00: not restarting again 
2019-10-08 12:03:01.3099 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 12:03:01.4160 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2019-10-08 12:03:01.4160 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 12:03:01.5351 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2019-10-08 12:03:01.5351 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 12:03:01.6601 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing exited. Restarting... 
2019-10-08 12:03:01.6601 #3204 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe 
2019-10-08 12:03:01.7862 #3204 [Warn] SyncTrayzor.Syncthing.SyncthingProcessRunner: 4 restarts in less than 00:01:00: not restarting again 
2019-10-08 12:03:02.9697 #3204 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
```

**Comment by r4taw2mg** [comment]
My workaround is to start syncting on its own. I cannot use synctrayzor though.

**Comment by canton7** [comment]
Sorry, this slipped under my radar.

It looks like Syncthing's immediately stopping after we start it. Can you try launching the `syncthing.exe` located at `C:\Users\Frank\AppData\Roaming\SyncTrayzor\syncthing.exe` on its own?

**Comment by r4taw2mg** [comment]
Never mind. I did not complain :-)

I did. This works as my current workaround.

**Comment by canton7** [comment]
That exact `syncthing.exe`? Can you try passing `-no-browser -no-restart -gui-address="localhost:8384"`?

**Comment by r4taw2mg** [comment]
I will have to check, as I don't have that computer at hand. 

I did replace that very syncthing.exe by a new download.

I will reply later.

**Comment by r4taw2mg** [comment]
> That exact `syncthing.exe`?

Yes, that one. But I have updated it manually.

> Can you try passing `-no-browser -no-restart -gui-address="localhost:8384"`?

Sorry, you have to give me more details of what to check.

I tried to pass those parameters as command line from Trayzor to ST, but get a message from trayzor that those are not allowed.

**Comment by canton7** [comment]
Pass them to syncthing.exe when you run it manually.

**Comment by r4taw2mg** [comment]
That is working w/o a problem.

**Comment by r4taw2mg** [comment]
How can I uninstall and re-install ST with saving ID and configuration?

**Comment by r4taw2mg** [comment]
I un- and re-installed SyncTrayzor, but the problem remains.

**Comment by dunesong** [comment]
Had the same issue. Running syncthing.exe manually resulted in immediate termination of the program without any error messages.

I downloaded the latest Windows binary of syncthing.exe and put it into the C:\Users\USERNAME\AppData\Roaming\SyncTrayzor\ folder. Now syncthing.exe and SyncTrayzor run successfully.

**Comment by HexXVI** [comment]
> Had the same issue. Running syncthing.exe manually resulted in immediate termination of the program without any error messages.
> 
> I downloaded the latest Windows binary of syncthing.exe and put it into the C:\Users\USERNAME\AppData\Roaming\SyncTrayzor\ folder. Now syncthing.exe and SyncTrayzor run successfully.

This worked, thank you 🙌
