### ISSUE TITLE
SyncTrayzor GUI stuck in "Syncthing Starting..."

### ISSUE THREAD

**Issue by mercteil** [canton7/SyncTrayzor#533]
Thank you for this amazing tool.

I have set up a sync between two servers. 

Today I saw the tray icon on the one server is greyed out and the GUI is stuck in:

![image](https://user-images.githubusercontent.com/36293774/66558258-8c4a4000-eb53-11e9-8339-6a3fdcafc858.png)

1. Synching **is working** fine, files are transferred
2. Gui has problems to wind up **Syncthing Starting...**
3. Logs show only one error:
 

```
2019-10-10 12:35:44.8019 #47608 [Error] SyncTrayzor.Services.Metering.NetworkCostManager: Failed to load network list manager: Exception from HRESULT: 0x80040202 System.Runtime.InteropServices.COMException Exception from HRESULT: 0x80040202 Void Advise(System.Object, Int32 ByRef)    at System.Runtime.InteropServices.ComTypes.IConnectionPoint.Advise(Object pUnkSink, Int32& pdwCookie)
   at NETWORKLIST.INetworkConnectionCostEvents_EventProvider.add_ConnectionCostChanged(INetworkConnectionCostEvents_ConnectionCostChangedEventHandler )
   at NETWORKLIST.NetworkListManagerClass.add_ConnectionCostChanged(INetworkConnectionCostEvents_ConnectionCostChangedEventHandler )
   at SyncTrayzor.Services.Metering.NetworkCostManager..ctor() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\NetworkCostManager.cs:line 42 System.Runtime.InteropServices.COMException (0x80040202): Exception from HRESULT: 0x80040202
   at System.Runtime.InteropServices.ComTypes.IConnectionPoint.Advise(Object pUnkSink, Int32& pdwCookie)
   at NETWORKLIST.INetworkConnectionCostEvents_EventProvider.add_ConnectionCostChanged(INetworkConnectionCostEvents_ConnectionCostChangedEventHandler )
   at NETWORKLIST.NetworkListManagerClass.add_ConnectionCostChanged(INetworkConnectionCostEvents_ConnectionCostChangedEventHandler )
   at SyncTrayzor.Services.Metering.NetworkCostManager..ctor() in C:\projects\synctrayzor\src\SyncTrayzor\Services\Metering\NetworkCostManager.cs:line 42```

**Comment by alex6H** [comment]
Hi,

I have exactly the same problem. For me, it appeared when I added a password to access the GUI. Now it shows me this error:
![image](https://user-images.githubusercontent.com/48403935/68811157-40b61500-0670-11ea-8f79-cd86faeefb58.png)
look like another instance of syncthing is running but Icouldnt find it!

I tried to reinstall but still the same issue...

Can you help me on this?

Many thanks

**Comment by canton7** [comment]
I think you've got different issues. 

@mercteil Can you post your whole log? That snippet is probably unrelated.

@alex6H Can you post your log please? File -> Settings -> Logging -> Show SyncTrayzor Log File.

**Comment by NSempsrott** [comment]
Hello all,

I'm a little late to the party, but I'm having the same problem as mercteil. Syncthing itself works fine, and I can access the GUI via my browser, but that of course kinda defeats the whole purpose of SyncTrayzor. After about 10 minutes I get an error message that tells me that it timed out. I'll try to remember to capture it and add it to my comment. 

I cleared my logs and changed the logging level to debug, to hopefully give a clear idea of what's going on.


[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/3914448/SyncTrayzor.log)

**Comment by mercteil** [comment]
Here is my log

[[DEBUG] SyncTrayzorLog.log…]()

**Comment by mercteil** [comment]
here it is
[SyncTrayzorLog.log](https://github.com/canton7/SyncTrayzor/files/3961391/SyncTrayzorLog.log)

**Comment by canton7** [comment]
@NSempsrott I can't say for sure because it looks like the SyncTrayzor log file is missing stuff at the end, but it looks like Syncthing genuinely took more than 10 minutes to start... Maybe they fixed something there in v1.3.2

**Comment by canton7** [comment]
@mercteil looks like Syncthing is taking a long time to start. Can you try viewing its UI in a web browser, (there's an option in the Syncthing menu) and see if that loads?

Perhaps upgrading Syncthing to v1.3.2 would help you too?

**Comment by mercteil** [comment]
@canton7 

![image](https://user-images.githubusercontent.com/36293774/75879419-b01c6400-5e1b-11ea-948e-564117622c5e.png)

I cannot use the `start in browser option`

I use the latest SyncThing version. However SyncTrayzor does not seem to see the version:

![image](https://user-images.githubusercontent.com/36293774/75879535-d7733100-5e1b-11ea-9eb1-142ee6a45411.png)

:(

**Comment by canton7** [comment]
@mercteil  Open a web browser to http://localhost:8384, then

**Comment by mercteil** [comment]
![image](https://user-images.githubusercontent.com/36293774/75879866-7566fb80-5e1c-11ea-83c4-def61e1ced62.png)

**Comment by mercteil** [comment]
On the other server everything works perfectly, also the browser GUI.

**Comment by mercteil** [comment]
deleted the `...User/AppData/Local/Syncthing/config.xml` file ... everything started properly

It seems some config was corrupt... (never used the file directly only the GUI for configuration)

**Comment by canton7** [comment]
It does look like this is a Syncthing issue I'm afraid, and nothing to do with SyncTrayzor.

**Comment by mercteil** [comment]
Thank for your assistance anyways... and for the amazing piece of software
