### ISSUE TITLE
cryptic error

### ISSUE THREAD

**Issue by dtxl** [canton7/SyncTrayzor#534]
When starting SyncTrayzor on a W7 32bit pc, this error is shown and ST won't start. This happened after a shutdown and starting of the pc later.

thanks.

```
Version: 1.1.24.0; Variant: Installed; Arch: X86
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at StyletIoC.Creation.BuilderUpper.<>c__DisplayClass4.<GetExpression>b__0(FieldInfo x) in c:\projects\stylet\Stylet\StyletIoC\Creation\BuilderUpper.cs:line 42
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at StyletIoC.Creation.BuilderUpper.GetExpression(Expression inputParameterExpression, ParameterExpression registrationContext, Type type) in c:\projects\stylet\Stylet\StyletIoC\Creation\BuilderUpper.cs:line 42
   at StyletIoC.Internal.Creators.CreatorBase.CompleteExpressionFromCreator(Expression creator, ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\CreatorBase.cs:line 24
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 114
   at StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\TransientRegistration.cs:line 15
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 101
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 94
   at StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\TransientRegistration.cs:line 15
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 101
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 94
   at StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\TransientRegistration.cs:line 15
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 101
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 94
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\SingletonRegistration.cs:line 37
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 101
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 94
   at StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\TransientRegistration.cs:line 15
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 101
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 94
   at StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\SingletonRegistration.cs:line 37
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__8(ParameterInfo x) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 101
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 94
   at StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\TransientRegistration.cs:line 15
   at StyletIoC.Internal.Registrations.FuncNoKeyRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\FuncNoKeyRegistration.cs:line 38
   at StyletIoC.Internal.Registrations.FuncNoKeyRegistration..ctor(IRegistration delegateRegistration) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\FuncNoKeyRegistration.cs:line 27
   at StyletIoC.Internal.Container.TryCreateFuncFactory(Type type, String key, IRegistrationCollection& registrations) in c:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:line 287
   at StyletIoC.Internal.Container.StyletIoC.Creation.IRegistrationContext.CanResolve(Type type, String key) in c:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:line 180
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__3(ParameterInfo p) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 68
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at StyletIoC.Internal.Creators.TypeCreator.<>c__DisplayClassd.<GetInstanceExpression>b__2(ConstructorInfo c) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 68
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Creators\TypeCreator.cs:line 67
   at StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(ParameterExpression registrationContext) in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\TransientRegistration.cs:line 15
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal() in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\RegistrationBase.cs:line 38
   at StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator() in c:\projects\stylet\Stylet\StyletIoC\Internal\Registrations\RegistrationBase.cs:line 30
   at StyletIoC.Internal.Container.Get(RuntimeTypeHandle typeHandle, String key, Type typeIfAvailable) in c:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:line 107
   at StyletIoC.Internal.Container.Get[T](String key) in c:\projects\stylet\Stylet\StyletIoC\Internal\Container.cs:line 102
   at Stylet.Bootstrapper`1.get_RootViewModel() in c:\projects\stylet\Stylet\Bootstrapper.cs:line 26
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 169
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 80
   at Stylet.BootstrapperBase.<Setup>b__0(Object o, StartupEventArgs e) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by canton7** [comment]
Weird that you're the only one experiencing this.

I've made a change which might fix it, it'll be out in the next release.

**Comment by canton7** [comment]
Version 1.1.26 is released. Please re-open if you can still reproduce this.
