### ISSUE TITLE
SynctTrayzor will not run Syncthing with Unexpected exception message

### ISSUE THREAD

**Issue by denigmus** [canton7/SyncTrayzor#544]
Syncthing will start successfully from \SyncTrayzorPortable-x64 folder, however SynctTrayzor can't run syncthing with some message about signature.  It doesn't work if start with Admin privileges too.  Win10-64.  

I'm not sure which part of the log you need, so here I copy full log.

Is there any workaround exist? 

```
2020-01-02 02:13:00.3969 #3560 [Info] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.24.0 (Amd64) started at C:\ProgsNodelet\SyncTrayzorPortable-x64\SyncTrayzor.exe (.NET version: Unknown (461308)) 
2020-01-02 02:13:00.4374 #3560 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\ProgsNodelet\SyncTrayzorPortable-x64\logs 
2020-01-02 02:13:00.4374 #3560 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingBackupPath: C:\ProgsNodelet\SyncTrayzorPortable-x64\syncthing.exe 
2020-01-02 02:13:00.4374 #3560 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\ProgsNodelet\SyncTrayzorPortable-x64\data\config.xml 
2020-01-02 02:13:00.4535 #3560 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\ProgsNodelet\SyncTrayzorPortable-x64\data\config-backups 
2020-01-02 02:13:00.4535 #3560 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\ProgsNodelet\SyncTrayzorPortable-x64\data\cef\cache 
2020-01-02 02:13:00.4535 #3560 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingPath: C:\ProgsNodelet\SyncTrayzorPortable-x64\data\syncthing.exe 
2020-01-02 02:13:00.4705 #3560 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingHomePath: C:\ProgsNodelet\SyncTrayzorPortable-x64\data\syncthing 
2020-01-02 02:13:00.4705 #3560 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Checking for other SyncTrayzor processes 
2020-01-02 02:13:00.4895 #3560 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Did not find any other processes, or they all responded with an error 
2020-01-02 02:13:00.5115 #3560 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowDeviceConnectivityBalloons=True ShowDeviceOrFolderRejectedBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingCommandLineFlags=[] SyncthingEnvironmentalVariables=[] SyncthingDenyUpgrade=False SyncthingPriorityLevel=Normal Folders=[] NotifyOfNewVersions=True LatestNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingCustomPath= SyncthingCustomHomePath= ShowSynchronizedBalloonEvenIfNothingDownloaded=False DisableHardwareRendering=False EnableFailedTransferAlerts=True EnableConflictFileMonitoring=True ConflictResolverDeletesToRecycleBin=True PauseDevicesOnMeteredNetworks=True HaveDonated=False IconAnimationMode=DataTransferring OpenFolderCommand=explorer.exe "{0}" ShowFileInFolderCommand=explorer.exe /select, "{0}"LogLevel=Info> 
2020-01-02 02:13:00.5266 #3560 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Found existing configuration at C:\ProgsNodelet\SyncTrayzorPortable-x64\data\config.xml 
2020-01-02 02:13:00.5881 #3560 [Debug] SyncTrayzor.Services.AutostartProvider: Have read/write access to the registry 
2020-01-02 02:13:00.8464 #3560 [Debug] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options 
2020-01-02 02:13:01.2467 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: SyncthingProcessRunner.Start called 
2020-01-02 02:13:01.2557 #3560 [Debug] SyncTrayzor.Syncthing.FreePortFinder: Found free port: 8384 
2020-01-02 02:13:01.2557 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Request to set state: Stopped -> Starting 
2020-01-02 02:13:01.2717 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Setting state: Stopped -> Starting 
2020-01-02 02:13:01.2837 #3560 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\ProgsNodelet\SyncTrayzorPortable-x64\data\syncthing.exe 
2020-01-02 02:13:01.3027 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Starting API clients 
2020-01-02 02:13:01.3257 #3560 [Debug] SyncTrayzor.Syncthing.ApiClient.SyncthingApiClientFactory: Attempting to request API 
2020-01-02 02:13:01.3478 #3560 [Debug] SyncTrayzor.Bootstrapper: Cleaning up config folder path 
2020-01-02 02:13:01.3478 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [start] 02:13:01 INFO: syncthing v1.3.2 "Fermium Flea" (go1.13.4 windows-amd64) teamcity@build.syncthing.net 2019-11-24 08:33:58 UTC 
2020-01-02 02:13:01.3768 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:01 INFO: My ID: LSW6AVF 
2020-01-02 02:13:01.3768 #3560 [Debug] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options 
2020-01-02 02:13:01.4218 #3560 [Warn] SyncTrayzor.Services.UpdateManagement.UpdateChecker: Fetching updates failed with an error System.IO.FileLoadException Не удалось загрузить файл или сборку "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" либо одну из их зависимостей. Сигнатура метода имеет неправильное соглашение о вызовах. (Исключение из HRESULT: 0x80131239) Boolean CanConvert(System.Type)    at Newtonsoft.Json.Converters.BinaryConverter.CanConvert(Type objectType)
   at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at RestEase.JsonResponseDeserializer.Deserialize[T](String content, HttpResponseMessage response, ResponseDeserializerInfo info)
   at RestEase.Implementation.Requester.<RequestAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__3.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__7.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 79 System.IO.FileLoadException: Не удалось загрузить файл или сборку "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" либо одну из их зависимостей. Сигнатура метода имеет неправильное соглашение о вызовах. (Исключение из HRESULT: 0x80131239)
File name: 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ---> System.Runtime.InteropServices.COMException (0x80131239): Сигнатура метода имеет неправильное соглашение о вызовах. (Исключение из HRESULT: 0x80131239)
   at Newtonsoft.Json.Converters.BinaryConverter.CanConvert(Type objectType)
   at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at RestEase.JsonResponseDeserializer.Deserialize[T](String content, HttpResponseMessage response, ResponseDeserializerInfo info)
   at RestEase.Implementation.Requester.<RequestAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient.<FetchUpdateAsync>d__3.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateNotificationClient.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Services.UpdateManagement.UpdateChecker.<FetchUpdateAsync>d__7.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Services\UpdateManagement\UpdateChecker.cs:line 79


COMException Сигнатура метода имеет неправильное соглашение о вызовах. (Исключение из HRESULT: 0x80131239) 
2020-01-02 02:13:02.2785 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Single thread SHA256 performance is 383 MB/s using crypto/sha256 (377 MB/s using minio/sha256-simd). 
2020-01-02 02:13:02.7389 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Hashing performance is 327.64 MB/s 
2020-01-02 02:13:02.7524 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Ready to synchronize "Default Folder" (default) (sendreceive) 
2020-01-02 02:13:02.7524 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Overall send rate is unlimited, receive rate is unlimited 
2020-01-02 02:13:02.7675 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Using discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX 
2020-01-02 02:13:02.7675 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Using discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX 
2020-01-02 02:13:02.7835 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Using discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX 
2020-01-02 02:13:02.8035 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Relay listener (dynamic+https://relays.syncthing.net/endpoint) starting 
2020-01-02 02:13:02.8185 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: QUIC listener ([::]:22000) starting 
2020-01-02 02:13:02.8275 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: TCP listener ([::]:22000) starting 
2020-01-02 02:13:02.8275 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Completed initial scan of sendreceive folder "Default Folder" (default) 
2020-01-02 02:13:02.8470 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: GUI and API listening on 127.0.0.1:8384 
2020-01-02 02:13:02.8630 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: Access the GUI via the following URL: http://localhost:8384/ 
2020-01-02 02:13:02.8630 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:02 INFO: My name is "WK" 
2020-01-02 02:13:03.1318 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:03 INFO: quic://0.0.0.0:22000 detected NAT type: Full cone NAT 
2020-01-02 02:13:03.1714 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:03 INFO: quic://0.0.0.0:22000 resolved external address quic://REMOVED:22000 (via stun.syncthing.net:3478) 
2020-01-02 02:13:03.3636 #3560 [Debug] SyncTrayzor.Syncthing.ApiClient.SyncthingApiClientFactory: Failed to connect on attempt 0 
2020-01-02 02:13:04.3847 #3560 [Debug] SyncTrayzor.Syncthing.ApiClient.SyncthingApiClientFactory: Attempting to request API 
2020-01-02 02:13:04.4427 #3560 [Error] SyncTrayzor.Syncthing.SyncthingManager: Unexpected exception while starting Syncthing: Не удалось загрузить файл или сборку "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" либо одну из их зависимостей. Сигнатура метода имеет неправильное соглашение о вызовах. (Исключение из HRESULT: 0x80131239) System.IO.FileLoadException Не удалось загрузить файл или сборку "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" либо одну из их зависимостей. Сигнатура метода имеет неправильное соглашение о вызовах. (Исключение из HRESULT: 0x80131239) Boolean CanConvert(System.Type)    at Newtonsoft.Json.Converters.BinaryConverter.CanConvert(Type objectType)
   at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at RestEase.JsonResponseDeserializer.Deserialize[T](String content, HttpResponseMessage response, ResponseDeserializerInfo info)
   at RestEase.Implementation.Requester.<RequestAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.ApiClient.SyncthingApiClient.<FetchVersionAsync>d__10.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\ApiClient\SyncthingApiClient.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.ApiClient.SyncthingApiClientFactory.<CreateCorrectApiClientAsync>d__1.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\ApiClient\SyncthingApiClientFactory.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<CreateApiClientAsync>d__127.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartClientAsync>d__128.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 349 System.IO.FileLoadException: Не удалось загрузить файл или сборку "System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" либо одну из их зависимостей. Сигнатура метода имеет неправильное соглашение о вызовах. (Исключение из HRESULT: 0x80131239)
File name: 'System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ---> System.Runtime.InteropServices.COMException (0x80131239): Сигнатура метода имеет неправильное соглашение о вызовах. (Исключение из HRESULT: 0x80131239)
   at Newtonsoft.Json.Converters.BinaryConverter.CanConvert(Type objectType)
   at Newtonsoft.Json.JsonSerializer.GetMatchingConverter(IList`1 converters, Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at RestEase.JsonResponseDeserializer.Deserialize[T](String content, HttpResponseMessage response, ResponseDeserializerInfo info)
   at RestEase.Implementation.Requester.<RequestAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.ApiClient.SyncthingApiClient.<FetchVersionAsync>d__10.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\ApiClient\SyncthingApiClient.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.ApiClient.SyncthingApiClientFactory.<CreateCorrectApiClientAsync>d__1.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\ApiClient\SyncthingApiClientFactory.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<CreateApiClientAsync>d__127.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 335
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartClientAsync>d__128.MoveNext() in C:\projects\synctrayzor\src\SyncTrayzor\Syncthing\SyncthingManager.cs:line 349


COMException Сигнатура метода имеет неправильное соглашение о вызовах. (Исключение из HRESULT: 0x80131239) 
2020-01-02 02:13:13.8244 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:13 INFO: New NAT port mapping: external TCP address REMOVED:51448 to local address 0.0.0.0:22000. 
2020-01-02 02:13:13.8589 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: [LSW6A] 02:13:13 INFO: Detected 1 NAT service 
2020-01-02 02:13:15.5213 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: Kill all Syncthing processes 
2020-01-02 02:13:15.5783 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingProcessRunner: Syncthing process stopped with exit status -1 
2020-01-02 02:13:15.5783 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Request to set state: Starting -> Stopped 
2020-01-02 02:13:15.5963 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Setting state: Starting -> Stopped 
2020-01-02 02:13:15.5963 #3560 [Debug] SyncTrayzor.Syncthing.SyncthingManager: Aborting API clients 
2020-01-02 02:13:15.5963 #3560 [Debug] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options
```

**Comment by canton7** [comment]
Do you have any anti-virus which might be getting in the way?

**Comment by denigmus** [comment]
No, I don't and privileges are full

**Comment by canton7** [comment]
Closing as old. Please reopen if you can still reproduce this. Thanks!
