### ISSUE TITLE
Something went badly wrong. SyncTrayzor is closed.

### ISSUE THREAD

**Issue by Microsoftmylife** [canton7/SyncTrayzor#566]
Hello. Please fix the problem, Syncthing was crashed. Here is the information, I post them hope you'll find a way to fix the problem and give the update. 

****

Version: 1.1.24.0; Variant: Installed; Arch: X86
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.StubHelpers.ObjectMarshaler.ConvertToNative(Object objSrc, IntPtr pDstVariant)
   at MS.Internal.Automation.UiaCoreProviderApi.RawUiaRaiseAutomationPropertyChangedEvent(IRawElementProviderSimple provider, Int32 id, Object oldValue, Object newValue)
   at System.Windows.Automation.Provider.AutomationInteropProvider.RaiseAutomationPropertyChangedEvent(IRawElementProviderSimple element, AutomationPropertyChangedEventArgs e)
   at System.Windows.Automation.Peers.AutomationPeer.RaisePropertyChangedEvent(AutomationProperty property, Object oldValue, Object newValue)
   at System.Windows.Automation.Peers.TextBoxAutomationPeer.RaiseValuePropertyChangedEvent(String oldValue, String newValue)
   at System.Windows.Controls.TextBox.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at MS.Internal.Data.PropertyPathWorker.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at Stylet.PropertyChangedBase.<>c__DisplayClass2.<OnPropertyChanged>b__0() in c:\projects\stylet\Stylet\PropertyChangedBase.cs:line 72
   at Stylet.Execute.<.cctor>b__0(Action a) in c:\projects\stylet\Stylet\Execute.cs:line 43
   at Stylet.PropertyChangedBase.OnPropertyChanged(String propertyName) in c:\projects\stylet\Stylet\PropertyChangedBase.cs:line 68
   at Stylet.ValidatingModelBase.<OnPropertyChanged>d__11.MoveNext() in c:\projects\stylet\Stylet\ValidatingModelBase.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Looks like your machine ran out of memory?

**Comment by canton7** [comment]
I'm afraid I don't think there's anything I can do: if you run out of memory, applications are going to crash.
