### ISSUE TITLE
fatal error: out of memory

### ISSUE THREAD

**Issue by wvw999** [canton7/SyncTrayzor#571]
log:

fatal error: out of memory

runtime stack:
runtime.throw(0xf20683, 0xd)
	C:/Go/src/runtime/panic.go:1116 +0x79
runtime.sysUsed(0xc001752000, 0x8000)
	C:/Go/src/runtime/mem_windows.go:83 +0x230
runtime.(*mheap).allocSpan(0x19285e0, 0x4, 0x1dc8500, 0x193e0e8, 0x2a29db28)
	C:/Go/src/runtime/mheap.go:1229 +0x3cb
runtime.(*mheap).alloc.func1()
	C:/Go/src/runtime/mheap.go:871 +0x6b
runtime.systemstack(0x0)
	C:/Go/src/runtime/asm_amd64.s:370 +0x6b
runtime.mstart()
	C:/Go/src/runtime/proc.go:1041

other:

Version: 1.1.24.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.StubHelpers.ObjectMarshaler.ConvertToNative(Object objSrc, IntPtr pDstVariant)
   at MS.Internal.Automation.UiaCoreProviderApi.RawUiaRaiseAutomationPropertyChangedEvent(IRawElementProviderSimple provider, Int32 id, Object oldValue, Object newValue)
   at System.Windows.Automation.Provider.AutomationInteropProvider.RaiseAutomationPropertyChangedEvent(IRawElementProviderSimple element, AutomationPropertyChangedEventArgs e)
   at System.Windows.Automation.Peers.AutomationPeer.RaisePropertyChangedEvent(AutomationProperty property, Object oldValue, Object newValue)
   at System.Windows.Automation.Peers.TextBoxAutomationPeer.RaiseValuePropertyChangedEvent(String oldValue, String newValue)
   at System.Windows.Controls.TextBox.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at Stylet.PropertyChangedBase.<>c__DisplayClass2.<OnPropertyChanged>b__0() in c:\projects\stylet\Stylet\PropertyChangedBase.cs:line 72
   at Stylet.PropertyChangedBase.OnPropertyChanged(String propertyName) in c:\projects\stylet\Stylet\PropertyChangedBase.cs:line 75
   at Stylet.ValidatingModelBase.<OnPropertyChanged>d__11.MoveNext() in c:\projects\stylet\Stylet\ValidatingModelBase.cs:line 305
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Looks like both Syncthing and SyncTrayzor reported out-of-memory conditions. Since they use independent platforms, this makes me think that you actually ran out of memory. There's nothing an application can do in this situation unfortunately: please ensure you have enough memory.

**Comment by wvw999** [comment]
I have had great luck running both apps in the time since this error happened- the system in question has 16 GB of ram, but if I recall correctly there was some other issue I discovered later (such as Firefox updating itself and then tanking performance for everything else on the system until you restart it)... in any case, it was most definitely a fluke related to some other application. Thanks for a great product!

**Comment by canton7** [comment]
Thanks for letting me know!
