### ISSUE TITLE
SyncTrayzor Fails to Load

### ISSUE THREAD

**Issue by dangeislinger** [canton7/SyncTrayzor#585]
SyncTrayzor failed and asked me to open an issue here. Details below & log attached.
[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/5471958/SyncTrayzor.log)

Version: 1.1.24.0; Variant: Installed; Arch: X86
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileLoadException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. Insufficient system resources exist to complete the requested service. (Exception from HRESULT: 0x800705AA)
File name: 'CefSharp.Core.dll'
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__1d(ScreenState oldState, ScreenState newState) in c:\projects\stylet\Stylet\Screen.cs:line 170
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 155
   at Stylet.Screen.Stylet.IScreenState.Activate() in c:\projects\stylet\Stylet\Screen.cs:line 165
   at Stylet.ScreenExtensions.<>c__DisplayClass1.<ActivateWith>b__0(Object o, ActivationEventArgs e) in c:\projects\stylet\Stylet\ScreenExtensions.cs:line 68
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<>c__DisplayClass1f.<Stylet.IScreenState.Activate>b__1e() in c:\projects\stylet\Stylet\Screen.cs:line 178
   at Stylet.Execute.OnUIThread(Action action) in c:\projects\stylet\Stylet\Execute.cs:line 73
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__1d(ScreenState oldState, ScreenState newState) in c:\projects\stylet\Stylet\Screen.cs:line 178
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler) in c:\projects\stylet\Stylet\Screen.cs:line 155
   at Stylet.Screen.Stylet.IScreenState.Activate() in c:\projects\stylet\Stylet\Screen.cs:line 165
   at Stylet.ScreenExtensions.TryActivate(Object screen) in c:\projects\stylet\Stylet\ScreenExtensions.cs:line 18
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel) in c:\projects\stylet\Stylet\WindowManager.cs:line 222
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog) in c:\projects\stylet\Stylet\WindowManager.cs:line 196
   at Stylet.WindowManager.ShowWindow(Object viewModel) in c:\projects\stylet\Stylet\WindowManager.cs:line 92
   at Stylet.BootstrapperBase.DisplayRootView(Object rootViewModel) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 101
   at Stylet.Bootstrapper`1.Launch() in c:\projects\stylet\Stylet\Bootstrapper.cs:line 90
   at SyncTrayzor.Bootstrapper.Launch() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 205
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
   at Stylet.BootstrapperBase.<Setup>b__0(Object o, StartupEventArgs e) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 48
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Make sure you've got enough spare RAM. Are you using a third-party antivirus?

**Comment by canton7** [comment]
Closing as no response. The next release of SyncTrayzor will change the version of the VC++ redist which it relies on, which might also affect this. Please re-open if you still see this with 1.1.26. Thanks!
