### ISSUE TITLE
SynTrayzor (portable x64 located at C:\Program files) showing this error at startup and even trying to run with admin privileges

### ISSUE THREAD

**Issue by niyonsv** [canton7/SyncTrayzor#592]
I placed the 'SyncTrayzor x64 portable' folder to C:\Program files. But this error is showing up at startup and even trying to run with admin privileges, saying _"Oops! Something went badly wrong. SyncTrayzor is going to have to close. Sorry about that"_. The SyncTrayzor was set up yesterday and worked fine till I shutdown the PC today morning. But after turning on the PC this error is showing up. Not sure if this error was already discussed but sorry I couldn't find one if already posted before. Do I need to set up everything from start? It's okay since I only configured a few folders and only one device.

Here's the information about the error:

> Version: 1.1.24.0; Variant: Portable; Arch: Amd64
Path: C:\Program Files\Utilities\SyncTrayzorPortable-x64\SyncTrayzor.exe
System.UnauthorizedAccessException: Access is denied.
at Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
at SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 51
at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 137
at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 144
at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
at System.Windows.Application.OnStartup(StartupEventArgs e)
at System.Windows.Application.<.ctor>b__1_0(Object unused)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

And here's the log:

> 2020-12-25 13:45:00.3347 #3920 [Info] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.24.0 (Amd64) started at C:\Program Files\Utilities\SyncTrayzorPortable-x64\SyncTrayzor.exe (.NET version: Unknown (528372)) 
2020-12-25 13:45:00.3847 #3920 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Program Files\Utilities\SyncTrayzorPortable-x64\logs 
2020-12-25 13:45:00.3847 #3920 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingBackupPath: C:\Program Files\Utilities\SyncTrayzorPortable-x64\syncthing.exe 
2020-12-25 13:45:00.3847 #3920 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Program Files\Utilities\SyncTrayzorPortable-x64\data\config.xml 
2020-12-25 13:45:00.3847 #3920 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Program Files\Utilities\SyncTrayzorPortable-x64\data\config-backups 
2020-12-25 13:45:00.3847 #3920 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Program Files\Utilities\SyncTrayzorPortable-x64\data\cef\cache 
2020-12-25 13:45:00.3847 #3920 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingPath: C:\Program Files\Utilities\SyncTrayzorPortable-x64\data\syncthing.exe 
2020-12-25 13:45:00.3847 #3920 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingHomePath: C:\Program Files\Utilities\SyncTrayzorPortable-x64\data\syncthing 
2020-12-25 13:45:00.4012 #3920 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Checking for other SyncTrayzor processes 
2020-12-25 13:45:00.4012 #3920 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Did not find any other processes, or they all responded with an error 
2020-12-25 13:45:00.4382 #3920 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowDeviceConnectivityBalloons=True ShowDeviceOrFolderRejectedBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingCommandLineFlags=[] SyncthingEnvironmentalVariables=[] SyncthingDenyUpgrade=False SyncthingPriorityLevel=Normal Folders=[] NotifyOfNewVersions=True LatestNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingCustomPath= SyncthingCustomHomePath= ShowSynchronizedBalloonEvenIfNothingDownloaded=False DisableHardwareRendering=False EnableFailedTransferAlerts=True EnableConflictFileMonitoring=True ConflictResolverDeletesToRecycleBin=True PauseDevicesOnMeteredNetworks=True HaveDonated=False IconAnimationMode=DataTransferring OpenFolderCommand=explorer.exe "{0}" ShowFileInFolderCommand=explorer.exe /select, "{0}"LogLevel=Info> 
2020-12-25 13:45:00.4582 #3920 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Found existing configuration at C:\Program Files\Utilities\SyncTrayzorPortable-x64\data\config.xml 
2020-12-25 13:45:00.5081 #3920 [Warn] SyncTrayzor.Services.Config.ConfigurationProvider: Syncthing doesn't exist at C:\Program Files\Utilities\SyncTrayzorPortable-x64, so copying from C:\Program Files\Utilities\SyncTrayzorPortable-x64\syncthing.exe 
2020-12-25 13:45:00.5281 #3920 [Error] SyncTrayzor.Bootstrapper: An unhandled exception occurred System.UnauthorizedAccessException Access is denied.
 Void Copy(System.String, System.String, Boolean)    at Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   at SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 51
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 137
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 144
   at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) System.UnauthorizedAccessException: Access is denied.
at Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
at SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 51
at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 137
at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 144
at Stylet.BootstrapperBase.Start(String[] args) in c:\projects\stylet\Stylet\BootstrapperBase.cs:line 81
at System.Windows.Application.OnStartup(StartupEventArgs e)
at System.Windows.Application.<.ctor>b__1_0(Object unused)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2020-12-25 13:45:04.8879 #3920 [Debug] SyncTrayzor.Services.ProcessStartProvider: Starting C:\Program Files\Utilities\SyncTrayzorPortable-x64\ProcessRunner.exe --shell  -- "explorer.exe" /select, "C:\Program Files\Utilities\SyncTrayzorPortable-x64\logs\SyncTrayzor.log"

**Comment by canton7** [comment]
The difference between the installed and portable versions is that the install version puts itself into Program Files and its data into AppData, while the portable version keeps its data in the same folder as the executables. This split exists because Windows (rightly) doesn't let applications write to Program Files.

If you're installing into Program Files, you need the installed version, not the portable version.
