### ISSUE TITLE
Upgrade to 1.1.25 crashes on startup on 2 of 4 machines.

### ISSUE THREAD

**Issue by rich8n** [canton7/SyncTrayzor#596]
Version: 1.1.25.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
File name: 'CefSharp.Core.dll'
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by rich8n** [comment]
2020-12-28 09:06:44.4531 #1848 [Error] SyncTrayzor.Bootstrapper: An unhandled AppDomain exception occurred. Terminating: True Stylet.Xaml.ActionNotSetException View.ActionTarget not set on control Hardcodet.Wpf.TaskbarNotification.TaskbarIcon (method DoubleClick). This probably means the control hasn't inherited it from a parent, e.g. because a ContextMenu or Popup sits in the visual tree. You will need so set 's:View.ActionTarget' explicitly. See the wiki section "Actions" for more details. Void AssertTargetSet()    at Stylet.Xaml.ActionBase.AssertTargetSet()
   at Stylet.Xaml.CommandAction.Execute(Object parameter)
   at Hardcodet.Wpf.TaskbarNotification.Util.ExecuteIfEnabled(ICommand command, Object commandParameter, IInputElement target) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Util.cs:line 273
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.RaiseTrayMouseDoubleClickEvent() in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\TaskbarIcon.Declarations.cs:line 1137
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.OnMouseEvent(MouseEvent me) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\TaskbarIcon.cs:line 389
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.ProcessWindowMessage(UInt32 msg, IntPtr wParam, IntPtr lParam) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Interop\WindowMessageSink.cs:line 252
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.OnWindowMessageReceived(IntPtr hwnd, UInt32 messageId, IntPtr wparam, IntPtr lparam) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Interop\WindowMessageSink.cs:line 216 Stylet.Xaml.ActionNotSetException: View.ActionTarget not set on control Hardcodet.Wpf.TaskbarNotification.TaskbarIcon (method DoubleClick). This probably means the control hasn't inherited it from a parent, e.g. because a ContextMenu or Popup sits in the visual tree. You will need so set 's:View.ActionTarget' explicitly. See the wiki section "Actions" for more details.
   at Stylet.Xaml.ActionBase.AssertTargetSet()
   at Stylet.Xaml.CommandAction.Execute(Object parameter)
   at Hardcodet.Wpf.TaskbarNotification.Util.ExecuteIfEnabled(ICommand command, Object commandParameter, IInputElement target) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Util.cs:line 273
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.RaiseTrayMouseDoubleClickEvent() in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\TaskbarIcon.Declarations.cs:line 1137
   at Hardcodet.Wpf.TaskbarNotification.TaskbarIcon.OnMouseEvent(MouseEvent me) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\TaskbarIcon.cs:line 389
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.ProcessWindowMessage(UInt32 msg, IntPtr wParam, IntPtr lParam) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Interop\WindowMessageSink.cs:line 252
   at Hardcodet.Wpf.TaskbarNotification.Interop.WindowMessageSink.OnWindowMessageReceived(IntPtr hwnd, UInt32 messageId, IntPtr wparam, IntPtr lparam) in c:\git\OSS\notifyicon-wpf\Hardcodet.NotifyIcon.Wpf\Source\NotifyIconWpf\Interop\WindowMessageSink.cs:line 216
2020-12-28 09:06:56.2481 #2200 [Info] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.25.0 (Amd64) started at C:\Program Files\SyncTrayzor\SyncTrayzor.exe (.NET version: Unknown (528372)) 
2020-12-28 09:06:56.3191 #2200 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\rich8\AppData\Roaming\SyncTrayzor\logs 
2020-12-28 09:06:56.3191 #2200 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingBackupPath: C:\Program Files\SyncTrayzor\syncthing.exe 
2020-12-28 09:06:56.3191 #2200 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\rich8\AppData\Roaming\SyncTrayzor\config.xml 
2020-12-28 09:06:56.3191 #2200 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\rich8\AppData\Roaming\SyncTrayzor\config-backups 
2020-12-28 09:06:56.3191 #2200 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Users\rich8\AppData\Local\SyncTrayzor\cef\cache 
2020-12-28 09:06:56.3191 #2200 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingPath: C:\Users\rich8\AppData\Roaming\SyncTrayzor\syncthing.exe 
2020-12-28 09:06:56.3191 #2200 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingHomePath:  
2020-12-28 09:06:56.3370 #2200 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Checking for other SyncTrayzor processes 
2020-12-28 09:06:56.3370 #2200 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Did not find any other processes, or they all responded with an error 
2020-12-28 09:06:56.3690 #2200 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowDeviceConnectivityBalloons=True ShowDeviceOrFolderRejectedBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingCommandLineFlags=[] SyncthingEnvironmentalVariables=[] SyncthingDenyUpgrade=False SyncthingPriorityLevel=Normal Folders=[] NotifyOfNewVersions=True LatestNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingCustomPath= SyncthingCustomHomePath= ShowSynchronizedBalloonEvenIfNothingDownloaded=False DisableHardwareRendering=False EnableFailedTransferAlerts=True EnableConflictFileMonitoring=True ConflictResolverDeletesToRecycleBin=True PauseDevicesOnMeteredNetworks=True HaveDonated=False IconAnimationMode=DataTransferring OpenFolderCommand=explorer.exe "{0}" ShowFileInFolderCommand=explorer.exe /select, "{0}"LogLevel=Info> 
2020-12-28 09:06:56.3820 #2200 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Found existing configuration at C:\Users\rich8\AppData\Roaming\SyncTrayzor\config.xml 
2020-12-28 09:06:56.4769 #2200 [Debug] SyncTrayzor.Services.AutostartProvider: Have read/write access to the registry 
2020-12-28 09:06:56.8248 #2200 [Debug] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options 
2020-12-28 09:06:56.9458 #2200 [Error] SyncTrayzor.Bootstrapper: An unhandled exception occurred System.IO.FileNotFoundException Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found. Void OnInitialActivate()    at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
File name: 'CefSharp.Core.dll'
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Weird: nothing's changed in that area. I've pulled the release: please manually downgrade to 1.1.24

**Comment by jirijanata** [comment]
I'm having the same problem. On the machine (Windows Server 2016) is .Net Framework 4.8 installed, but nothing more. Downgrade to 1.1.24 worked just fine.

**Comment by canton7** [comment]
@rich8n You've got two posts with two different errors there. Can you please give details on what you needed to do in order to trigger each of them? Thanks!

**Comment by canton7** [comment]
@jirijanata Which of the two errors above do you see? Did you need to do anything in order to trigger it? Thanks!

**Comment by rich8n** [comment]
One was from the error window itself, one was from the log file linked in the error window.  All I do to trigger it is start SyncTrayzor from the installed shortcut.

**Comment by mediadog** [comment]
Same problem here after updating.  After rebooting, icon showed up in system tray, but right-clicking and selecting open gets the crash.  Then trying to run it from the shortcut gets the crash.  Win7 Enterprise x64.  Going back to 1.1.24 works fine.

Version: 1.1.25.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found.
File name: 'CefSharp.Core.dll'
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
etc.

**Comment by canton7** [comment]
Can you try this build, and confirm whether it fixes your issue, please? https://ci.appveyor.com/project/canton7/synctrayzor/builds/37033863/artifacts 

Thanks!

**Comment by noirflux** [comment]
Ayup, all better!  Thanks for the fast service!

**Comment by canton7** [comment]
I don't suppose anyone who had the "System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies. The specified module could not be found." error is running Windows 8 or earlier? That needed a slightly different fix, but I don't have an old machine to test it on.

**Comment by noirflux** [comment]
As I noted in my post above, the machine here is running Win7 Enterprise x64, and in the build you posted the link to (37033863)  SyncTrayzorSetup-x64.exe works fine.

**Comment by canton7** [comment]
Perfect, thanks!

**Comment by rich8n** [comment]
I updated to the newest version on all 4 PCs, and it's working great!  Thanks for taking the time to address this issue!
