### ISSUE TITLE
SyncTrayzor crashes after update 1.1.25.0

### ISSUE THREAD

**Issue by HokoriXIII** [canton7/SyncTrayzor#599]
Version: 1.1.25.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
SmartFormat.Core.Formatting.FormattingException: Error parsing format string: Invalid number of plural parameters at 31
Обновлено {0:p:1 файл|{} файлов}
-------------------------------^
   в SmartFormat.SmartFormatter.FormatError(FormatItem errorItem, Exception innerException, Int32 startIndex, FormattingInfo formattingInfo) в /_/src/SmartFormat/SmartFormatter.cs:строка 276
   в SmartFormat.SmartFormatter.Format(FormattingInfo formattingInfo) в /_/src/SmartFormat/SmartFormatter.cs:строка 260
   в SmartFormat.SmartFormatter.Format(IFormatProvider provider, String format, Object[] args) в /_/src/SmartFormat/SmartFormatter.cs:строка 154
   в SyncTrayzor.NotifyIcon.NotifyIconManager.FolderSynchronizationFinished(Object sender, FolderSynchronizationFinishedEventArgs e) в C:\projects\synctrayzor\src\SyncTrayzor\NotifyIcon\NotifyIconManager.cs:строка 232
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Looks like someone messed up the translation. Which language is that?

**Comment by HokoriXIII** [comment]
Its Russian. If U need translation in my issue I can translate toEnglish

**Comment by canton7** [comment]
That's fine -- I'll go moan at the person who translated that, thanks

**Comment by canton7** [comment]
Can you try this build, and confirm whether it fixes your issue, please? https://ci.appveyor.com/project/canton7/synctrayzor/builds/37033863/artifacts 

Thanks!

**Comment by matejart** [comment]
Thank you for this fix, @canton7! This has solved the issue for me.

I had a similar error:

```
2020-12-29 14:48:17.4844 #45672 [Error] SyncTrayzor.Bootstrapper: An unhandled exception occurred SmartFormat.Core.Formatting.FormattingException Error parsing format string: Invalid number of plural parameters at 51
You have {0:p:1 conflicted file|{} conflicted files}.
---------------------------------------------------^ Void FormatError(SmartFormat.Core.Parsing.FormatItem, System.Exception, Int32, SmartFormat.Core.Formatting.FormattingInfo)    at SmartFormat.SmartFormatter.FormatError(FormatItem errorItem, Exception innerException, Int32 startIndex, FormattingInfo formattingInfo) in /_/src/SmartFormat/SmartFormatter.cs:line 276
   at SmartFormat.SmartFormatter.Format(FormattingInfo formattingInfo) in /_/src/SmartFormat/SmartFormatter.cs:line 260
   at SmartFormat.SmartFormatter.Format(IFormatProvider provider, String format, Object[] args) in /_/src/SmartFormat/SmartFormatter.cs:line 154
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) SmartFormat.Core.Formatting.FormattingException: Error parsing format string: Invalid number of plural parameters at 51
```

**Comment by canton7** [comment]
That's... very weird. I wasn't expecting that to happen with English.

**Comment by HokoriXIII** [comment]
For me new version helped. For now. It started to crash after some hours yesturday, today it was crushing almoust instantly. New version works fine.
