### ISSUE TITLE
CefSharp.core.dll not a valid win32

### ISSUE THREAD

**Issue by cdurrett** [canton7/SyncTrayzor#604]
syncthing running happily though

Version: 1.1.26.0; Variant: Installed; Arch: X86
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.BadImageFormatException: Could not load file or assembly 'CefSharp.Core.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)
File name: 'CefSharp.Core.dll'
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.Screen.Stylet.IScreenState.Activate()
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<>c__DisplayClass35_0.<Stylet.IScreenState.Activate>b__1()
   at Stylet.Execute.OnUIThread(Action action)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.Screen.Stylet.IScreenState.Activate()
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.DisplayRootView(Object rootViewModel)
   at Stylet.Bootstrapper`1.Launch()
   at SyncTrayzor.Bootstrapper.Launch() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 205
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Duplicate if #602. Please try the build linked there and let me know if it fixes the issue on your machine. Thanks!
