### ISSUE TITLE
Duplicate devices / folders present in config

### ISSUE THREAD

**Issue by endolith** [canton7/SyncTrayzor#61]
```
System.ArgumentException: The source argument contains duplicate keys.
   at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__27.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 323
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__14.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ViewerViewModel.<Start>d__d.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Pages\ViewerViewModel.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Thanks.

What version are you running? 1.0.15?

**Comment by canton7** [comment]
Could I also see the contents of your log? You'll find it at `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs\SyncTrayzor.log`. I suspect you've got multiple folders with the same ID (which I didn't think was possible), but that will tell us for sure.

**Comment by endolith** [comment]
syncthing v0.10.30
synctrayzor 1.0.15

**Comment by endolith** [comment]
```
2015-04-21 07:50:06.6284 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ExePath: C:\Program Files\SyncTrayzor 
2015-04-21 07:50:06.7074 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\logs 
2015-04-21 07:50:06.7074 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingCustomHomePath: C:\Users\Jonathan\AppData\Local\SyncTrayzor\syncthing 
2015-04-21 07:50:06.7074 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncThingPath: C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\syncthing.exe 
2015-04-21 07:50:06.7074 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncThingBackupPath: C:\Program Files\SyncTrayzor\syncthing.exe 
2015-04-21 07:50:06.7124 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\config.xml 
2015-04-21 07:50:06.7124 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\config-backups 
2015-04-21 07:50:06.7864 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowSynchronizedBalloon=True ShowDeviceConnectivityBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingApiKey= SyncthingEnvironmentalVariables=[] SyncthingUseCustomHome=False SyncthingDenyUpgrade=False SyncthingRunLowPriority=False Folders=[] NotifyOfNewVersions=True LastNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True ShowSyncthingConsole=True WindowPlacement= SyncthingWebBrowserZoomLevel=0> 
2015-04-21 07:50:06.8014 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Found existing configuration at C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\config.xml 
2015-04-21 07:50:06.8204 [Info] SyncTrayzor.Services.AutostartProvider: Have read/write access to the registry 
2015-04-21 07:50:06.8234 [Info] SyncTrayzor.Services.AutostartProvider: GetCurrentSetup determined that the current configuration is: <AutostartConfiguration AutoStart=False StartMinimized=False> 
2015-04-21 07:50:06.8234 [Info] SyncTrayzor.Services.AutostartProvider: Setting AutoStart to <AutostartConfiguration AutoStart=False StartMinimized=False> 
2015-04-21 07:50:08.8595 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: SyncThingProcessRunner.Start called 
2015-04-21 07:50:08.8865 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Starting 
2015-04-21 07:50:08.8865 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Stopped -> Starting 
2015-04-21 07:50:08.8865 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Starting syncthing: C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\syncthing.exe 
2015-04-21 07:50:09.5185 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Starting API clients 
2015-04-21 07:50:09.5395 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Attempting to request API using version 0.10.x API client 
2015-04-21 07:50:09.9506 [Debug] SyncTrayzor.Services.UpdateManagement.UpdateNotificationClient: Fetched updates response: <UpdateNotificationResponse data= error=> 
2015-04-21 07:50:09.9506 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
2015-04-21 07:50:10.3776 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:10 INFO: syncthing v0.10.30 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC 
2015-04-21 07:50:10.3786 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:10 INFO: My ID: DQ4LQZO 
2015-04-21 07:50:10.3786 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:10 FATAL: Cannot open database: The process cannot access the file because it is being used by another process. - Is another copy of Syncthing already running? 
2015-04-21 07:50:10.3786 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status Error 
2015-04-21 07:50:10.3786 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Starting -> Stopped 
2015-04-21 07:50:10.3786 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Starting -> Stopped 
2015-04-21 07:50:10.3786 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Aborting API clients 
2015-04-21 07:50:11.5627 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Failed to connect on attempt 0 
2015-04-21 07:50:11.5627 [Info] SyncTrayzor.SyncThing.SyncThingManager: StartClientAsync aborted 
2015-04-21 07:50:13.1587 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: SyncThingProcessRunner.Start called 
2015-04-21 07:50:13.1587 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Starting 
2015-04-21 07:50:13.1587 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Stopped -> Starting 
2015-04-21 07:50:13.1587 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Starting syncthing: C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\syncthing.exe 
2015-04-21 07:50:13.1978 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Starting API clients 
2015-04-21 07:50:13.1978 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Attempting to request API using version 0.10.x API client 
2015-04-21 07:50:13.8988 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:13 INFO: syncthing v0.10.30 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC 
2015-04-21 07:50:13.8988 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:13 INFO: My ID: DQ4LQZO 
2015-04-21 07:50:13.8988 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:13 FATAL: Cannot open database: The process cannot access the file because it is being used by another process. - Is another copy of Syncthing already running? 
2015-04-21 07:50:13.9038 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status Error 
2015-04-21 07:50:13.9038 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Starting -> Stopped 
2015-04-21 07:50:13.9038 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Starting -> Stopped 
2015-04-21 07:50:13.9038 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Aborting API clients 
2015-04-21 07:50:15.1999 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Failed to connect on attempt 0 
2015-04-21 07:50:15.1999 [Info] SyncTrayzor.SyncThing.SyncThingManager: StartClientAsync aborted 
2015-04-21 07:50:26.9785 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: SyncThingProcessRunner.Start called 
2015-04-21 07:50:26.9785 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Starting 
2015-04-21 07:50:26.9785 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Stopped -> Starting 
2015-04-21 07:50:26.9785 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Starting syncthing: C:\Users\Jonathan\AppData\Roaming\SyncTrayzor\syncthing.exe 
2015-04-21 07:50:27.0475 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Starting API clients 
2015-04-21 07:50:27.0475 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Attempting to request API using version 0.10.x API client 
2015-04-21 07:50:27.7766 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:27 INFO: syncthing v0.10.30 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC 
2015-04-21 07:50:27.7766 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:27 INFO: My ID: DQ4LQZO 
2015-04-21 07:50:29.0177 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:29 INFO: Starting web GUI on https://127.0.0.1:8384/ 
2015-04-21 07:50:29.0507 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Failed to connect on attempt 0 
2015-04-21 07:50:30.0657 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Attempting to request API using version 0.10.x API client 
2015-04-21 07:50:30.3017 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:30 INFO: Starting UPnP discovery... 
2015-04-21 07:50:30.3017 [Debug] SyncTrayzor.SyncThing.SyncThingProcessRunner: [DQ4LQ] 07:50:30 INFO: Unrecognized UPnP device of type urn:schemas-upnp-org:device:InternetGatewayDevice:1 
2015-04-21 07:50:31.1938 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClient: Fetched version: <Version arch=amd64 longVersion=syncthing v0.10.30 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC os=windows version=v0.10.30> 
2015-04-21 07:50:31.1938 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClientFactory: Success! 
2015-04-21 07:50:31.1938 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Have the API client! It's SyncThingApiClientV0p10 
2015-04-21 07:50:31.1938 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Starting -> Running 
2015-04-21 07:50:31.1938 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Starting -> Running 
2015-04-21 07:50:31.2128 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Startup Complete! Loading startup data 
2015-04-21 07:50:31.3688 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClient: Fetched configuration: <Config version=10 folders=[<Folder id=audio_test_files path=\\?\C:\Users\Jonathan\Documents\Audio test files devices=[<Device deviceId=DQ4LQZO-TCFTTP5-CSXNTWJ-Z5F4GWH-7KNHE3K-CPBGZIX-7D3SMV2-CYMHQAO>, <Device deviceId=PFTGPAK-ZCABA45-UAVXPM4-PNJ5QN5-UYZS66C-Y2KPDDJ-S44MK5X-34SFPQ2>] readonly=False rescalinterval=00:01:00>, <Folder id=datasheets path=\\?\C:\Users\Jonathan\Documents\Datasheets and application notes devices=[<Device deviceId=DQ4LQZO-TCFTTP5-CSXNTWJ-Z5F4GWH-7KNHE3K-CPBGZIX-7D3SMV2-CYMHQAO>, <Device deviceId=PFTGPAK-ZCABA45-UAVXPM4-PNJ5QN5-UYZS66C-Y2KPDDJ-S44MK5X-34SFPQ2>, <Device deviceId=POWFPEW-KHKNTI5-SVL3YME-JGSSIJF-GITYTRL-2XV72WE-6ZTOLG2-PCMJEAG>] readonly=False rescalinterval=00:01:00>, <Folder id=default path=\\?\C:\Users\Jonathan\Sync devices=[<Device deviceId=DQ4LQZO-TCFTTP5-CSXNTWJ-Z5F4GWH-7KNHE3K-CPBGZIX-7D3SMV2-CYMHQAO>, <Device deviceId=PFTGPAK-ZCABA45-UAVXPM4-PNJ5QN5-UYZS66C-Y2KPDDJ-S44MK5X-34SFPQ2>, <Device deviceId=POWFPEW-KHKNTI5-SVL3YME-JGSSIJF-GITYTRL-2XV72WE-6ZTOLG2-PCMJEAG>] readonly=False rescalinterval=00:01:00>, <Folder id=engineering_documents path=\\?\C:\Users\Jonathan\Documents\Engineering documents devices=[<Device deviceId=DQ4LQZO-TCFTTP5-CSXNTWJ-Z5F4GWH-7KNHE3K-CPBGZIX-7D3SMV2-CYMHQAO>, <Device deviceId=PFTGPAK-ZCABA45-UAVXPM4-PNJ5QN5-UYZS66C-Y2KPDDJ-S44MK5X-34SFPQ2>, <Device deviceId=POWFPEW-KHKNTI5-SVL3YME-JGSSIJF-GITYTRL-2XV72WE-6ZTOLG2-PCMJEAG>] readonly=False rescalinterval=00:01:00>] devices=[<Device id=BTDQGY6-VHG7TTI-NXXTH5M-SSCWKZ2-XTHK6SX-T4GGD5V-INUCZ3C-IIFMAQW name=Samsung Relay addresses=[dynamic] compression=N/A certname= isintroducer=False>, <Device id=DQ4LQZO-TCFTTP5-CSXNTWJ-Z5F4GWH-7KNHE3K-CPBGZIX-7D3SMV2-CYMHQAO name=THINKPAD addresses=[dynamic] compression=N/A certname= isintroducer=False>, <Device id=DQ4LQZO-TCFTTP5-CSXNTWJ-Z5F4GWH-7KNHE3K-CPBGZIX-7D3SMV2-CYMHQAO name=THINKPAD addresses=[dynamic] compression=N/A certname= isintroducer=False>, <Device id=PFTGPAK-ZCABA45-UAVXPM4-PNJ5QN5-UYZS66C-Y2KPDDJ-S44MK5X-34SFPQ2 name=Work HP addresses=[dynamic] compression=N/A certname= isintroducer=False>, <Device id=POWFPEW-KHKNTI5-SVL3YME-JGSSIJF-GITYTRL-2XV72WE-6ZTOLG2-PCMJEAG name=Optiplex addresses=[optiplex, dynamic] compression=N/A certname= isintroducer=False>]> 
2015-04-21 07:50:31.4288 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClient: Fetched system info: <SystemInfo alloc=22008744 cpuPercent=8.533907 goroutines=27 myId=DQ4LQZO-TCFTTP5-CSXNTWJ-Z5F4GWH-7KNHE3K-CPBGZIX-7D3SMV2-CYMHQAO pathSeparator=\ sys=33253624 tilde=C:\Users\Jonathan> 
2015-04-21 07:50:31.4288 [Debug] SyncTrayzor.SyncThing.ApiClient.SyncThingApiClient: Fetched version: <Version arch=amd64 longVersion=syncthing v0.10.30 (go1.4.2 windows-amd64 default) unknown-user@syncthing-builder 2015-03-29 07:46:44 UTC os=windows version=v0.10.30> 
2015-04-21 07:50:31.4288 [Error] SyncTrayzor.SyncThing.SyncThingManager: Error starting Syncthing API System.ArgumentException The source argument contains duplicate keys. Void InitializeFromCollection(System.Collections.Generic.IEnumerable`1[System.Collections.Generic.KeyValuePair`2[TKey,TValue]])    at System.Collections.Concurrent.ConcurrentDictionary`2.InitializeFromCollection(IEnumerable`1 collection)
   at System.Collections.Concurrent.ConcurrentDictionary`2..ctor(IEnumerable`1 collection)
   at SyncTrayzor.SyncThing.SyncThingManager.<LoadStartupDataAsync>d__48.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 426
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__27.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 304 System.ArgumentException: The source argument contains duplicate keys.
   at System.Collections.Concurrent.ConcurrentDictionary`2.InitializeFromCollection(IEnumerable`1 collection)
   at System.Collections.Concurrent.ConcurrentDictionary`2..ctor(IEnumerable`1 collection)
   at SyncTrayzor.SyncThing.SyncThingManager.<LoadStartupDataAsync>d__48.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 426
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__27.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 304
2015-04-21 07:50:31.4548 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Killing Syncthing process 
2015-04-21 07:50:31.4548 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Running -> Stopped 
2015-04-21 07:50:31.4548 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Setting state: Running -> Stopped 
2015-04-21 07:50:31.4548 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Aborting API clients 
2015-04-21 07:50:31.4548 [Info] SyncTrayzor.SyncThing.SyncThingProcessRunner: Syncthing process stopped with exit status Success 
2015-04-21 07:50:31.4698 [Debug] SyncTrayzor.SyncThing.SyncThingManager: Request to set state: Stopped -> Stopped 
2015-04-21 07:50:31.4698 [Error] SyncTrayzor.Bootstrapper: An unhandled exception occurred System.ArgumentException The source argument contains duplicate keys. Void InitializeFromCollection(System.Collections.Generic.IEnumerable`1[System.Collections.Generic.KeyValuePair`2[TKey,TValue]])    at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__27.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 323
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__14.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ViewerViewModel.<Start>d__d.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Pages\ViewerViewModel.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler) System.ArgumentException: The source argument contains duplicate keys.
   at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__27.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 323
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__14.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ViewerViewModel.<Start>d__d.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Pages\ViewerViewModel.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by canton7** [comment]
Aha, not folders, but devices. Let me ask the Syncthing devs, see if that's expected.

**Comment by canton7** [comment]
As a short-term fix, edit Syncthing's config.xml (will probably be in `C:\Users\<You>\AppData\Local\Syncthing\config.xml`, find the `<device>...</device>` items (where each one has an `<address>` tag inside it), and look for devices which have the same ID. You appear to have the device 'THINKPAD' twice.

**Comment by endolith** [comment]
Removing the duplicate fixed it, thanks.  This *is* THINKPAD, for the record.  It's supposed to have an entry for itself?

**Comment by canton7** [comment]
No, you're not supposed to have a reference to your current device - trying to sync with yourself isn't recommended (although it may work - I think there was a thread on the forums about this?)

**Comment by endolith** [comment]
Well I didn't put it there. :)

**Comment by canton7** [comment]
Are you sure? Even using the web GUI?

**Comment by canton7** [comment]
If Syncthing's added devices without your say-so, then that's a Syncthing bug and probably wants raising with them.

**Comment by endolith** [comment]
All 3 of my computers have <device> entries for themselves in config.xml, are you sure that's a bug?  Only one had duplicate entries, though.

**Comment by canton7** [comment]
Let me ask...

**Comment by canton7** [comment]
Apparently it's fine :smile: I was apparently mis-remembering, apologies.

**Comment by endolith** [comment]
:+1:

**Comment by canton7** [comment]
Cool. I've got a commit that will be in the next release to stop SyncTrayzor crashing in this case anyway - I'll close off the issue when that's released. Thanks for your help!
