### ISSUE TITLE
1.1.27 Crashing when opening GUI

### ISSUE THREAD

**Issue by ChristianB011** [canton7/SyncTrayzor#618]
SyncTrayzor seems to start fine with my computer for background sync, but when I try to open it it immediately crashes with the following message.  It also crashes when trying to restart it from the Start Menu.

Version: 1.1.27.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: CefSettings.BrowserSubprocessPath not found.
File name: 'C:\Program Files\SyncTrayzor\CefSharp.BrowserSubprocess.exe'
   at CefSharp.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Can you check whether `C:\Program Files\SyncTrayzor\CefSharp.BrowserSubprocess.exe` exists? My guess is that your AV might have taken a dislike to it

**Comment by ChristianB011** [comment]
I checked to see if that file was actually missing, and it does appear to be.  After verifying that, I grabbed a copy of the latest installer and ran it again (previously I updated from an older version through SyncTrayzor).  After running the installer, everything seems to be working again.

I do think that I was able to open the GUI after initially running the update, so I'm not sure if there was some kind of issue with my PC not properly shutting down that could have caused this issue.  There is nothing in my Antivirus logs to indicate that it removed that file, but I will keep an eye out for that going forward.

**Comment by canton7** [comment]
The installer shouldn't have removed that file, and SyncTrayzor itself doesn't have permission to, so I suspect it was probably something post-installation as well. I suspected AV because they tend not to like that file for some reason.

Glad you managed to get it solved, thanks for letting me know
