### ISSUE TITLE
Synctrayzor crashed and will not start up again

### ISSUE THREAD

**Issue by JensChrG** [canton7/SyncTrayzor#620]
Synctrayzor crashed today, the first time I tried opening the window by clicking the tray icon.
Message:
```
Version: 1.1.27.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: CefSettings.BrowserSubprocessPath not found.
File name: 'C:\Program Files\SyncTrayzor\CefSharp.BrowserSubprocess.exe'
   at CefSharp.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at SyncTrayzor.Pages.ShellViewModel.EnsureInForeground()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Stylet.Xaml.ActionBase.InvokeTargetMethod(Object[] parameters)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
SyncTrayzor.log and syncthing.log are from the initial crash.

After that the program crashes immediately if I try to start it manually (from the start menu).
Message: 
```
Version: 1.1.27.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: CefSettings.BrowserSubprocessPath not found.
File name: 'C:\Program Files\SyncTrayzor\CefSharp.BrowserSubprocess.exe'
   at CefSharp.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
SyncTrayzor - second time.log is from trying to start it manually.
syncthing.log was not updated.

[SyncTrayzor.log](https://github.com/canton7/SyncTrayzor/files/5924362/SyncTrayzor.log)
[syncthing.log](https://github.com/canton7/SyncTrayzor/files/5924363/syncthing.log)
[SyncTrayzor - second time.log](https://github.com/canton7/SyncTrayzor/files/5924389/SyncTrayzor.-.second.time.log)

**Comment by canton7** [comment]
Please see #618

**Comment by JensChrG** [comment]
Yes, that is the same issue.
I am sorry for the duplicate, I only checked open issues...

My AV claims that it has not removed the file so I do not know how the file may have been deleted, but a reinstall fixed it anyway.
