### ISSUE TITLE
Tried uninstalling but it didn't fully uninstall. Wanted to reinstall and found a fatal bug.

### ISSUE THREAD

**Issue by ZeekaBobIs** [canton7/SyncTrayzor#622]
```
Version: 1.1.27.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.ArgumentException: Item has already been added. Key in dictionary: 'Path'  Key being added: 'PATH'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()
   at SyncTrayzor.Syncthing.SyncthingProcessRunner.StartInternal(Boolean isRestart)
   at SyncTrayzor.Syncthing.SyncthingManager.<StartAsync>d__118.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
[SyncTrayzor.log](https://download1641.mediafire.com/rh5n259gkwug/1kgoigaauovjtac/SyncTrayzor.log)

EDIT: Just realized that launching the app a second time didn't return the same error. Not sure if this is a fluke, not sure if I should close the issue. Feel free to close it for me if it needs to be closed.

**Comment by canton7** [comment]
I've seen this reported before when you've got two environmental variables with the same name but different casing. So you think that's something which could have happened here?

**Comment by canton7** [comment]
Closing as no response
