### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [canton7/SyncTrayzor#637]
I don't know what was happening when it crashed. I stepped away from my PC and came back to find not one but _two_ of the "Oops! Something went terribly wrong" (or however it's worded). Once I copied the contents to the clipboard and pasted it on this issue, clicking Close caused both of the "Oops!" windows to disappear so I didn't get a chance to compare the details below with the other "Oops!" window.

Version: 1.1.28.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at SyncTrayzor.Bootstrapper.OnUnhandledException(DispatcherUnhandledExceptionEventArgs e)
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
It looks like your genuinely ran out of memory I'm afraid. The error you posted occurred when it ran out of memory trying to show a previous error by the looks of it -- so the out-of-memory presumably happened twice in quick succession.
