### ISSUE TITLE
SyncTrayzor crashes on start-up Windows 10

### ISSUE THREAD

**Issue by GraemeKPeters** [canton7/SyncTrayzor#648]
Here's the generated information:

Version: 1.1.28.0; Variant: Portable; Arch: Amd64
Path: C:\Program Files\SyncTrayzorPortable-x64\SyncTrayzor.exe
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\SyncTrayzorPortable-x64\data\config.xml.tmp' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at SyncTrayzor.Utils.AtomicFileStream..ctor(String path, String tempPath) in C:\projects\synctrayzor\src\SyncTrayzor\Utils\AtomicFileStream.cs:line 20
   at SyncTrayzor.Services.FilesystemProvider.CreateAtomic(String path) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 47
   at SyncTrayzor.Services.Config.ConfigurationProvider.SaveToFile(Configuration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 421
   at SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration, Boolean& hadToCreate) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 191
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 99
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 147
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
It looks like you took the portable variant, and put it in Program Files.

If you want a version in Program Files, use the installer. If you want to use the portable version, it needs to be put somewhere that it has permission to write to.
