### ISSUE TITLE
1.1.28.0 Crashes immediately on open after installing 

### ISSUE THREAD

**Issue by andronocean** [canton7/SyncTrayzor#653]
Here's the error message. 

```
Version: 1.1.28.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.Management.ManagementException: Generic failure 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at SyncTrayzor.Services.GraphicsCardDetector.GetIsIntelXe()
   at SyncTrayzor.Services.GraphicsCardDetector.get_IsIntelXe()
   at SyncTrayzor.Pages.BarAlerts.BarAlertsViewModel.Load()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

(Possibly relevant: I did have SyncTrayzor installed on this machine previously, but uninstalled it and a bunch of other things as part of a debugging process. Not sure what version it was at when I did so... several months back.)

**Comment by andronocean** [comment]
Just tried the portable version, getting what looks like the same error there too:

```
Version: 1.1.28.0; Variant: Portable; Arch: Amd64
Path: C:\Users\Andron\Apps\SyncTrayzorPortable\SyncTrayzorPortable-x64\SyncTrayzor.exe
System.Management.ManagementException: Generic failure 
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at SyncTrayzor.Services.GraphicsCardDetector.GetIsIntelXe() in C:\projects\synctrayzor\src\SyncTrayzor\Services\GraphicsCardDetector.cs:line 25
   at SyncTrayzor.Services.GraphicsCardDetector.get_IsIntelXe() in C:\projects\synctrayzor\src\SyncTrayzor\Services\GraphicsCardDetector.cs:line 17
   at SyncTrayzor.Pages.BarAlerts.BarAlertsViewModel.Load() in C:\projects\synctrayzor\src\SyncTrayzor\Pages\BarAlerts\BarAlertsViewModel.cs:line 84
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by andronocean** [comment]
Aha! I just tried installing 1.1.27 instead (normal version, not portable). That worked perfectly, no errors, the tray is live, and syncthing launches properly. 🥳 

I'm going to close this since my problem is solved, but if you need any followup info feel free to ask me.
