### ISSUE TITLE
Oops! Something Went Badly Wrong error

### ISSUE THREAD

**Issue by csatech** [canton7/SyncTrayzor#665]
Here are the error details:

Version: 1.1.29.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.UnauthorizedAccessException: Access is denied.

   at Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   at SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to)
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration)
   at SyncTrayzor.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by wbwc** [comment]
The same here:

Version: 1.1.29.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.UnauthorizedAccessException: Zugriff verweigert

   bei Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   bei SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to)
   bei SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration)
   bei SyncTrayzor.Bootstrapper.Configure()
   bei Stylet.BootstrapperBase.Start(String[] args)
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
