### ISSUE TITLE
Problems parsing network adapter name

### ISSUE THREAD

**Issue by cristihcd** [canton7/SyncTrayzor#675]
Hello,

Using synctrayzor v.1.1.28, syncthing v1.18.5 on Windows 10. 
Zerotier One is installed, which creates network adapters named like: `ZeroTier One [xxxxxxxxxxxxxxx]` -- 16 characters representing network id.

The error is:

```
2021-12-13 09:38:09.2917 #13820 [Error] SyncTrayzor.Bootstrapper: An unhandled AppDomain exception occurred. Terminating: True System.FormatException Unable to parse input '169.254.254.234%ZeroTier One [6xxxxxxxxxxxxxx]:22000' into a URI System.Net.IPEndPoint Parse(System.String)    at SyncTrayzor.Syncthing.Devices.SyncthingAddressParser.Parse(String input)
   at SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<>c__DisplayClass27_0.<FetchDevicesAsync>b__1(ConfigDevice device)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<ReloadDevicesAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadConfigDataAsync>d__135.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<ReloadConfigDataAsync>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() System.FormatException: Unable to parse input '169.254.254.234%ZeroTier One [6fae0299f6f8ccb8]:22000' into a URI
   at SyncTrayzor.Syncthing.Devices.SyncthingAddressParser.Parse(String input)
   at SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<>c__DisplayClass27_0.<FetchDevicesAsync>b__1(ConfigDevice device)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager.<ReloadDevicesAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<LoadConfigDataAsync>d__135.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Syncthing.SyncthingManager.<ReloadConfigDataAsync>d__136.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by cristihcd** [comment]
The specific error is:

Terminating: True System.FormatException Unable to parse input '169.254.254.234%ZeroTier One [xxxxxxxxxxxxxxx]:22000' into a URI System.Net.IPEndPoint Parse(System.String)    at SyncTrayzor.Syncthing.Devices.SyncthingAddressParser.Parse(String input)
