### ISSUE TITLE
Not Sure What's Hapenning. 

### ISSUE THREAD

**Issue by MasterLive013** [canton7/SyncTrayzor#682]
I get this:

> Version: 1.1.29.0; Variant: Portable; Arch: Amd64
> Path: C:\Program Files\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\SyncTrayzor.exe
> System.UnauthorizedAccessException: Access to the path 'C:\Program Files\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\config.xml.tmp' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at SyncTrayzor.Utils.AtomicFileStream..ctor(String path, String tempPath) in C:\projects\synctrayzor\src\SyncTrayzor\Utils\AtomicFileStream.cs:line 20
>    at SyncTrayzor.Services.FilesystemProvider.CreateAtomic(String path) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 47
>    at SyncTrayzor.Services.Config.ConfigurationProvider.SaveToFile(Configuration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 421
>    at SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration, Boolean& hadToCreate) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 191
>    at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 99
>    at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 168
>    at Stylet.BootstrapperBase.Start(String[] args)
>    at System.Windows.Application.OnStartup(StartupEventArgs e)
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Please help.

**Comment by MasterLive013** [comment]
Think I solved it, please close the thread.
