### ISSUE TITLE
Error msg when opening synctrayzor on Windows 11 machine

### ISSUE THREAD

**Issue by grosbald** [canton7/SyncTrayzor#685]
Hi, 

Get this message on a windows 11 laptop when trying to open Synctrayzor. Any advice most welcome

Version: 1.1.29.0; Variant: Installed; Arch: X86
Path: C:\Program Files (x86)\SyncTrayzor\SyncTrayzor.exe
System.UnauthorizedAccessException: Access is denied.

   at Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   at SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to)
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration)
   at SyncTrayzor.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
You appear to not have write access to `%APPDATA%\SyncTrayzor`?

**Comment by grosbald** [comment]
Ok, thank you. Not being that IT literate how would that happen with an Microsoft update or a user meddling?

tks

**Comment by rlad78** [comment]
@grosbald did you try changing something in the SyncTrayzor settings before you got this error? I tried changing Syncthing -> Advanced -> Syncthing Custom Path and got the same error. I went through the logs and found this, which made me realized I only specified the directory, not the file path:

```
2022-05-12 19:52:44.0704 #5820 [Warn] SyncTrayzor.Services.Config.ConfigurationProvider: Syncthing doesn't exist at C:\Users\username\OneDrive\Software\syncthing-windows-amd64-v1.20.1, so copying from C:\Program Files\SyncTrayzor\syncthing.exe
```

If you need to change some setting, you can do so in `%APPDATA%\SyncTrayzor\config.xml` as long as you know what you need to change.
