### ISSUE TITLE
oops smt went badly wrong

### ISSUE THREAD

**Issue by Zixim** [canton7/SyncTrayzor#69]
on starting synctrayzor i got the following : 

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8384
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at SyncTrayzor.SyncThing.SyncThingManager.<StartClientAsync>d__27.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 323
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingManager.<StartAsync>d__14.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingManager.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Utils.SafeSyncthingExtensions.<StartWithErrorDialogAsync>d__0.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Utils\SafeSyncthingExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.Pages.ShellViewModel.<Start>d__10.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\Pages\ShellViewModel.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
```

help?

**Comment by canton7** [comment]
Mind posting your log? You'll find it in `C:\Users\<You>\AppData\Roaming\SyncTrayzor\logs\SyncTrayzor.log` for the installed version, or `data\logs\SyncTrayzor.log` for the installed version. Thanks!

**Comment by Zixim** [comment]
http://pastebin.com/DLZcGh3w

also, https://forum.syncthing.net/t/panic-leveldb-table-corruption-on-data-block/2526/1

**Comment by canton7** [comment]
Aha - I saw the forum post, but didn't draw the link between that and this.

Syncthing is crashing out (as per the panic), and SyncTrayzor is failing to connect to it. Granted, we should be handling this better and not crashing! I'll get a fix in.

**Comment by Zixim** [comment]
and the root of the panic is a corrupt .ldb file, right?
I've removed the ldb file...we'll see what happens next.

**Comment by AudriusButkevicius** [comment]
You have to remove the whole database, removing one file will not solve it.

**Comment by canton7** [comment]
OK, so Syncthing crashed out after we'd first established communications with it. That's an error case which we don't currently handle, so the fix for this will become part of that.

**Comment by canton7** [comment]
Apparently I fixed this a while back, but didn't close this issue off.
