### ISSUE TITLE
After update synctrazor does not start in W10, before was working ok for years....

### ISSUE THREAD

**Issue by EdgardoVUrquiza** [canton7/SyncTrayzor#692]
Error   ooops!  something went badly wrong

Version: 1.1.28.0; Variant: Installed; Arch: X86
Path: C:\Program Files (x86)\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: CefSettings.BrowserSubprocessPath not found.
File name: 'C:\Program Files (x86)\SyncTrayzor\CefSharp.BrowserSubprocess.exe'
   at CefSharp.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   at CefSharp.Cef.Initialize(CefSettingsBase cefSettings)
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.Screen.Stylet.IScreenState.Activate()
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<>c__DisplayClass35_0.<Stylet.IScreenState.Activate>b__1()
   at Stylet.Execute.OnUIThread(Action action)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.Screen.Stylet.IScreenState.Activate()
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.DisplayRootView(Object rootViewModel)
   at Stylet.Bootstrapper`1.Launch()
   at SyncTrayzor.Bootstrapper.Launch()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by EdgardoVUrquiza** [comment]
IT WAS SOLVED   adding folowing command line flag:
-allow-newer-config
in advanced settings
