### ISSUE TITLE
ObjectDisposedException in SyncThingConnectionsWatcher

### ISSUE THREAD

**Issue by HermanEldering** [canton7/SyncTrayzor#70]
This one popped up. Perhaps because my laptop went to sleep.

System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.Stream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Refit.RequestBuilderImplementation.<>c__DisplayClass28`1.<<buildCancellableTaskFuncForMethod>b__27>d__2a.MoveNext() in y:\code\paulcbetts\refit\Refit\RequestBuilderImplementation.cs:line 236
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingConnectionsWatcher.<PollAsync>d__6.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingConnectionsWatcher.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.SyncThing.SyncThingPoller.<Start>d__2.MoveNext() in c:\Documents\projects\SyncTrayzor\src\SyncTrayzor\SyncThing\SyncThingPoller.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
Oh, fun. Looks like the library I'm using to make web requests to Syncthing has an issue or two. I'm about to replace it, which should have the side effect of side-stepping whatever is causing this.
