### ISSUE TITLE
Avast antivirus blocked execution

### ISSUE THREAD

**Issue by Colin2791** [canton7/SyncTrayzor#717]
Avast claimed that the SyncThing has a virus inside and quarantined the app.
Now the app show this error:
Version: 1.1.29.0; Variant: Installed; Arch: X86
Path: C:\Program Files (x86)\SyncTrayzor\SyncTrayzor.exe
System.UnauthorizedAccessException: Access is denied.

   at Pri.LongPath.File.Copy(String sourcePath, String destinationPath, Boolean overwrite)
   at SyncTrayzor.Services.FilesystemProvider.Copy(String from, String to)
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration)
   at SyncTrayzor.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at Stylet.BootstrapperBase.<Setup>b__9_0(Object o, StartupEventArgs e)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by canton7** [comment]
There's not a lot I can do about your AV I'm afraid. Tell it to restore the things it deleted. If you can't, you might have to run the installer again.

**Comment by Colin2791** [comment]
It says has Win32.Magic.WooDoo-C inside.

**Comment by canton7** [comment]
Not a lot I can do about that: AVs randomly decide that various bits of SyncTrayzor have something wrong with them (it's normally the embedded browser). This version had been out for months.

You'll have to tell it to live with SyncTrayzor.

**Comment by Colin2791** [comment]
OK. Thanks!
