### ISSUE TITLE
Synctrazor Crashed

### ISSUE THREAD

**Issue by Ethan7** [canton7/SyncTrayzor#722]
Log:
"Version: 1.1.28.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: CefSettings.BrowserSubprocessPath not found.
File name: 'C:\Program Files\SyncTrayzor\CefSharp.BrowserSubprocess.exe'
   at CefSharp.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
"

It crashes consistently, I'm unable to open it.

**Comment by Proto92356** [comment]
I started getting this exact same error a few days ago - not sure exactly when it started.  Did an automatic update trigger this?

Version: 1.1.28.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
System.IO.FileNotFoundException: CefSettings.BrowserSubprocessPath not found.
File name: 'C:\Program Files\SyncTrayzor\CefSharp.BrowserSubprocess.exe'
   at CefSharp.Cef.Initialize(CefSettingsBase cefSettings, Boolean performDependencyCheck, IApp cefApp)
   at SyncTrayzor.Pages.ViewerViewModel.OnInitialActivate()
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.<>c__DisplayClass4_0.<ActivateWith>b__0(Object o, ActivationEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Stylet.Screen.<Stylet.IScreenState.Activate>b__35_0(ScreenState oldState, ScreenState newState)
   at Stylet.Screen.SetState(ScreenState newState, Action`2 changedHandler)
   at Stylet.ScreenExtensions.TryActivate(Object screen)
   at Stylet.WindowManager.WindowConductor..ctor(Window window, Object viewModel)
   at Stylet.WindowManager.CreateWindow(Object viewModel, Boolean isDialog, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at SyncTrayzor.Pages.ShellViewModel.EnsureInForeground()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Stylet.Xaml.ActionBase.InvokeTargetMethod(Object[] parameters)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by emendoza2** [comment]
I am not sure if this issue is related, but I experience a crash after a few seconds of SyncTrayzor being launched. After the crash happens, the executable for SyncTrayzor is gone. Could it be an antivirus issue? I am using Avast if that helps.
