### ISSUE TITLE
Crash On Initial Install

### ISSUE THREAD

**Issue by davidlspeed** [canton7/SyncTrayzor#767]
Installing this on the 5th box here (2 Win, 1 Pi, 1 Android) and ran into a problem on the 3rd Win

Downloaded, unzipped and moved resulting folder to C:/ProgramFiles

Tried to install 3x, by double clicking on SyncTrayzor.exe; same thing each time.  No uninstall option available, so I followed instructions.  I *had* left the install folder under Downloads on the other 2 Win installs, but that was kinda messy - the only diff I can see.  Maybe it doesn't like the way Windoze locked down that directory?

HW
Fairly recent system (LT 3 yrs); kept cleanish and updated
msi z-390 mobo
Intel i5-9600
@3.7gmsi z390
16 GB ram
250gb m2 ssd; ~50% used
2TB spinners mirrored; ~10% used
OS
win10 pro 64
version: 22H2
build: 19045.2364
exp: Windows Feature Experience Pack 120.2212.4190.0

from the window shown after crash:

Version: 1.1.29.0; Variant: Portable; Arch: Amd64
Path: C:\Program Files\SyncTrayzorPortable-x64\SyncTrayzor.exe
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\SyncTrayzorPortable-x64\data\config.xml.tmp' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at SyncTrayzor.Utils.AtomicFileStream..ctor(String path, String tempPath) in C:\projects\synctrayzor\src\SyncTrayzor\Utils\AtomicFileStream.cs:line 20
   at SyncTrayzor.Services.FilesystemProvider.CreateAtomic(String path) in C:\projects\synctrayzor\src\SyncTrayzor\Services\FilesystemProvider.cs:line 47
   at SyncTrayzor.Services.Config.ConfigurationProvider.SaveToFile(Configuration config) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 421
   at SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration, Boolean& hadToCreate) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 191
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in C:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 99
   at SyncTrayzor.Bootstrapper.Configure() in C:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 168
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

log file:

2023-05-20 10:33:27.3579 #10508 [Info] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.29.0 (Amd64) started at C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\SyncTrayzor.exe (.NET version: Unknown (528372)) 
2023-05-20 10:33:27.3891 #10508 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\logs 
2023-05-20 10:33:27.4047 #10508 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingBackupPath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\syncthing.exe 
2023-05-20 10:33:27.4047 #10508 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\config.xml 
2023-05-20 10:33:27.4047 #10508 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\config-backups 
2023-05-20 10:33:27.4047 #10508 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\cef\cache 
2023-05-20 10:33:27.4047 #10508 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingPath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\syncthing.exe 
2023-05-20 10:33:27.4047 #10508 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingHomePath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\syncthing 
2023-05-20 10:33:27.4047 #10508 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Checking for other SyncTrayzor processes 
2023-05-20 10:33:27.4047 #10508 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Did not find any other processes, or they all responded with an error 
2023-05-20 10:33:27.4204 #10508 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowDeviceConnectivityBalloons=False ShowDeviceOrFolderRejectedBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingCommandLineFlags=[] SyncthingEnvironmentalVariables=[] SyncthingDenyUpgrade=False SyncthingPriorityLevel=Normal Folders=[] NotifyOfNewVersions=True LatestNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingCustomPath= SyncthingCustomHomePath= ShowSynchronizedBalloonEvenIfNothingDownloaded=False DisableHardwareRendering=False HideIntelXeWarningMessage=False EnableFailedTransferAlerts=True EnableConflictFileMonitoring=True ConflictResolverDeletesToRecycleBin=True PauseDevicesOnMeteredNetworks=True HaveDonated=False IconAnimationMode=DataTransferring OpenFolderCommand=explorer.exe "{0}" ShowFileInFolderCommand=explorer.exe /select, "{0}"LogLevel=Info> 
2023-05-20 10:33:27.4360 #10508 [Info] SyncTrayzor.Services.Config.ConfigurationProvider: Configuration file C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\config.xml doesn't exist, so creating 
2023-05-20 10:33:27.4360 #10508 [Warn] SyncTrayzor.Services.Config.ConfigurationProvider: Syncthing doesn't exist at C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\syncthing.exe, so copying from C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\syncthing.exe 
2023-05-20 10:33:27.4738 #10508 [Debug] SyncTrayzor.Services.AutostartProvider: Have read/write access to the registry 
2023-05-20 10:33:27.7588 #10508 [Debug] SyncTrayzor.Services.Conflicts.ConflictFileWatcher: Refreshing conflicted files. Found 0 from 0 options 
2023-05-20 10:33:28.2380 #10508 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\syncthing.exe 
2023-05-20 10:33:28.7929 #10508 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
2023-05-20 10:33:30.5538 #10508 [Info] SyncTrayzor.Syncthing.SyncthingProcessRunner: Starting syncthing: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\syncthing.exe 
2023-05-20 10:38:27.7780 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 8MiB 
2023-05-20 10:38:28.1569 #10508 [Info] SyncTrayzor.Services.UpdateManagement.UpdateChecker: No updates available 
2023-05-20 10:43:27.8072 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 8MiB 
2023-05-20 10:48:27.8164 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 8MiB 
2023-05-20 10:53:27.8420 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 8MiB 
2023-05-20 10:58:27.8469 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 8MiB 
2023-05-20 11:03:27.8547 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:07:45.6556 #10508 [Warn] SyncTrayzor.Syncthing.Devices.SyncthingDeviceManager: Unexpected device connected: KDVYNEY-TK7YOIR-76FVI3T-POZ3GNP-6NFWH6D-3AZ6WJR-UMOY57V-HMENYAE, address 192.168.1.131:22000. It wasn't fetched when we fetched our config 
2023-05-20 11:07:55.9283 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:07:55.9283 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:08:25.5794 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:12:13.2698 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:12:13.2698 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:13:25.5867 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:18:25.6052 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:23:25.6230 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:27:08.3665 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-waiting. Defaulting to Idle 
2023-05-20 11:27:08.3753 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 11:27:08.3753 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-waiting. Defaulting to Idle 
2023-05-20 11:27:08.3903 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 11:27:12.5126 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 11:27:12.5126 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 11:27:18.3801 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:27:18.3801 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:27:37.0641 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-waiting. Defaulting to Idle 
2023-05-20 11:27:37.0641 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 11:27:37.0641 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-waiting. Defaulting to Idle 
2023-05-20 11:27:37.0641 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 11:27:37.1868 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 11:27:37.1868 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 11:28:25.6316 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:30:04.8073 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:30:04.8073 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:33:25.6386 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:38:25.6458 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:43:25.6364 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:48:25.6644 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:49:20.2081 #1244 [Info] SyncTrayzor.Bootstrapper: SyncTrazor version 1.1.29.0 (Amd64) started at C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\SyncTrayzor.exe (.NET version: Unknown (528372)) 
2023-05-20 11:49:20.2550 #1244 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\logs 
2023-05-20 11:49:20.2550 #1244 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncthingBackupPath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\syncthing.exe 
2023-05-20 11:49:20.2550 #1244 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\config.xml 
2023-05-20 11:49:20.2550 #1244 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\config-backups 
2023-05-20 11:49:20.2550 #1244 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\cef\cache 
2023-05-20 11:49:20.2550 #1244 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingPath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\syncthing.exe 
2023-05-20 11:49:20.2550 #1244 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: DefaultSyncthingHomePath: C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\data\syncthing 
2023-05-20 11:49:20.2550 #1244 [Debug] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Checking for other SyncTrayzor processes 
2023-05-20 11:49:20.2550 #1244 [Info] SyncTrayzor.Services.Ipc.IpcCommsClientFactory: Found process with ID 10508 and location C:\Users\Dave\Documents\Downloads\SyncTrayzorPortable-x64\SyncTrayzorPortable-x64\SyncTrayzor.exe 
2023-05-20 11:51:20.4723 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:51:20.4723 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:53:25.6819 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:53:45.2063 #10508 [Warn] SyncTrayzor.Services.Metering.MeteredNetworkManager: Unable to fetch device state for device ID GI6RZXC-T7PMUQW-7OMONLZ-GVFIVUP-FLJITKL-GQ5RPFP-VDSAS7O-MR6MMAK. This should not happen. 
2023-05-20 11:56:38.9072 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:56:38.9072 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 11:58:25.6867 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 11:59:48.8710 #10508 [Warn] SyncTrayzor.Services.Metering.MeteredNetworkManager: Unable to fetch device state for device ID GI6RZXC-T7PMUQW-7OMONLZ-GVFIVUP-FLJITKL-GQ5RPFP-VDSAS7O-MR6MMAK. This should not happen. 
2023-05-20 12:03:25.6816 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 12:08:25.7055 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 12:13:25.7172 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 12:18:25.7204 #10508 [Info] SyncTrayzor.Services.MemoryUsageLogger: Working Set: 177MiB. Private Memory Size: 127MiB. GC Total Memory: 9MiB 
2023-05-20 12:20:15.3312 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 12:20:15.3312 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state scan-waiting. Defaulting to Idle 
2023-05-20 12:20:36.2686 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-waiting. Defaulting to Idle 
2023-05-20 12:20:36.2686 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 12:20:36.2686 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-waiting. Defaulting to Idle 
2023-05-20 12:20:36.2686 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 12:20:36.2864 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle 
2023-05-20 12:20:36.2864 #10508 [Warn] SyncTrayzor.Syncthing.Folders.FolderStateTransformer: Unknown folder sync state sync-preparing. Defaulting to Idle

**Comment by tomasz1986** [comment]
You are trying to use the portable version inside Program Files. That's not how things are supposed to be done 😉. If you want to use the portable version, you should put it in a location where no Admin access is required (e.g. Desktop). On the other hand, if you do want to have the program located inside Program Files, then you should delete the the folders you copied there manually and just use the normal installer to install the program (i.e. `SyncTrayzorSetup-x64.exe` instead of `SyncTrayzorPortable-x64.zip`).
