### ISSUE TITLE
SyncTrayzor crashes at start

### ISSUE THREAD

**Issue by ilyaradko** [canton7/SyncTrayzor#786]
Upon start it gives the following error: "Oops! Something wend badly wrong" and the following log output:

`Version: 1.1.29.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\Net\SyncTrayzor\SyncTrayzor.exe
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.IsPathRooted(String path)
   at SyncTrayzor.Services.PathTransformer.MakeAbsolute(String input)
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration)
   at SyncTrayzor.Bootstrapper.Configure()
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by ilyaradko** [comment]
Ok, I seemed to find the reason. I set the "Syncthing Custom Path" in settings. And since it was in the "Program Files" folder (with a spacebar), I included the path in double quotes, as is normally done when path contains a space. And the quotes where causing the "Illegal character in path" error. I had to manually edit the config.xml file to remove the quotes.

It's probably worth doing syntax check for the fields in the settings.
