### ISSUE TITLE
Didn't start

### ISSUE THREAD

**Issue by Brianpals** [canton7/SyncTrayzor#799]
An error showed while opening Synctrayzor and I was told to show the following information (obviously I don't know what it means but I'm sure someone out there does). Also, because it won't open and because I'm not used to all this, I can't seem to find the two versions that you require in the contributing guidelines:
 
"Version: 1.1.29.0; Variant: Installed; Arch: Amd64
Path: C:\Program Files\SyncTrayzor\SyncTrayzor.exe
RestEase.ApiException: POST "https://localhost:8384/rest/db/scan" failed because response status code does not indicate success: 500 (Internal Server Error).
   at RestEase.Implementation.Requester.<SendRequestAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RestEase.Implementation.Requester.<RequestVoidAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SyncTrayzor.NotifyIcon.NotifyIconViewModel.<RescanAll>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"

**Comment by Brianpals** [comment]
Yes, this is working now.
