### ISSUE TITLE
Crash after update to latest release

### ISSUE THREAD

**Issue by padraigkitterick** [canton7/SyncTrayzor#96]
I got a prompt to install the latest release today (x64 windows). Clicked the update button and then after the install completed, and everytime I then attempted to run it I got the following stack trace:

System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at SyncTrayzor.Services.Config.ConfigurationProvider.LoadFromDisk(Configuration defaultConfiguration) in c:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 145
   at SyncTrayzor.Services.Config.ConfigurationProvider.Initialize(Configuration defaultConfiguration) in c:\projects\synctrayzor\src\SyncTrayzor\Services\Config\ConfigurationProvider.cs:line 85
   at SyncTrayzor.Bootstrapper.Configure() in c:\projects\synctrayzor\src\SyncTrayzor\Bootstrapper.cs:line 85
   at Stylet.BootstrapperBase.Start(String[] args)
   at System.Windows.Application.<.ctor>b__1(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

I then downloaded 1.0.21 manually (x64 windows installer) and completed the install which went OK. Tried to run it and got the identical stack trace.

The relevant bit of the log file for the auto-update is as follows:

2015-05-29 14:41:49.4802 [Info] SyncTrayzor.Services.UpdateManagement.UpdateManager: Auto-installing 1.0.21 
2015-05-29 14:41:49.5352 [Info] SyncTrayzor.Services.ProcessStartProvider: Starting C:\Program Files\SyncTrayzor\ProcessRunner.exe --nowindow -- "C:\Program Files\SyncTrayzor\ProcessRunner.exe" --runas --launch="\"C:\Program Files\SyncTrayzor\SyncTrayzor.exe\"" -- "C:\Users\syncuser\AppData\Local\Temp\SyncTrayzor\SyncTrayzorUpdate-1.0.21.exe" /SILENT 
2015-05-29 14:42:17.2647 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ExePath: C:\Program Files\SyncTrayzor 
2015-05-29 14:42:17.6837 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: LogFilePath: C:\Users\syncuser\AppData\Roaming\SyncTrayzor\logs 
2015-05-29 14:42:17.6837 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: SyncThingBackupPath: C:\Program Files\SyncTrayzor\syncthing.exe 
2015-05-29 14:42:17.6837 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFilePath: C:\Users\syncuser\AppData\Roaming\SyncTrayzor\config.xml 
2015-05-29 14:42:17.6837 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: ConfigurationFileBackupPath: C:\Users\syncuser\AppData\Roaming\SyncTrayzor\config-backups 
2015-05-29 14:42:17.6837 [Debug] SyncTrayzor.Services.Config.ApplicationPathsProvider: CefCachePath: C:\Users\syncuser\AppData\Local\SyncTrayzor\cef\cache 
2015-05-29 14:42:18.8808 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Loaded default configuration: <Configuration ShowTrayIconOnlyOnClose=False MinimizeToTray=False CloseToTray=True ShowSynchronizedBalloon=True ShowDeviceConnectivityBalloons=True SyncthingAddress=localhost:8384 StartSyncthingAutomatically=True SyncthingApiKey= SyncthingEnvironmentalVariables=[] SyncthingUseCustomHome=False SyncthingDenyUpgrade=False SyncthingRunLowPriority=False Folders=[] NotifyOfNewVersions=True LastNotifiedVersion= ObfuscateDeviceIDs=True UseComputerCulture=True SyncthingConsoleHeight=100 WindowPlacement= SyncthingWebBrowserZoomLevel=0 LastSeenInstallCount=0 SyncthingPath=%APPDATA%\SyncTrayzor\syncthing.exe SyncthingCustomHomePath=%LOCALAPPDATA%\SyncTrayzor\syncthing> 
2015-05-29 14:42:19.0638 [Debug] SyncTrayzor.Services.Config.ConfigurationProvider: Found existing configuration at C:\Users\syncuser\AppData\Roaming\SyncTrayzor\config.xml 
2015-05-29 14:42:19.3878 [Error] SyncTrayzor.Bootstrapper: An unhandled exception occurred 

That is then followed by the same stack trace mentioned above.

**Comment by canton7** [comment]
Mind posting the contents of `C:\Users\syncuser\AppData\Roaming\SyncTrayzor\config.xml`? Censor as appropriate.

**Comment by padraigkitterick** [comment]
It's empty... pretty sure it shouldn't be!

**Comment by padraigkitterick** [comment]
It's timestamp was about when I clicked the upgrade button.

**Comment by canton7** [comment]
Ah, I was worried that might be the case. The only thing I can think of is that the upgrade kicked in at exactly the wrong time: while SyncTrayzor was writing to its config file. Due to a legacy issue with the embedded browser component, the installer currently need to kill SyncTrayzor in quite an ugly way. There's the foundation for a fix for this out there, but I need to wait until people have upgrade to that version before I can put the other half of the fix in place!

I'm afraid you'll have to delete the (now empty) config file, and let SyncTrayzor regenerate it. If you've got a backup config file (they're generated during config file version migrations, and will be in `C:\Users\syncuser\AppData\Roaming\SyncTrayzor\config-backups`), you can copy that back and that will be used as a starting point.

**Comment by padraigkitterick** [comment]
Thanks - that fixed it. Despite not having a 'config-backups' folder, it still retained my settings (folders and paired peers) so everything is back up and running. Thanks for the help.

**Comment by canton7** [comment]
Yeah, Syncthing's config is separate from SyncTrayzor's. SyncTrayzor's config stores stuff like how to close to the tray, whether to watch folders for changes, the size of the console area, etc. For a full list, see what's in the settings menu.

I'll leave this issue open for now: I've had two people with corrupt config files recently (for completely different reasons), and it's something I should probably catch a bit better...

**Comment by canton7** [comment]
OK, I've got a better error message in there. Closing.
